### ISSUE TITLE
FBL / ARF support

### ISSUE THREAD

**Issue by alexroosenstein** [postalserver/postal#102]
Would be great if Postal could support feedback loop reports.

Perhaps even with a webhook event when a specific email is marked as spam.

**Comment by adamcooke** [comment]
I agree. This would be useful. I've marked this as an enhancement. Hopefully someone will be able to look at this in the near future.

**Comment by rsgehlot** [comment]
Do we any update on this, these days fbl is kind of very critical and mandatory to prevent your system..

**Comment by navinp** [comment]
Is there anyone here that can do this, even if I have to hire?
