### ISSUE TITLE
Configurable rotation/spread of IP pool

### ISSUE THREAD

**Issue by alexroosenstein** [postalserver/postal#104]
Adding a chance/probability to the IP addresses in an IP pool would allow you to manage the amount of traffic an IP handles. Currently it's completely random (literally RAND()).

Adding a probability would allow you to warm up IPs (gradually increase the probability over time).

Thus: be able to define a percentage a specific outgoing IP should roughly handle. Say you set IP 1.2.3.4. to 10%, it should only handle 10% of outgoing traffic, the other 90% should be spread over the remaining IPs (either evenly, or taking in account their set percentage if applicable)

Edit: I added a bounty.

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=44873265)](https://www.bountysource.com/issues/44873265-ip-pool-usage-probability)

**Comment by adamcooke** [comment]
It would be nice to have something to allow new IPs to be introduced slowly into a pool. As you say, right now it is totally random.

**Comment by wtom** [comment]
In case you still need it, i needed it and build something very quick myself. #833
