### ISSUE TITLE
Improve "Domains & DNS Configuration" page

### ISSUE THREAD

**Issue by oviliz** [postalserver/postal#1051]
https://github.com/postalhq/postal/wiki/Domains-&-DNS-Configuration

1. The assumed IP for tracking is 192.168._1_.4 but then is 192.168._0_.4 in the "Tracking domain" section.
> For this documentation we will assume you have allocated some IP addresses:
> ...
> - 192.168.1.4 - IPv4 address for the "fast" web server (used for tracking)
> ...
> - **Tracking domain** - to configure click & link tracking you'll need to configure a domain that will be used in rewritten links. This will point to the second IP address on your host. The second IP is used to distinguish traffic which is aimed at the management web server and that destined for the tracking web server.
> `track.mail.yourdomain.com.    IN    A     192.168.0.4`

2. The "Route domain" section creates an MX record pointing to _mx._mail.yourdomain.com but that's not previously defined in the page. I would think that should be pointing to mail.yourdomain.com instead?

> **Route domain** - if you wish to receive incoming e-mail by sending messages directly to created routes in Postal, you'll need to configure a domain for this just to point to your MX servers.
> `routes.mail.yourdomain.com.   IN    MX    10 mx.mail.yourdomain.com`

**Comment by uhlhosting** [comment]
How is the status of tracking in 2.0?

**Comment by willpower232** [comment]
I think the original issue has been dealt with in the new documentation https://docs.postalserver.io/install/dns-configuration

The underlying handling of tracking has completely changed and requires you to manage the web server virtualhost and SSL certificate yourself https://docs.postalserver.io/features/click-and-open-tracking#configuring-your-web-server
