### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by iammattmartin** [postalserver/postal#117]
Is there a way to change the date format?

`May 01, 2017 19:02` seems to be the default.

`01 May 2017 19:02` would be ideal for some geographic regions.

**Comment by catphish** [comment]
What dates are you referring to?

**Comment by mattmartincouk** [comment]
Any dates in the GUI are in the Month Day, Year format.

Unless you're American, you'd usually expect to see Day Month Year.

**Comment by catphish** [comment]
I suspect that internationalization of date formats would need to be part of a wider i18n project. Right now the interface is US English only (though it's plausible some British has slipped in there too).

**Comment by adamcooke** [comment]
There will certainly be some British English (although we do try to avoid it in most places but I refuse to spell colour without a u but I will happily use a Z instead of an S for words like "organization").
