### ISSUE TITLE
Automatically inject Sender header

### ISSUE THREAD

**Issue by catphish** [postalserver/postal#134]
We could potentially improve compatibility with clients that don't add `Sender` headers by injecting a Sender header with the contents of the MAIL FROM command in cases where the `From` address doesn't match a known domain, but the MAIL FROM command does.

**Comment by benjaoming** [comment]
Thanks for opening this. In relation to adding a sender header (if missing) for a given server (or credentials), has their been considerations of forcing a sender header to a specific identity in all cases?

I am thinking of a situation where the mail API is ONLY allowed to send as `robot@acme.org` and not for example `president@acme.org` ?

**Comment by willpower232** [comment]
@benjaoming Postal is not designed to regulate your emails in this way. It would be better to apply those restrictions within whatever program is creating your emails.

**Comment by benjaoming** [comment]
@willpower232 we don't want to delegate trust to 100 different integrations if we can enforce it centrally. Actually, we can't just delegate it. Is there something problematic with Postal handling this?

**Comment by willpower232** [comment]
Unfortunately Postal is only designed to send all emails it is told to. Apart from the one sending limit it imposes, there are no other limits available so if you want a limit, you will have to create a piece of software to sit between Postal and your organisations to reject unwanted messages.

**Comment by benjaoming** [comment]
@willpower232 being aware of the current scope of Postal, would you be able to see the value of adding a feature in Postal such that credentials can be restricted to only one Sender+From+Return-Path ? The feature would be contributed by me or someone else, this is not a request for maintainers to do work, this is just to know if there is a way to have things accepted into Postal.

The use case is something like this:

_As an administrator,_ I want to delegate email sending capability to a less trusted environment through a unique credential restricted to only sending on behalf of one email address.

_Such that_ in case of breach, I am sure that the environment can only send on behalf of `robot@example.org` and not `invoices@example.org`

**Comment by willpower232** [comment]
Whilst I can see the usefulness on the face of it, if someone is maliciously able to send emails then restricting the first part of the address won't do much to prevent anything.

If you could enforce the textual name and the email address then it might help slightly against things like social engineering, but fundamentally someone is still able to send email messages through your infrastructure so the net effect of applying such a restriction would just be more annoying for the official user.

**Comment by benjaoming** [comment]
@willpower232

> fundamentally someone is still able to send email messages through your infrastructure 

If an attacker with access to an environment with a Postal API credential is forced to send from robot@example.org then of course it's better than if they have the freedom to send from ceo.jane.doe@example.org -- this should be indisputable.

> If you could enforce the textual name and the email address then it might help slightly against things like social engineering

Forcing the textual name in Sender+From+Return-Path is a great idea, too, but maybe that's because you're actually buying into the logic that it mitigates attack vectors.

> so the net effect of applying such a restriction would just be more annoying for the official user.

Sorry if this was unclear: I was talking about introducing a non-default configuration option in Postal's credential handling and asking for the interest from maintainers in including a potential contribution.
