### ISSUE TITLE
Docker: Need to add Docker install instructions to the Wiki

### ISSUE THREAD

**Issue by jaydrogers** [postalserver/postal#1423]
# Problem
* [The Wiki ](https://github.com/postalhq/postal/wiki)references the Ubuntu 16.04 install
![image](https://user-images.githubusercontent.com/3174134/127230990-ef00cbf2-27b8-44a9-92b3-c607e0a4ed0d.png)

# Proposed solution
* Reference the new Docker install repo or at least include the same instructions on the wiki

# Next Steps
@adamcooke will need to get this updated since he has repo access.

**Comment by adamcooke** [comment]
I am planning to re-do all the documentation here relating to installation as soon as we're happy with the contents of the new [install repo](https://github.com/postalhq/install).

**Comment by willpower232** [comment]
Would it also be prudent to get away from the wiki and have markdown files managed in a repo for better collaboration?

**Comment by adamcooke** [comment]
That's not a terrible idea. 👍  I'm semi reluctant to put such things in *this* repo but a new `docs` repo might be nice. We can then accept pull requests far more easily!

**Comment by willpower232** [comment]
I think you can clone the existing wiki as a repo so you get all the existing markdown files to save all the copy pasting and then markdown also opens the door for a real documentation website with Jekyll or whatever.

**Comment by jaydrogers** [comment]
Everything is converted to the new docs site 🥳: https://docs.postalserver.io/

Feel free to look at the README of the docs repo on how to make changes: https://github.com/postalserver/docs

Any questions, let me know!
