### ISSUE TITLE
Enable GitHub Discussions and direct all support questions there

### ISSUE THREAD

**Issue by adamcooke** [postalserver/postal#1426]
Also, remove all outstanding support queries from the current issue list.

**Comment by jaydrogers** [comment]
I was just creating an issue on this, so let me merge my thoughts in here 😃

# Problem
* Github issues is littered with support questions
* This makes it very distracting for the things that need to get done

# Proposed solution
* Issues should be reserved for action items only
* Support can be moved to Github Discussions

### Issue template examples
We have an open source project where we use issue templates: https://github.com/serversideup/amplitudejs/issues/new/choose

The code for it can be found here: https://github.com/serversideup/amplitudejs/tree/master/.github/ISSUE_TEMPLATE

# What "done" looks like
- [ ] Create Github Discussions on the repository
- [ ] Add link to README file explaining where is the appropriate place to get help
- [ ] Add Github issue templates to the repository (with links to get support on Github Discussions)

# Next steps
@adamcooke & @willpower232: **What common items are required for every bug report?**

**For example:**
On our other open source repository, we require everyone to fill out:
1. Issue description
2. Environment (software version, browser version, etc)
3. Steps to reproduce
4. Expected results
5. Link to reproduce (probably not applicable to this project)
6. Additional details & screenshots

This is what it looks like:
![image](https://user-images.githubusercontent.com/3174134/127236464-2caaab89-c829-46f5-b0f0-47f3cc53fa27.png)

 **We also have two labels/statuses for bug reports:**
1. Bug: Needs confirmation (the default status when someone reports a bug)
2. Bug: Confirmed (someone part of the team confirmed and replicated this bug)

☝️ These two steps helped us trim all of the garbage requests and helped us stay focused on legit bug reports.

**From your perspective:**
Anything that should be included to speed up support and bug replication?

**Comment by willpower232** [comment]
Requesting log entries is very useful, particularly for SMTP issues where we need to understand what commands are being used.

Also presumably `postal status` will no longer make sense in the Glorious Dockerised Future so something like `docker-compose ps -a` will be useful to confirm which parts of Postal are running in the users environment.

As you mentioned, reproducing steps will be more useful than a link as all the Postal code will be here. If there is a nice way of outputting Postals current version, I imagine that will be very useful in these templates too.

**Comment by adamcooke** [comment]
I've added a note about log output to the bug template. I'll expand on it in the future when we've achieved full GDF.
