### ISSUE TITLE
Documentation: Create migration guide from 1.x to 2.x

### ISSUE THREAD

**Issue by jaydrogers** [postalserver/postal#1440]
# Background
There have been a number of changes to Postal recently 🥳

# Problem
* There are a lot of people running "1.x" of Postal, but there may be breaking changes when they upgrade to "2.x"

# Next steps
@adamcooke: Are you able to create documentation (possibly in the Wiki) on how a user would go from their "Postal 1.x server" to a "Postal 2.x" server?

**Comment by adamcooke** [comment]
Yes. The main difference between Postal 1.x and 2.0 will be the way it is installed. The actual software will be mostly the same and the databases aren't changing at all. Someone running Postal 1.x should be able to upgrade to Postal 2.0 by simply stopping their old processes and starting some new ones through Docker, in theory. 

I'll write a list of actual changes a bit nearer the time and we can work out what additional docs might be required then.

**Comment by willpower232** [comment]
Yeah it should be as easy as 
1. follow new install instructions
2. link to existing database and rabbitmq
3. `postal stop`
4. run any migrations
5. start version 2 from instructions
6. `rm /opt/postal/app`

Although we'll probably also take the opportunity of removing the ancient ubuntu server somewhere in there :sweat_smile:

**Comment by adamcooke** [comment]
The only other change will for people using open/click tracking. They will need to reconfigure their web proxy and issue certs for any domains they use for this.

**Comment by adamcooke** [comment]
I believe I have now compiled all the instructions needed to upgrade to v2. If anyone spots any problems or thinks anything could be better, please submit an issue or PR on the [docs repo](https://github.com/postalserver/docs).

https://docs.postalserver.io/install/upgrade-to-v2
