### ISSUE TITLE
Creating Users

### ISSUE THREAD

**Issue by ILoveYaToo** [postalserver/postal#145]
Hi,

Currently, it's difficult to create new users automatically as `postal make-user` creates a prompt for user details. I would absolutely love it if we could enter the username/password/details as arguments.

For example,
`postal make-user -fname Test -lname User -password pass -username testuser`

Thanks!

Side Note: The password is insecure, as it can be seen while being entered as well as in the shell's history file, but the user can always change it after logging in. Probably a better way would be for a password to be automatically generated and output by the command.

**Comment by adamcooke** [comment]
I like both these ideas. I'll get them implemented soon.

**Comment by zeeshanjamal16** [comment]
You can use bash feature and pipe the standard input to directly create user.

`printf 'test@example.com\nFname\nSname\nLongRand0mPassword' | postal make-user`

**Comment by stevus** [comment]
@adamcooke Any update on this?
