### ISSUE TITLE
Postal Mail Server errors 

### ISSUE THREAD

**Issue by monowar1** [postalserver/postal#1535]
Hello Everyone.
I have already set up a completely postal mail server everything is okay but when I send an email don't to send my email mail is pending also when I use it via SMTP (ERROR: The SMTP server has unexpectedly disconnected.) So please help me fix this issue.

I am using Contabo server ubuntu 18.04 and 20.04 same problem.

Thanks

**Comment by jaydrogers** [comment]
The question you are asking is more for support (not necessarily a reproducible bug that requires a code fix).

I'd recommend closing this issue and opening your question under "Discussions" https://github.com/postalserver/postal/discussions/new?category=Help-with-using-Postal
