### ISSUE TITLE
Worker Exiting with error 1

### ISSUE THREAD

**Issue by BigMSolutions** [postalserver/postal#1550]
this what i get when runing portal status
postal_cron_1       /docker-entrypoint.sh post ...   Up
postal_requeuer_1   /docker-entrypoint.sh post ...   Up
postal_smtp_1       /docker-entrypoint.sh post ...   Up
postal_web_1        /docker-entrypoint.sh post ...   Up
postal_worker_1     /docker-entrypoint.sh post ...   Exit 1

**Comment by seunex** [comment]
Hello @BigMSolutions 
How did you resolve this?

**Comment by mickbut-ler** [comment]
Did anyone fix this?

**Comment by willpower232** [comment]
Since people keep finding this issue, I will draw your attention to https://github.com/postalserver/postal/discussions/2211#discussioncomment-4026494

**Comment by shakibhasan09** [comment]
Same problem here

root@mail:~# postal status
      Name                     Command               State    Ports
-------------------------------------------------------------------
postal_cron_1       /docker-entrypoint.sh post ...   Up
postal_requeuer_1   /docker-entrypoint.sh post ...   Up
postal_smtp_1       /docker-entrypoint.sh post ...   Up
postal_web_1        /docker-entrypoint.sh post ...   Exit 1
postal_worker_1     /docker-entrypoint.sh post ...   Up

**Comment by almotaqqaf** [comment]
> > Hello @BigMSolutions How did you resolve this?
> 
> Hi
> 
> Please help me resolve the same issue.
> 
> ## root@mail:~# postal status
> Name Command State Ports
> postal_cron_1 /docker-entrypoint.sh post ... Up postal_requeuer_1 /docker-entrypoint.sh post ... Exit 1 postal_smtp_1 /docker-entrypoint.sh post ... Up postal_web_1 /docker-entrypoint.sh post ... Up postal_worker_1 /docker-entrypoint.sh post ... Exit 1 root@mail:~#
> 
> Thanks

I have the same situation, did you resolve it ?

**Comment by kayastha1988** [comment]
What's the main issue for auto stop for postal docker? I have installed Postal SMTP in my server. Sometime all docker containers automatically stopped. What's the reason behind this?

Thanks in advance
