### ISSUE TITLE
Allow us to add "suppressions" manually.

### ISSUE THREAD

**Issue by ro78** [postalserver/postal#156]
Hello,

I would be really nice to be able to add "suppressions" (recipients that should NOT be emailed) manually.

For example, I send an email, and the recipient reply with a request of stop emailing email instead of using the unsubscribe link, or send a request to abuse/postmaster : I want to be able to blacklist future sends manually in Postal.

Romain

**Comment by adamcooke** [comment]
The suppression list entries have an expiry. Postal is not an MLM so having something to stop it emailing people because they don't want to receive it is out of our scope. The suppression list is just for internal use.
