### ISSUE TITLE
Docker-compose Error

### ISSUE THREAD

**Issue by samykalem** [postalserver/postal#1600]
Hello, 
Just ran "postal initialize" and i'm getting the following error. 

Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

Docker-compose version:

docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.10
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020

I'm running a fresh and updated install of Ubuntu 20 LTS

**Comment by willpower232** [comment]
Your version of docker-compose is well over a year old, are you able to update it?

**Comment by samykalem** [comment]
You are right Will, It's strange that the ubuntu Repo is stating it's the latest...
I will do a manual update

apt update
Hit:1 https://download.docker.com/linux/ubuntu focal InRelease
Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:5 http://archive.ubuntu.com/ubuntu focal-security InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
root@redacted:/opt/postal/install# apt upgrade docker-compose
Reading package lists... Done
Building dependency tree
Reading state information... Done
docker-compose is already the newest version (1.25.0-1).
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@redacted:/opt/postal/install#

**Comment by Juanzin420** [comment]
Thank you for this! I was having the same problem, will try your solution

**Comment by samykalem** [comment]
For everyone, 
Run 
apt remove docker-compose
apt install pip
pip install docker-compose
