### ISSUE TITLE
No interface UI after upgrade from v1 to v2

### ISSUE THREAD

**Issue by ValentinPifu** [postalserver/postal#1602]
## Describe the bug

After upgrading from v1 to v2, our postal interface isn't showing the UI, only text.

## To Reproduce

From v1 to v2
1. mv /usr/bin/postal /usr/bin/postal.v1
2. a) git clone https://postalserver.io/start/install /opt/postal/install
2. b) sudo ln -s /opt/postal/install/bin/postal /usr/bin/postal
3. postal upgrade
4. postal start

## Expected behaviour

To see the default interface of postal.

## Screenshots

![Screenshot from 2021-09-23 16-44-43](https://user-images.githubusercontent.com/18114871/134518293-748b2d73-6b51-4c18-95c3-3c2200403311.png)
![Screenshot from 2021-09-23 16-44-17](https://user-images.githubusercontent.com/18114871/134518221-a8382e50-63a7-4cda-825e-1f06441543b4.png)

## Environment details 

 - OS: Ubuntu 18.04
 - Browser: Chrome/Firefox/Opera
 - Version: latest all of them
 - Type: desktop

## Additional information/context

All the containers are up and running and we don't see any errors in logs.

**Comment by willpower232** [comment]
The original nginx config would need to be updated/replaced because it has some references to the files which no longer make sense

V1: https://github.com/postalserver/postal/blob/4e5b621232f553ed48580bfa678918207ff81cc8/resource/nginx.cfg

V2: https://github.com/postalserver/postal/discussions/1534#discussioncomment-1158045

I think the upgrading documentation needs updating to include this fact.

**Comment by grrinch** [comment]
I confirm it is exactly what it was.

My current nginx configuration:

```
server {
 2     listen [::]:80;
 3     listen 0.0.0.0:80;
 4     server_name example.com;
 5     return 301 https://$host$request_uri;
 6 }
 7
 8 server {
 9     listen [::]:443 ssl;
10     listen 0.0.0.0:443 ssl;
11     server_name example.com;
12     ssl_certificate      /etc/letsencrypt/live/example.com/fullchain.pem;
13     ssl_certificate_key  /etc/letsencrypt/live/example.com/privkey.pem;
14     ssl_protocols TLSv1.2 TLSv1.1 TLSv1;
15     ssl_prefer_server_ciphers on;
16     ssl_ciphers EECDH+ECDSA+AESGCM:EECDH+//cut//GCM:DH+AES256:RSA+AESGCM:!aNU$
17
18     location / {
19        add_header  X-Robots-Tag "noindex, nofollow, nosnippet, noarchive";
20        client_max_body_size 50M;
21        proxy_set_header X-Real-IP  $remote_addr;
22        proxy_set_header Host $host;
23        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
24        proxy_set_header X-Forwarded-Proto https;
25        proxy_pass http://127.0.0.1:5000;
26     }
27 }
```

I have replaced my actual domain with example.com in the above snippet.

I agree, the nginx config while upgrading could be mentioned in the Docs. 

I would say, overall, that just disabling nginx (if not needed any longer) and replacing it with Caddy would be just fine.

Thanks for your help @willpower232 💪🏻
