### ISSUE TITLE
Webhooks Invalid SSL certificate with new letsencrypt root CA

### ISSUE THREAD

**Issue by KimCoCat1** [postalserver/postal#1619]
Since the change to their new root CA (https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/) Webhooks accessing any endpoints using letsencrypt  SSL certificates respond with 'Invalid SSL certificate' in postal under Webhooks - 'View History'

**Comment by CyberHackFR** [comment]
Same issues.
Found a temporary solution.
`if uri.scheme == 'https'
        connection.use_ssl = true
        connection.verify_mode = OpenSSL::SSL::VERIFY_PEER
        ssl = true
      else`

Removed verify SSL

`if uri.scheme == 'https'
        connection.use_ssl = true
        connection.verify_mode = OpenSSL::SSL::VERIFY_NONE
        ssl = true
      else`

May be useful to someone
Regards

**Comment by adamcooke** [comment]
This is not a Postal bug and removing SSL verification is not the solution to the problem you're experiencing.
