### ISSUE TITLE
Spam Checks : Timed out when scanning for spam

### ISSUE THREAD

**Issue by amisalabir** [postalserver/postal#1625]
Spamd is configured and active but is Postal I get this message "Timed out when scanning for spam"
<img width="692" alt="Screenshot 2021-10-07 at 12 24 06 AM" src="https://user-images.githubusercontent.com/1482502/136292384-9ac5adbf-8f95-4a04-a182-168e017f56b1.png">

Please help if anybody fix this

**Comment by amisalabir** [comment]
Hello @adamcooke thank you for your reply. I

**Comment by willpower232** [comment]
You should check your configuration and restart Postal as necessary. If you are still having problems then a discussion is best.
