### ISSUE TITLE
[Postal v2] SMTP TLS Caddy OpenSSL::PKey::RSAError: Neither PUB key nor PRIV key: nested asn1 error

### ISSUE THREAD

**Issue by bernardinosousa** [postalserver/postal#1630]
## Describe the bug
When setting smtp tls config error logs on sending email:
smtp_1      | [9] [2021-10-07T11:43:17.706] ERROR -- : [GHP9YJ] An error occurred while processing data from a client.
smtp_1      | [9] [2021-10-07T11:43:17.706] ERROR -- : [GHP9YJ] OpenSSL::PKey::RSAError: Neither PUB key nor PRIV key: nested asn1 error
smtp_1      | [9] [2021-10-07T11:43:17.706] ERROR -- : [GHP9YJ] /opt/postal/app/lib/postal/config.rb:130:in `initialize'
smtp_1      | [9] [2021-10-07T11:43:17.706] ERROR -- : [GHP9YJ] /opt/postal/app/lib/postal/config.rb:130:in `new'
smtp_1      | [9] [2021-10-07T11:43:17.706] ERROR -- : [GHP9YJ] /opt/postal/app/lib/postal/config.rb:130:in `smtp_private_key'

## To Reproduce

1. Copy caddy-data crt and key to /opt/postal/config
2. Edit postal.yml with smtp certificate and private key path with "/config/cert.crt and /config/cert.key"
3. Test smtp external connection

## Expected behaviour

Send email with TLS without giving error

## Environment details 

 - OS: Ubuntu 20.04

## Additional information/context

The solution that i found is changing Caddyfile to key type rsa2048

domain.com {
  reverse_proxy 127.0.0.1:5000
  tls {
    # Valid values are rsa2048, rsa4096, rsa8192, p256, and p384.
    # Default is currently p256.
    key_type rsa2048
  }
}

**Comment by adamcooke** [comment]
You're trying to use the private key generated by Caddy. This is not a support configuration nor is it documented anywhere.
