### ISSUE TITLE
Greylog logging does not work in v2

### ISSUE THREAD

**Issue by ndTEC** [postalserver/postal#1635]
After upgrading to v2 logs are not sent logstash.
In postal.yml i have:
logging:
  stdout: false
  root: # Automatically determined based on config root
  max_log_file_size: 20
  max_log_files: 10
  greylog:
  host: example.lan
  port: 12201

**Comment by willpower232** [comment]
I do vaguely have a memory of a PR where the spelling changed back and forth or something so maybe it was a thing previously
