### ISSUE TITLE
Error: "SSL_connect returned=1 errno=0 state=error: dh key too small"

### ISSUE THREAD

**Issue by ndTEC** [postalserver/postal#1641]
First of all i want you to know that before i opened this issue i looked if it was reported by someone else and i already applied those solutions without success.
The problem seems to be that postal refuses to send emails to servers which have SSL with weak Cipher.
I run the command **openssl s_client** on two mail servers to which we can send emails and to which we cannot. The difference i found is in the TLS version and Cypher of their SSL certificate. The failed one has TLS v1.2 Cypher DHE-RSA-AES256-SHA256 (which is weak) and the other TLSv1.3 Cypher TLS_AES_256_GCM_SHA384 (which is recommended). 
This results in a **Ephemeral Diffie-Hellman Key** too small for the failed server **Server Temp Key: DH, 1024 bits**
How can we tell Postal to still communicate with servers when Server Temp Key is small?

I am using v2 of Postal.

**Comment by willpower232** [comment]
See #1558 as you need to create your own docker image as any configuration changes won't persist if the container is replaced and may not be applied as the processes are already running (and restarting would remove the changes)

**Comment by willpower232** [comment]
Ah that should work but I think you need to apply it to the worker one as well

**Comment by ndTEC** [comment]
Finally. Now is working. So in the docker-compose.yml i added the /opt/openssl/openssl.cnf for the worker container also.
Thank you.

**Comment by casualmatt** [comment]
I have the same problem but i have the latest image, is this still not fix?

**Comment by ndTEC** [comment]
@casualmatt i am running v2.1 with this fix

**Comment by casualmatt** [comment]
I'm using 2.1 but the fix is not done, i probably need to use the work around.
