### ISSUE TITLE
Assets mismatch after upgrade from 1.x

### ISSUE THREAD

**Issue by hafrang** [postalserver/postal#1678]
## Describe the bug

After upgrade from 1.x to 2.1.0, the assets indicated to the client actually does not exist.

## To Reproduce

1. Upgrade from 1.x: https://docs.postalserver.io/install/upgrade-to-v2
2. Access to postal from your browser

## Screenshots

Indicated assets:
![image](https://user-images.githubusercontent.com/13354482/139588690-617ad90f-5b20-4a0b-9047-41edf2307afc.png)

Actual assets:
![image](https://user-images.githubusercontent.com/13354482/139588765-0f9c7eee-a72a-4eb4-84ca-ea2801d58c60.png)

## Environment details 

 - OS: Ubuntu 16.04 (server)
 - Browser: Edge (new)
 - Version: 2.1.0
 - Type: laptop

## Temporary fix

So, what I've done so far is to copy the assets to what is expected by the browser. Like this:
![image](https://user-images.githubusercontent.com/13354482/139589091-9aa7e37e-9de3-4b7d-9acf-dbf121686261.png)

Finally, I get this on the web application.
![image](https://user-images.githubusercontent.com/13354482/139589247-03ad988a-8f96-49eb-82b2-bb919fa9d7ce.png)

**Comment by willpower232** [comment]
When you're upgrading, you need to rewrite the nginx configuration. This is not currently documented but I would like to add a mention when I have some time to do so.

Have a look at https://github.com/postalserver/postal/issues/1668#issuecomment-954657653
