### ISSUE TITLE
Postal worker keeps sending request to http endpoint

### ISSUE THREAD

**Issue by ridwankustanto** [postalserver/postal#1706]
## Describe the bug

Hi, I'm new on Postal. And I wanna try to receive email from http endpoint. 

I found weird behavior with receiving emails from HTTP endpoint. I already setup HTTP endpoint and its route. Then I send email from my personal email to postal routes address.

It is successful and I got the mail to my endpoint. BUT, it keeps sending me the message. I checked the worker logs, and it said something like this:

![image](https://user-images.githubusercontent.com/19152005/141427673-3157ab2b-f0cf-4df4-8f72-f8b1fb6692d3.png)

It's like it started to scheduler to send it again or something.

## To Reproduce

1. Create Http endpoint
2. Create routes using http endpoint that you created before
3. Send email to the routes address

## Expected behaviour

Get message on http endpoint every 5 minutes, event tho http endpoint already received it before.

## Screenshots

And this is my setup:

![image](https://user-images.githubusercontent.com/19152005/141429156-3c4becad-1797-4a15-9180-d4fd01976d35.png)

This is log on my http endpoint:
![image](https://user-images.githubusercontent.com/19152005/141428724-75a2b078-0aa9-4090-a04f-a50ca845b84c.png)

## Environment details 

 - OS: Installed postal on ubuntu 20
 - Browser chrome
 - Version 2.1.0

**Comment by willpower232** [comment]
So you sent an email message to an address handled by Postal and received several requests to your ngrok?

**Comment by ridwankustanto** [comment]
> So you sent an email message to an address handled by Postal and received several requests to your ngrok?

Yes, that's what exactly happened to me. I already followed the documentation to give 200 OK to the response if I got the message.

I checked on Incoming Message and I have multiple identical messages received, 1 message / 5-10 minutes. But those multiple messages weren't sent from my personal email, I checked and it just sent one.

What makes it happen? I was thought maybe it because of this:

![image](https://user-images.githubusercontent.com/19152005/141449238-e0956bce-5700-4ccb-9a84-6e58a403f3b6.png)


But I already give 200 OK as a response.

**Comment by willpower232** [comment]
that should only be if it fails though, you should see your message logged in the messages tab in Postal and then see what happened to it on the right hand side?

**Comment by ridwankustanto** [comment]
> that should only be if it fails though, you should see your message logged in the messages tab in Postal and then see what happened to it on the right hand side?

![image](https://user-images.githubusercontent.com/19152005/141450861-41dbe375-cdcc-48d8-8e91-07fd0ec23c39.png)

Do you mean this? These messages are all the same

**Comment by willpower232** [comment]
you should be able to click on those messages for more details

**Comment by ridwankustanto** [comment]
> you should be able to click on those messages for more details

Yes, and they are exactly the same. It becomes weirder today, the postal couldn't read the message as success, because it tried to send me Mail Delivery Failed multiple times today.

![image](https://user-images.githubusercontent.com/19152005/141603033-bf140a62-6b96-4517-8d3e-f9c064da9d33.png)

Is this have something to do with misconfiguration DNS?

**Comment by ridwankustanto** [comment]
I almost forgot I found misplaced words on http endpoint format field. When I choose "Delivered as raw message", instead of raw message I got the hashed one and vice versa

![image](https://user-images.githubusercontent.com/19152005/141605017-9b4c89f4-b920-41b4-93b0-2aa700bebe73.png)

**Comment by ridwankustanto** [comment]
Anyway, I will close this issue since I solved this. I guess it was because of misconfiguration. I have google mail MX configuration on domain A, and I was moved to domain B which there is no MX configuration before, and it worked fine now.
