### ISSUE TITLE
Webhooks URL does not allow "%"

### ISSUE THREAD

**Issue by MrSnoozles** [postalserver/postal#1752]
## Describe the bug

When setting up a webhook with a URL that contains `%` (urlencoded character), I get the error **URL is invalid**

## To Reproduce

1. Go to your server
2. Go to Webhooks
2. Add a webhook
3. Enter a webhook url that contains urlencoded characters e.g. `https://chatserver.mycompany.com:5001/webapi/entry.cgi?api=Chat.External.Server&method=chatbot&version=2&token=A%22BWMM0I4PlQq5YGsY93Fqn6SPc39sCKkVuGY5iTASpQUDY0xD5k42fyuI7r2Ag0DPoHVdrG`
4. See error "URL is invalid"

## Expected behaviour

The webhook should get saved.

## Screenshots

![grafik](https://user-images.githubusercontent.com/17496592/144590443-8aa40221-84b9-4474-9edb-8398afeacb79.png)

**Comment by willpower232** [comment]
Glad you were able to figure out it was down to `%`

It looks like it is validated here https://github.com/postalserver/postal/blob/ea10ae18f10ec243c9e30a540a3de4d853155838/app/models/webhook.rb#L31

Do you know which character is being encoded or does synology literally want that exact URL?

**Comment by MrSnoozles** [comment]
Synology passes the token in encoded quotes. The webhook URL synology tells me to enter is

`https://www.mydomain.com:5001/webapi/entry.cgi?api=SYNO.Chat.External&method=incoming&version=2&token=%22tokenTokenTOkenMfq%22`

**Comment by willpower232** [comment]
ah yeah it wouldn't work either way, I'm not sure which approach @adamcooke would prefer, allowing `"` or allowing `%`

**Comment by dipakparmar** [comment]
Also, Microsoft Teams Webhook uses `@` in the URL, which also needs to be whitelisted. 

Url Structure is `https://xxxxxxxxxxxxxx.webhook.office.com/webhookb2/xxxxxxxxxxxxx`**@**`xxxxxxxxxxxxxx/IncomingWebhook/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/xxxxxxxxxxxx13`

**Comment by dipakparmar** [comment]
Updated regex for allowing **@** 

 `\Ahttps?\:\/\/[a-z0-9\-\.\_\?\=\&\@\/\+:]+\z`

**Comment by adamcooke** [comment]
Fixed in c60c69db1800775776da4c28c68001f230fe5888
