### ISSUE TITLE
postal_smtp_1 Exit 1 on 

### ISSUE THREAD

**Issue by DanteAnuj** [postalserver/postal#1831]
## Describe the bug

i was trying installing postal then I encountered this error when I run the **postal status** command 

error - 

postal_smtp_1      /docker-entrypoint.sh post   Exit 1

![postalissue](https://user-images.githubusercontent.com/58907150/151052932-8a7439ab-8b10-4466-828e-589dbd0b4ddb.png)

Screenshot link (in case above doesn't work) - https://prnt.sc/26j9ue9

## Environment details 

OS - Ubuntu [20]([url](url))

**Comment by adamcooke** [comment]
This doesn't sound like a bug. Check the logs for it. Post a Discussion if you still need help.

**Comment by DanteAnuj** [comment]
> This doesn't sound like a bug. Check the logs for it. Post a Discussion if you still need help.

I have created a Discussion  - https://github.com/postalserver/postal/discussions/1832
