### ISSUE TITLE
Tracking Domain setup prevents sub-sub-domains?

### ISSUE THREAD

**Issue by mvrahden** [postalserver/postal#1855]
## Describe the problem

The UI to configure tracking domains is preventing to define sub-sub-domains.

Say the organization domain is `example.com` (with MX records referring to `mail.example.com`) I want to setup the tracking domain as `click.mail` . `example.com` but the UI rejects this option with a banner showing "Name is invalid".

FYI: DNS checks for the actual domain are all green.

This leaves me a little confused. What is the ideal way to solve this? Or are there any technical limitations or best practices I'm missing?

**Comment by mvrahden** [comment]
@adamcooke or @willpower232 any hint on this one?

**Comment by willpower232** [comment]
I haven't had an opportunity to investigate but I guess the only issue might be certain combinations of CNAMEs

**Comment by adamcooke** [comment]
At present, tracking domains must exist on the root of the domain.

**Comment by mvrahden** [comment]
@adamcooke I'm wondering: is there any technical limitation for this rule to be in place or is it just because the validator is configured to say so?
