### ISSUE TITLE
SOFT FAIL

### ISSUE THREAD

**Issue by AlgoVoyager** [postalserver/postal#1896]
### Discussed in https://github.com/postalserver/postal/discussions/1895

<div type='discussions-op-text'>

<sup>Originally posted by **AlgoVoyager** March  4, 2022</sup>
![image](https://user-images.githubusercontent.com/53928002/156777745-745d90a4-1fa6-4f56-b107-3aea3433f279.png)
piliz welp!</div>

**Comment by adamcooke** [comment]
This is not a bug.

**Comment by AlgoVoyager** [comment]
whats the problem i'm facing, why its soft fail
