### ISSUE TITLE
mail tracking pixel link issue

### ISSUE THREAD

**Issue by yuanedge** [postalserver/postal#1910]
## Describe the bug

I got a email tracking from postal server, but the pixel link lacks a H.

![image](https://user-images.githubusercontent.com/101683514/158501510-189a1921-c1ae-4be5-873f-5afde0d83820.png)

**Comment by willpower232** [comment]
Judging by the original line of code https://github.com/postalserver/postal/blob/6f1d92b974517ed37e3f7caface84ec6ddf08808/lib/postal/message_parser.rb#L134

It seems there are several characters missing and the quotes are quite messed up.

How are you generating the email?

**Comment by willpower232** [comment]
Presuming you are both working together, Postal really is not designed for this arrangement so I'm not sure you'll be able to achieve everything working perfectly. There are known issues with using click tracking and SMTP so I think you have a few problems here.
