### ISSUE TITLE
530 From/Sender name is not valid

### ISSUE THREAD

**Issue by PCL-CrisKolkman** [postalserver/postal#1917]
Hello,

All incoming emails are being delivered to our Sophos UTM for scanning etc.
I would like to setup the Sophos UTM to then deliver the messages to the Postal server but when this is done I see this error:
`2022:03:19-10:51:50 mailserver exim-out[1163]: 2022-03-19 10:51:50 1nVVkU-0000Ii-Fq ** info@domain.com P=<sender@gmail.com> R=static_route_hostlist T=static_smtp H=192.168.200.48 [192.168.200.48]:25: SMTP error from remote mail server after end of data: 530 From/Sender name is not valid`

192.168.200.48 is the Postal SMTP server.

When I deliver messages to the Postal server directly (so without the Sophos UTM in between) everything is fine, but this is not a situation we want (because the UTM controls a lot of the traffic on port 25 and is blocking attacks etc.).

What could be wrong here?

**Comment by willpower232** [comment]
> From/Sender name is not valid

the domain name used in the from address of the message you are sending must be set up in the same organisation as the credential.

**Comment by PCL-CrisKolkman** [comment]
@willpower232 It's an incoming message so the sender will never be in the same orginisation.
Please confirm if an issue is solved next time before just closing it.

**Comment by willpower232** [comment]
the way you are trying to use Postal requires the domain names to be set up in the organisation, there isn't a bug in Postal here
