### ISSUE TITLE
Postal not working

### ISSUE THREAD

**Issue by PCL-CrisKolkman** [postalserver/postal#1920]
Hello,

I've setup a complete new VM (Ubuntu 18.04 LTS) and followed every step in:
https://docs.postalserver.io/install/prerequisites and https://docs.postalserver.io/install/installation

When I want to go to the web page, I get:
ERR_SSL_PROTOCOL_ERROR

And not able to access the web page at all.

**Comment by willpower232** [comment]
You have not set up your nginx/caddy properly.

**Comment by PCL-CrisKolkman** [comment]
> You have not set up your nginx/caddy properly.

Issue is nor solved with this answer.
I followed the instructions step by step and it's not working.

@willpower232 Please re-open.

**Comment by willpower232** [comment]
this is not a problem with Postal, please open a discussion with a copy of your nginx/caddy host configuration

**Comment by sinnbeck** [comment]
I had the same issue. It was due to me running running the docker command before setting up DNS. I added the dns record, stopped/removed the container and ran the command again
```
docker run -d \
   --name postal-caddy \
   --restart always \
   --network host \
   -v /opt/postal/config/Caddyfile:/etc/caddy/Caddyfile \
   -v /opt/postal/caddy-data:/data \
   caddy
