### ISSUE TITLE
Outgoing messages not respecting routing

### ISSUE THREAD

**Issue by PCL-CrisKolkman** [postalserver/postal#1922]
Hello,

I've setup incoming routing which is working perfectly, but outgoing messages are not respecting those routes (while they should imo).

When you have for example a Wordpress website which is using the Postal server as SMTP server, this is an outgoing message.
But that message is being send to a domain which is known on the Postal server and also has incoming routing on that Postal server, but the Postal server is trying to send the message to the MX records for that domain (which fails) instead of delivering it to the correct endpoint.

**Comment by willpower232** [comment]
The only way for this to work is if the MX records for the domain to also deliver to Postal otherwise the message will never be incoming.
