### ISSUE TITLE
Outgoing messages not respecting routing

### ISSUE THREAD

**Issue by PCL-CrisKolkman** [postalserver/postal#1924]
Reopen #1922
@willpower232 Would be nice if you only close issues when it's confirmed that they can be closed.

> Hello,
> 
> I've setup incoming routing which is working perfectly, but outgoing messages are not respecting those routes (while they should imo).
> 
> When you have for example a Wordpress website which is using the Postal server as SMTP server, this is an outgoing message.
> But that message is being send to a domain which is known on the Postal server and also has incoming routing on that Postal server, but the Postal server is trying to send the message to the MX records for that domain (which fails) instead of delivering it to the correct endpoint.

The MX records **are** pointing to the Postal server itself, but when Postal tries to deliver the message, below error is seen:

![image](https://user-images.githubusercontent.com/97805195/159450752-0eda95c9-1be0-4971-a5c0-49db7196841a.png)

**Comment by adamcooke** [comment]
That's a timeout of the SMTP send sending messages. Please don't re-open this unless you can provide something to show this is a Postal bug (I highly doubt it is!)

If you need help debugging your installation, you can try posting a Discussion.

**Comment by PCL-CrisKolkman** [comment]
> That's a timeout of the SMTP send sending messages. Please don't re-open this unless you can provide something to show this is a Postal bug (I highly doubt it is!)
> 
> If you need help debugging your installation, you can try posting a Discussion.

@adamcooke Incoming messages to those same domains to the same Postal server are delivered just fine, so I **highly** doubt something else is wrong :)
