### ISSUE TITLE
WEB ui NOT reachable

### ISSUE THREAD

**Issue by robertpreshyl** [postalserver/postal#1925]
I run "postal start and Postal Status" and everything’s up and running BUT web ui using http://mail.yourdomain.com:5000  gives "This site can't be reached error" please any help?

**Comment by willpower232** [comment]
Port 5000 should not be exposed to the internet, it should be going via a proxy such as Caddy or nginx. You might want to look at your firewall settings. If you are still having problems please open a discussion with more detail

**Comment by robertpreshyl** [comment]
My firewall settings is good to me because i can access internet and visit other pages and i had postal setup before now and it was working good... i just changed the vps and reinstalled postal server and now i have this issue... could this be because i recently switched to 1.1.1.1dns on my router?
