### ISSUE TITLE
SMTP process hangs when authentication update query is slow

### ISSUE THREAD

**Issue by Wouter0100** [postalserver/postal#1926]
## Describe the bug

SMTP daemon hangs when authentication update query is slow. This results in the fact that it does not respond to any incoming connections, and as far as I've seen the daemon seems to be developed to allow this.

## To Reproduce

It is fairly difficult to reproduce. We had an issue where the MySQL server was not performing optimally, and this would result in hiccups in the SMTP process. 

## Expected behaviour

Have it still accept and process connections even though a single connection is a bit slower.

## Environment details 

 - OS: Ubuntu 20.04 / Docker
 - Version: latest

**Comment by willpower232** [comment]
Can you elaborate on "not performing optimally"? Have you made any changes to the MySQL config at all? Not suggesting you've caused this problem but its possible some other changes might accidentally avoid this issue.

**Comment by Wouter0100** [comment]
Sure thing. The `not performing optimally` was a disk I/O issue where the host hypervisor was overloaded, and as a result of this - some issues arose from within the SMTP process, where it would hang the whole process (not even accept new connections) during a query in the SMTP auth step. This [query (or method that executes a query)](https://github.com/postalserver/postal/blob/9f0697f194209f5fae5e451ba8fb888413fe37fa/lib/postal/smtp_server/client.rb#L211).

This query would take between a couple of ms to ~1 and sometimes 2 seconds. We fixed these underlying disk I/O issues, but this will not "fix" the issue SMTP is having, where it would block the whole process for a small amount of time during the query. It will only make it less obvious as the query is way faster now (and thus hangs for a less amount of time).

**Comment by Wouter0100** [comment]
Thanks for your detailed response. I feared that was the case, but I was unable to confirm it as is.

We will most likely perform a rewrite ourselves and, if possible, contribute it back. For now, we simple run the SMTP daemon multiple times.

**Comment by willpower232** [comment]
You might be interested in https://github.com/postalserver/postal/pull/751 where someone attempted this previously.
