### ISSUE TITLE
smtp server should not authenticate random username

### ISSUE THREAD

**Issue by The-3x** [postalserver/postal#1930]
## Description

When using the smtp server to send mails i have seen that you can use the username anything. like you have set the username for an smtp api as "johndoe" but we can authenticate the system via "imnotjohn".

## Expected behavior
Any unknown user should be blocked by smtp server.

**Comment by willpower232** [comment]
The username doesn't mean anything to Postal as the credentials are already random strings and stored in plain text. Adding a username would not make anything more secure as it would be the equivalent of having two passwords in the same credential.
