### ISSUE TITLE
NoMethodError: undefined method `include?' for nil:NilClass when simulating incoming messages

### ISSUE THREAD

**Issue by ninoarsov** [postalserver/postal#1938]
## Describe the bug

Hey! I'm running Postal on a VPS. So far, everything has been working smoothly, including sending email.
However, when I choose the "simulate incoming message" from the web interface, I received an error:

`NoMethodError: undefined method 'include?' for nil:NilClass

Support Ref: J-GJEMLKFMTX`

So far, I have set up an organization, a domain, provisioned a mail server and I have set up all the DNS records. Everything is marked green and seems to be flawless.

## Expected behaviour

The email message appears in the incoming messages section.

## Screenshots

![image](https://user-images.githubusercontent.com/3225161/161234188-60c6d35d-0e61-4f27-b329-e2ce99fa0cfa.png)
![image](https://user-images.githubusercontent.com/3225161/161234339-4552af53-87e3-4eb0-8072-772455cb80fb.png)
![image](https://user-images.githubusercontent.com/3225161/161234618-9f68d814-d70f-4cc6-ad56-e2381eedbca7.png)

## Environment details 

 - OS: Ubuntu 20.04
 - Browser: Brave/Safari/Firefox

## Additional information/context

So far, I haven't noticed anything strange in the container logs.
Thanks!

**Comment by willpower232** [comment]
`J-GJEMLKFMTX` should be locatable in one of the logs so you can see if there is a stack trace or any more information about the message.

Otherwise you'll have to find "undefined method" in the logs for the stack trace so we can see where it occurred.
