### ISSUE TITLE
Cant send email via smtp, using sendblaster

### ISSUE THREAD

**Issue by admin1101** [postalserver/postal#1944]
### Discussed in https://github.com/postalserver/postal/discussions/1943

<div type='discussions-op-text'>

<sup>Originally posted by **admin1101** April  6, 2022</sup>
![image](https://user-images.githubusercontent.com/103117630/161969704-ef66b18e-00ee-4374-aca3-2b0f44dddfa6.png)

I keep getting this after trying to test smtp
domain is correctly configured and every TXT and CNAME record has been added.

ERROR: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 46.21.153.246:25
</div>

**Comment by willpower232** [comment]
not a problem with postal, already being discussed in discussion
