### ISSUE TITLE
Issues sending mail with Postal

### ISSUE THREAD

**Issue by Larkings** [postalserver/postal#1960]
### Discussed in https://github.com/postalserver/postal/discussions/1959

<div type='discussions-op-text'>

<sup>Originally posted by **Larkings** April 19, 2022</sup>
I am having this issue
I have set up an SMTP server and installed Postal

When I send a test email / my email says "Pending"

smtper.net I receive this error:

SMTP send error
Failure sending mail.
Unable to read data from the transport connection: The connection was closed.

Gmail responded:
530 Authentication required

When I run Postal Status:

root@mail:~# postal status
Name Command State Ports

postal_cron_1 /docker-entrypoint.sh post ... Up
postal_requeuer_1 /docker-entrypoint.sh post ... Exit 1
postal_smtp_1 /docker-entrypoint.sh post ... Up
postal_web_1 /docker-entrypoint.sh post ... Up
postal_worker_1 /docker-entrypoint.sh post ... Exit 1

How do I get all of these to say "up" ??
Please help..</div>

**Comment by willpower232** [comment]
Please don't duplicate discussions into issues

**Comment by mail2sathishkumar008** [comment]
> Please don't duplicate discussions into issues

Hey @willpower232 Im also facing the same issue. can u pls help me to resolve it?
