### ISSUE TITLE
i can't connect smtp on 3rd party app

### ISSUE THREAD

**Issue by nicefhub** [postalserver/postal#1962]
I can only send mails directly from postal app but each time i tried to connect smtp to mailing applications it give me this error: 

"Connection could not be established with (host smtp-server) :stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol Log data: ++ Starting Swift_SmtpTransport !! Connection could not be established with host (host smtp-server) :stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol (code: 0)
++ Starting Swift_SmtpTransport !! Connection could not be established with host (host smtp-server) :stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol (code: 0)"

please how do i resolve this?

**Comment by willpower232** [comment]
it sounds like you have not configured SSL in Postal. You will need to enable it and give Postal a certificate to use. If you are having trouble with that, feel free to open a new discussion with more information.
