### ISSUE TITLE
SMTP TLS/SSL: Let's Encrypt Cert does not work on V2 (works absolutely fine on V1)

### ISSUE THREAD

**Issue by plamenh** [postalserver/postal#1966]
Can't upgrade because of this.

For some reason when I follow the upgrade instructions (including fixing the cert paths in the config file), SSL/TLS does not work. I also can't get to smtp container output to see what the problem is.

Therefore, I am not sure if it's got anything to do with ECDSA / RSA: https://github.com/postalserver/postal/issues/1248 (This is an old issue from 2020, so I am guessing not)

Can someone advise how I can see what's going on inside the smtp container?

Thanks.

**Comment by willpower232** [comment]
Nothing has changed with how Postal handles SSL certificates so it does still have a problem with ECDSA.

When upgrading to V2, the docker container probably won't have access to the SSL certificate files if they aren't in the config folder or in a docker mount you add so that could also be the problem.

Please open a discussion if the above doesn't help.

**Comment by plamenh** [comment]
Well, the certs are in the config folder and they are owned by root (docker runs as root):

```
root@p2:~# ls -lah /opt/postal/certs
total 20K
drwxr-xr-x  2 root root 4.0K Jun 10  2020 .
drwxr-xr-x 11 root root 4.0K Apr 22 09:17 ..
-rw-r--r--  1 root root 5.5K Apr 22 00:00 fullchain.pem
-rw-------  1 root root 1.7K Apr 22 00:00 privkey.pem
```

Also, config is set correctly:

```
smtp_server:
  tls_enabled: true
  tls_certificate_path: /certs/fullchain.pem
  tls_private_key_path: /certs/privkey.pem
```

This is why I am asking for a way to check smtp container output, I need to find out what's wrong.

**Comment by willpower232** [comment]
You can see in the docker-compose file that only the config folder makes it into the container

https://github.com/postalserver/install/blob/ce3ddfa66e18a7509ebec9c7aebf84fcd70675df/templates/docker-compose.yml#L17

so your certs folder won't make it into the container at all without either moving the certs folder into the config folder or adding a certs line to the docker-compose.yml file then you'll be able to correct the config paths.

in v2, you can do `postal logs smtp` to see the logs or `postal bash smtp` if you want to explore the container from the terminal

**Comment by plamenh** [comment]
Ok, got it, so `/opt/postal/certs` need to move to `/opt/postal/config/certs`.

Thanks.
