### ISSUE TITLE
Emails are not getting out from Addtional IP's.

### ISSUE THREAD

**Issue by mjml1982** [postalserver/postal#1970]
Hello,

I set up an IP pool in postal and added the additional IP's to the main server network but it's not sending emails from the additional IPs only from the main IP.

It's saying no SMTP servers were available, I have double-checked with the main server IP and port 25 is open and telnet also connects on additional IPs on port 25, I'm also able to login to SSH using additional IPs, I have set up all the DNS records properly but still it's not working.

Here is the screenshot of the error.

## Screenshots

![image](https://user-images.githubusercontent.com/38753697/165393812-12de7f8a-c90c-4083-bbc1-e2a9e6044a3e.png)

 - OS: Ubuntu 18.x

Thanks.

**Comment by mjml1982** [comment]
When i run the command `sudo postal logs smtp_server or smtp` it does not give any logs.

**Comment by willpower232** [comment]
do you need the sudo part? what is the output?
