### ISSUE TITLE
Retry mails that were held when address is removed from the suppression list

### ISSUE THREAD

**Issue by bigon** [postalserver/postal#1973]
Hello,

There are a lot of (closed) discussion/bugs (#1300, #257, #239, #1286,...) about retrying the mails that have been put on hold automatically or in bulk, wouldn't the simplest be to just retry the mails that have been put on hold because the email address has been put in the suppression list?

I was actually expecting this to happen when seeing that the suppression list had and expiration date

**Comment by willpower232** [comment]
Postal holds mail that it has either been told should not be delivered or thinks should not be delivered so it doesn't usually make sense for the message to be sent after it has been held, that is why it is a manual process.

**Comment by bigon** [comment]
Well if the suppression is removed, we are not in the "[postal] thinks should not be delivered" anymore IMVHO

**Comment by teoxrr** [comment]
But if held messages are not going to be delivered, how to clean'em? Maybe should be thousands.
