### ISSUE TITLE
"Check my records are correct" never ends for any additional domains (Postal 2.1.1) 

### ISSUE THREAD

**Issue by andrsharov** [postalserver/postal#1975]
I was setup postal server for my technical domain: all work good.

But when I tried to add an another domain DNS checks always fails: it never ends.

Steps to reproduce: 

First you need to setup your first domain, then:

1. Add new organization.
2. Add new mail server.
3. In the mail server "Domains" add new domain.
4. Make settings in your domain registator.
5. Wait some time ( I am already wait more 24 hours). 
6. Press "Check my records are correct" button.
7. Check will not never ends.

Maybe can you to advice me how to debug ?

P.S.: I need to add 11 (eleven) additional domains (2nd level).

![Check_my_records_are_correct](https://user-images.githubusercontent.com/44819772/165787785-a25e2654-635e-4068-ad96-4c2a0ecad818.png)

**Comment by willpower232** [comment]
If you have already waited a day then its likely the server is having a problem resolving the correct DNS. You can ssh onto your server and check the server is capable of resolving the record with `dig txt yourdomain.com`.

**Comment by andrsharov** [comment]
@willpower232 , Thanks for soo quick answer.

I think all good with my DNS: 

How I checked this? 

On the the host machine: 

- `dig txt yourdomain.com` gives me the correct answer 
```
yourdomain.com.            86048   IN      TXT     "v=spf1 include:_spf.google.com include:spf.mail.yourdomain.com include:amazonses.com include:mailgun.org ~all"
```
Inside all docker containers: 

- Login with root user `docker exec -it -u 0 postal-web-1 /bin/bash`
- Update `apt update`
- Install dnsutils `apt install dnsutils`
- `dig txt yourdomain.com` gives me correct answer 
```
yourdomain.com.            86048   IN      TXT     "v=spf1 include:_spf.google.com include:spf.mail.yourdomain.com include:amazonses.com include:mailgun.org ~all"
```

**Comment by andrsharov** [comment]
For test puprposes I can use domain: `t-mod.ru`. 

I only add only one SPF record, but when I press the button checks always fails: it never ends. 

`dig txt t-mod.ru` gives me the corret answer. 

![image](https://user-images.githubusercontent.com/44819772/165801704-57c43e66-c20d-4d76-b699-ad55eca68d35.png)

**Comment by andrsharov** [comment]
@willpower232 , Exactly ! 

The blue button never stops for any additional domain.

For the first domain the blue button always work correctly. I special maked mistackes in DNS record in the first domain , after DNS update, Blue button show it corrently ( I mean it shows error ) , then I was corrected DNS values for the right values , and blue button shows all green 

P.S.: I also so this Discusion https://github.com/postalserver/postal/discussions/1971 . similar symptoms .

**Comment by willpower232** [comment]
If you open your browsers developer tools (usually the F12 key) and have a look at the network tab, you might be able to see what error message happens when the button is clicked.

**Comment by andrsharov** [comment]
Hi, @willpower232 .

There are two archives from F12 Google Chrome developer tools : 

- success.zip - for the first domain;
- fail.zip - for the any additional domain;

Different is in the time of execution of `check` request. 

[fail.zip](https://github.com/postalserver/postal/files/8612566/fail.zip)
[success.zip](https://github.com/postalserver/postal/files/8612567/success.zip)

**Comment by andrsharov** [comment]
@willpower232 , I was resolved problem.

In the file `postal.yml` I was setup this:
```
general:
  use_local_ns_for_domains: true
```
Main problem was that our cloud provider Selectel has blocked any outgoing DNS requests up to any DNS Servers, exclude his own servers.  But I think postal was ignored system DNS setting, and are use servers hardcoded in the code.

Please nail down in the instruction to always check permissions for outside DNS ( 53/udp ) requests  from the host machene.

=))))))
