### ISSUE TITLE
Please Ican't make a new admin user on postal, what might be the issue?

### ISSUE THREAD

**Issue by admin1101** [postalserver/postal#1976]
![image](https://user-images.githubusercontent.com/103117630/165829991-b68dc55f-7d1a-4b07-b43c-6698c7f39ef2.png)

Please I can't make a new admin user on postal, what might be the issue?

**Comment by admin1101** [comment]
`I need help fixing this

**Comment by willpower232** [comment]
You can see in the docs that the command to run is `postal make-user`

https://docs.postalserver.io/install/installation#initializing-the-database

If you can't run other linux-specific commands then that is not a Postal issue
