### ISSUE TITLE
Docker containers don't automatically start or restart when killed

### ISSUE THREAD

**Issue by memcorrupt** [postalserver/postal#1984]
I have to run `postal start` every time I restart the underlying server. Also, if I kill the processes, the containers don't automatically restart. This happens after updating to v2 using the guide on the docs, and then updating the nginx config to reflect the new caddy config.

**Comment by willpower232** [comment]
Everyone setup will be slightly different so Postal doesn't specify how it is kept alive.

The least complicated option IMHO is to add a restart policy to the docker-compose.yml file something like this https://progressivecoder.com/docker-compose-restart-policies-to-manage-docker-containers/

Other people have tried things in #1610 which may be more appropriate for how you are running Postal.
