### ISSUE TITLE
TLS/SSL encryption for Postal smtp

### ISSUE THREAD

**Issue by fav22** [postalserver/postal#1985]
Hello, can someone here help me on how to install ssl/tls encryption for postal smtp please? Thanks very much

**Comment by willpower232** [comment]
You need to supply these config values including a path to a certificate file.

https://github.com/postalserver/postal/blob/9f0697f194209f5fae5e451ba8fb888413fe37fa/config/postal.defaults.yml#L68-L70

**Comment by fav22** [comment]
Thank you, i will do this and give feedback

**Comment by KnudH** [comment]
@fav22 their is some thing you need to notice to get this work and their are many discussions about it

I think postal dont support implicit TLS (the realy secure TLS) but only explicit TLS (STARTTLS). Or am I wrong @willpower232?

**Comment by ThatProgrammerr** [comment]
Sorry for re-opening this, but what cert do I need for the smtp.cert and smtp.key? I tried copying the one Caddy was using but it seems that isn't correct. Do I just generate a new cert  with certbot for the root domain postal is hosting on and use that?

**Comment by willpower232** [comment]
If you rummage through the issues here, you'll see that there is a way to asking Caddy to create certificates using RSA which allows you to reuse the same certificate file.

As these certificates are regenerated every few months, there is a need to restart Postal at some point before the certificate expires and after the certificate has been automagically replaced.

**Comment by ThatProgrammerr** [comment]
> If you rummage through the issues here, you'll see that there is a way to asking Caddy to create certificates using RSA which allows you to reuse the same certificate file.
> 
> As these certificates are regenerated every few months, there is a need to restart Postal at some point before the certificate expires and after the certificate has been automagically replaced.

Is there a chance you can send me the issue? I'd love to be able to do exactly this bu t couldn't find that issue.

**Comment by willpower232** [comment]
I think I saw it first on https://github.com/postalserver/postal/discussions/1572
