### ISSUE TITLE
Setup Postal With Sub Domain, Can't Receive Email

### ISSUE THREAD

**Issue by fav22** [postalserver/postal#1989]
## Describe the bug

Hi, 

I'm not sure if it's a bug or missing configuration. I can send email but I can't receive email even my DNS configuration is passed. I suspect it because I setup my postal with subdomain on my MX record. 

## To Reproduce

1. Setup postal with subdomain
2. Set MX configuration sub.domain.com sub.domain.com; 10
3. Point ip to sub.domain.com

## Expected behaviour

I want to receive email with my subdomain like: mail@sub.domain.com

## My configuration

I follow all the DNS setup from this Postal Dns Documentation. But instead of mydomain.com MX 10 mail.mydomain.com, I set it up like mail.mydomain.com MX 10 mail.mydomain.com.

## Environment details 

 - OS: UBUNTU
</div>

**Comment by willpower232** [comment]
I would verify that sub.domain.com was not a CNAME, if it is then adding MX records to it won't work and it will need to be changed to an A.

If this isn't the problem, please open a discussion with some error message or output that you do have when you try to email sub.domain.com.

**Comment by fav22** [comment]
Hello, thank you for your reply!  I think the issue was ports 25 blocked by my hosting provider (contabo), what i don't understand is i don't even use ports 25 for with postal, instead i use 465/587
