### ISSUE TITLE
Postal breaks when clicking DNS setup

### ISSUE THREAD

**Issue by jazer143** [postalserver/postal#1993]
## Describe the bug

Hi There, Anyone here has the solution per subject matter. Just suddenly unable to edit the domain/DNS setup.

Is this bug, related to what I performed in the GUI. I did add domains in organization level, then removed the domain and added in server level. Something conflict with it. Thanks

web_1       | [9] [2022-05-18T09:46:00.598] INFO -- : Completed 500 Internal Server Error in 43ms (ActiveRecord: 6.7ms)
web_1       | [9] [2022-05-18T09:46:00.599] FATAL -- :
web_1       | [9] [2022-05-18T09:46:00.599] FATAL -- : ActionView::Template::Error (undefined method `join' for "postal.xxx.xx":String):
web_1       | [9] [2022-05-18T09:46:00.599] FATAL -- :      99:     If you wish to receive incoming e-mail for this domain, you need to add the following MX records
web_1       |     100:     to the domain. You don't have to do this and we'll only tell you if they're set up or not. Both
web_1       |     101:     records should be priority <b>10</b>.
web_1       |     102:   %pre.codeBlock.u-margin= Postal.config.dns.mx_records.join("\n")
web_1       | [9] [2022-05-18T09:46:00.599] FATAL -- :
web_1       | [9] [2022-05-18T09:46:00.599] FATAL -- : app/views/domains/setup.html.haml:102:in `_app_views_domains_setup_html_haml___3061569241756760880_70042260205540'
web_1       | lib/postal/tracking_middleware.rb:12:in `call'

**Comment by willpower232** [comment]
MX records in the config file need to be specified as a list on multiple lines even if there is only one.

https://github.com/postalserver/postal/blob/9f0697f194209f5fae5e451ba8fb888413fe37fa/config/postal.defaults.yml#L85-L86
