### ISSUE TITLE
(Installer) - ConfigTemplate - DNS instructions 404

### ISSUE THREAD

**Issue by wadabum** [postalserver/postal#1998]
-> https://postalserver.io/start/install
generated `postal.yml` contains
```
dns:
  # Specify the DNS records that you have configured. Refer to the documentation at
  # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
  # information about these.
```
what basically 404´s.

-> Replace with `https://docs.postalserver.io/install/dns-configuration` or similar?

**Comment by willpower232** [comment]
Ah good spot, you wanna make a PR to update it?

https://github.com/postalserver/install/blob/ce3ddfa66e18a7509ebec9c7aebf84fcd70675df/examples/postal.yml#L48

**Comment by cleaverm** [comment]
@adamcooke I just started with Postal and came across this too. Looks like the [install](https://github.com/postalserver/install) repo has been untouched for over a year. The Postal docs still mention it, and it worked ok for me (:pray:). Some of the open PRs looks like easy wins - I would open one for this issue too if the repo gets some attention :smile:

**Comment by willpower232** [comment]
The install repo requires very little maintenance so that is why it is quiet over there. If you have the capacity to make PRs then by all means go ahead.
