### ISSUE TITLE
Cram Md5 not authenticatin correctly

### ISSUE THREAD

**Issue by samykalem** [postalserver/postal#2009]
Hello, 
I noticed that my CRAM-MD5 challenges keep failing.  Is there anyways i could disable that auth ? I can confirm that is the right challenge response. It should of been accepted. 
Anyone had that issue before ? 

LOG 

[8] [2022-06-02T13:57:43.009] DEBUG -- : [KRFHGM]    Connection opened from REDACTED
smtp_1      | [8] [2022-06-02T13:57:43.009] DEBUG -- : [KRFHGM]    Client identified as REDACTED
smtp_1      | [8] [2022-06-02T13:57:43.089] DEBUG -- : [KRFHGM] <= ehlo [REDACTED]
smtp_1      | [8] [2022-06-02T13:57:43.099] DEBUG -- : [KRFHGM] => 250-My capabilities are
smtp_1      | [8] [2022-06-02T13:57:43.099] DEBUG -- : [KRFHGM] => 250-STARTTLS
smtp_1      | [8] [2022-06-02T13:57:43.099] DEBUG -- : [KRFHGM] => 250 AUTH CRAM-MD5 PLAIN LOGIN
smtp_1      | [8] [2022-06-02T13:57:43.179] DEBUG -- : [KRFHGM] <= STARTTLS
smtp_1      | [8] [2022-06-02T13:57:43.180] DEBUG -- : [KRFHGM] => 220 Ready to start TLS
smtp_1      | [8] [2022-06-02T13:57:43.949] DEBUG -- : [KRFHGM] <= ehlo [REDACTED]
smtp_1      | [8] [2022-06-02T13:57:43.957] DEBUG -- : [KRFHGM] => 250-My capabilities are
smtp_1      | [8] [2022-06-02T13:57:43.958] DEBUG -- : [KRFHGM] => 250 AUTH CRAM-MD5 PLAIN LOGIN
smtp_1      | [8] [2022-06-02T13:57:44.038] DEBUG -- : [KRFHGM] <= AUTH CRAM-MD5
smtp_1      | [8] [2022-06-02T13:57:44.038] DEBUG -- : [KRFHGM] => 334 *REDACTED challenge *
smtp_1      | [8] [2022-06-02T13:57:44.058] DEBUG -- : [KRFHGM] <= *REDACTED responsechallenge *
smtp_1      | [8] [2022-06-02T13:57:44.062] DEBUG -- : [KRFHGM] => 535 Denied
smtp_1      | [8] [2022-06-02T13:57:44.082] DEBUG -- : [KRFHGM] <= AUTH PLAIN [redacted]
smtp_1      | [8] [2022-06-02T13:57:44.099] DEBUG -- : [KRFHGM] => 235 Granted for redacted
smtp_1      | [8] [2022-06-02T13:57:44.119] DEBUG -- : [KRFHGM] <= mail FROM:<redacted>
smtp_1      | [8] [2022-06-02T13:57:44.119] DEBUG -- : [KRFHGM] => 250 OK
smtp_1      | [8] [2022-06-02T13:57:44.139] DEBUG -- : [KRFHGM] <= rcpt TO:<redacted>
smtp_1      | [8] [2022-06-02T13:57:44.140] DEBUG -- : [KRFHGM] Added external address 'redacted'
smtp_1      | [8] [2022-06-02T13:57:44.140] DEBUG -- : [KRFHGM] => 250 OK
smtp_1      | [8] [2022-06-02T13:57:44.159] DEBUG -- : [KRFHGM] <= data
smtp_1      | [8] [2022-06-02T13:57:44.159] DEBUG -- : [KRFHGM] => 354 Go ahead
smtp_1      | [8] [2022-06-02T13:57:44.179] DEBUG -- : [KRFHGM] <= From:redacted
smtp_1      | [8] [2022-06-02T13:57:44.179] DEBUG -- : [KRFHGM] <= To: redacted
smtp_1      | [8] [2022-06-02T13:57:44.180] DEBUG -- : [KRFHGM] <= Subject: Test Message from smtptest at 2022-06-02 09:57:42
smtp_1      | [8] [2022-06-02T13:57:44.180] DEBUG -- : [KRFHGM] <=
smtp_1      | [8] [2022-06-02T13:57:44.180] DEBUG -- : [KRFHGM] <= Test message from the smtptest tool sent at 2022-06-02 09:57:42
smtp_1      | [8] [2022-06-02T13:57:44.181] DEBUG -- : [KRFHGM] <= .
smtp_1      | [8] [2022-06-02T13:57:44.439] DEBUG -- : [KRFHGM] => 250 OK
smtp_1      | [8] [2022-06-02T13:57:44.458] DEBUG -- : [KRFHGM] <= quit

**Comment by willpower232** [comment]
The last time someone reported an issue with it, there was a problem with the username https://github.com/postalserver/postal/issues/414#issuecomment-401848161
