### ISSUE TITLE
Support Caddy On-Demand TLS

### ISSUE THREAD

**Issue by playworker** [postalserver/postal#2043]
### Discussed in https://github.com/postalserver/postal/discussions/2041

<div type='discussions-op-text'>

<sup>Originally posted by **playworker** June 28, 2022</sup>
Apologies if this is already supported - we're in the middle of researching upgrading to Postal v2 and I can't see anything in the docs.

Caddy supports on-demand TLS: https://caddyserver.com/docs/automatic-https#on-demand-tls

Which I think means that we wouldn't need to manually add new tracking domains to the Caddyfile, but if I understand correctly it needs an endpoint in Postal that it can call to check if it should generate certs for that domain.

Here's some more info: https://caddy.community/t/automatic-tls-not-working-with-cname-redirect/11372/2

> It’s just a GET request with a query ?domain={hostname}. Respond with status 200 if :+1:, respond with anything else (4xx usually) for :-1:

This seems like it would be a great addition, if it's not already in place :)</div>

**Comment by willpower232** [comment]
doesn't need to be an issue if its already a discussion
