### ISSUE TITLE
forwardfor not respected

### ISSUE THREAD

**Issue by Trapulo** [postalserver/postal#2056]
## Describe the bug

I've Postal behind HAProxy, that forward HTTP(s) requests. Tracking works well (both hidden images and link tracking), but Postal does not respect forwardfor in activity log.

When it reports that an email has been opened or a link clicked, it says "from X.X.X.X" where X.X.X.X is the HAProxy address, not the original client address.

I think this is a bug...

## To Reproduce

1. Enable link tracking
2. Run Postal behind a reverse proxy
3. Check activity log for a tracked email

## Expected behaviour

I expect to see the remote client IP address, not the proxy IP.

## Environment details 

 - Postal 2.1.1
 - HAProxy with forwardfor  enabled

**Comment by masihfathi** [comment]
@Trapulo can help about HAProxy config and postal caddy config for handling multiple instance of postal servers.

**Comment by Trapulo** [comment]
In HAProxy I simply forward "any host starting pstr." (all my tracking instances start with pstr, eg. pstr.domain.com) to postal Web server

**Comment by masihfathi** [comment]
Thanks for your respose.
i need a sample of postal.yml for postal cluster.
 i change caddy file of postals to point to ip and also i dont know what value need for host in postal.yml. but i just get a blank page after calling haproxy domain.
 ```
 web:
  # The host that the management interface will be available on
  host: ip??
  # The protocol that requests to the management interface should happen on
  protocol: http
 ```
 for Caddyfile of server 1
 ```
 http://ip1 {
  reverse_proxy 127.0.0.1:5000 {
    header_up X-Forwarded-Proto https
    header_up X-Postal-Track-Host "1"
  }
}
 ```
 
 for haproxy server config i used this 


```# Global settings
global
    log /dev/log local0
    log /dev/log local1 notice
    maxconn 4096
    user haproxy
    group haproxy
    daemon

    # Default SSL material locations
    ca-base /etc/ssl/certs
    crt-base /etc/ssl/private

    # Default ciphers for SSL
    ssl-default-bind-ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA
    ssl-default-bind-options no-sslv3 no-tlsv10

# Default settings for proxies
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

# Redirect HTTP to HTTPS
frontend http_redirect
    bind *:80
    mode http
    redirect scheme https code 301 if !{ ssl_fc }

# HTTPS frontend
frontend https_in
    bind *:443 ssl crt {crt path}
    mode http
    option http-server-close
    option forwardfor
    reqadd X-Forwarded-Proto:\ https
    default_backend app_servers

# Backend for HTTPS Servers
backend https_servers
    mode tcp
    balance roundrobin
    server server1 ip1:443 check
    server server2 ip2:443 check

# Frontend for SMTP (Port 25)
frontend smtp_in
    bind *:25
    mode tcp
    default_backend smtp_servers

# Backend for SMTP Servers
backend smtp_servers
    mode tcp
    balance roundrobin
    server server1 ip1:25 check
    server server2 ip2:25 check

# Frontend for Submission (Port 587)
frontend submission_in
    bind *:587
    mode tcp
    default_backend submission_servers

# Backend for Submission Servers
backend submission_servers
    mode tcp
    balance roundrobin
    server server1 ip1:587 check
    server server2 ip2:587 check

# Application servers backend
backend app_servers
    mode http
    balance roundrobin
    option httpchk HEAD / HTTP/1.1\r\nHost:localhost
    server app1 ip1:80 check
    server app2 ip2:80 check
```

**Comment by masihfathi** [comment]
> Thanks for your respose. i need a sample of postal.yml for postal cluster. i change caddy file of postals to point to ip and also i dont know what value need for host in postal.yml. but i just get a blank page after calling haproxy domain.
> 
> ```
> web:
>  # The host that the management interface will be available on
>  host: ip??
>  # The protocol that requests to the management interface should happen on
>  protocol: http
> ```
> 
> for Caddyfile of server 1
> 
> ```
> http://ip1 {
>  reverse_proxy 127.0.0.1:5000 {
>    header_up X-Forwarded-Proto https
>    header_up X-Postal-Track-Host "1"
>  }
> }
> ```
> 
> for haproxy server config i used this
> 
> ```
> global
>     log /dev/log local0
>     log /dev/log local1 notice
>     maxconn 4096
>     user haproxy
>     group haproxy
>     daemon
> 
>     # Default SSL material locations
>     ca-base /etc/ssl/certs
>     crt-base /etc/ssl/private
> 
>     # Default ciphers for SSL
>     ssl-default-bind-ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA
>     ssl-default-bind-options no-sslv3 no-tlsv10
> 
> # Default settings for proxies
> defaults
>     log     global
>     mode    http
>     option  httplog
>     option  dontlognull
>     timeout connect 5000ms
>     timeout client  50000ms
>     timeout server  50000ms
>     errorfile 400 /etc/haproxy/errors/400.http
>     errorfile 403 /etc/haproxy/errors/403.http
>     errorfile 408 /etc/haproxy/errors/408.http
>     errorfile 500 /etc/haproxy/errors/500.http
>     errorfile 502 /etc/haproxy/errors/502.http
>     errorfile 503 /etc/haproxy/errors/503.http
>     errorfile 504 /etc/haproxy/errors/504.http
> 
> # Redirect HTTP to HTTPS
> frontend http_redirect
>     bind *:80
>     mode http
>     redirect scheme https code 301 if !{ ssl_fc }
> 
> # HTTPS frontend
> frontend https_in
>     bind *:443 ssl crt {crt path}
>     mode http
>     option http-server-close
>     option forwardfor
>     reqadd X-Forwarded-Proto:\ https
>     default_backend app_servers
> 
> # Backend for HTTPS Servers
> backend https_servers
>     mode tcp
>     balance roundrobin
>     server server1 ip1:443 check
>     server server2 ip2:443 check
> 
> # Frontend for SMTP (Port 25)
> frontend smtp_in
>     bind *:25
>     mode tcp
>     default_backend smtp_servers
> 
> # Backend for SMTP Servers
> backend smtp_servers
>     mode tcp
>     balance roundrobin
>     server server1 ip1:25 check
>     server server2 ip2:25 check
> 
> # Frontend for Submission (Port 587)
> frontend submission_in
>     bind *:587
>     mode tcp
>     default_backend submission_servers
> 
> # Backend for Submission Servers
> backend submission_servers
>     mode tcp
>     balance roundrobin
>     server server1 ip1:587 check
>     server server2 ip2:587 check
> 
> # Application servers backend
> backend app_servers
>     mode http
>     balance roundrobin
>     option httpchk HEAD / HTTP/1.1\r\nHost:localhost
>     server app1 ip1:80 check
>     server app2 ip2:80 check
> ```

@adamcooke 
Hi Adam, Would you please help me about this haproxy approach and postal configs needed for this issue.
excuse me for taking your time regarding this issue
