### ISSUE TITLE
Update to Ruby 3

### ISSUE THREAD

**Issue by petamoriken** [postalserver/postal#2073]
## Describe the bug

Since Ruby 2.6.x is EOL, it is recommended to upgrade to version 2.7.x as soon as possible.

cf: https://www.ruby-lang.org/en/downloads/branches/

**Comment by petamoriken** [comment]
Ruby 2.7 goes EOL next month.

https://www.ruby-lang.org/en/downloads/branches/

**Comment by uhlhosting** [comment]
@petamoriken you are also free to help with upgrade process submit PR.

**Comment by petamoriken** [comment]
I'm not familiar with the Ruby ecosystem, but I'll give it a try if no one else is working on it in the future.

**Comment by catphish** [comment]
Resolved by 957b784658cda8c4c95cf1f2b65e05d99d23d427

**Comment by petamoriken** [comment]
Thanks a lot!
