### ISSUE TITLE
Running HA Rabbit in K8s causes duplicate or more emails

### ISSUE THREAD

**Issue by chrism417** [postalserver/postal#2111]
## Describe the bug

When running RabbitMQ in HA in kubernetes (3 pods), emails are duplicated and maybe even more than duplicated

## To Reproduce

Run RabbitMQ HA

## Expected behaviour

Rabbit to be highly available in case one pod goes down Postal can still connect

## Screenshots

Here's a screenshot of before/after me scaling down to only 1 Rabbit, note the messages per minute

![image](https://user-images.githubusercontent.com/57097380/184184602-d248e30c-f3e4-42d7-bd79-6f0b2e8926c3.png)

Can someone explain this behavior?

**Comment by willpower232** [comment]
as mentioned in https://github.com/postalserver/postal/discussions/2103, I'm not sure how you load balance amongst instances of RabbitMQ but I imagine your setup was somehow taking input from several queues simultaneously leading to the duplication. I don't know enough about RabbitMQ or Ruby on Rails to know how to fix off the top of my head but definitely something worth addressing in documentation if not in code.

**Comment by catphish** [comment]
I'm going to close this ticket because Rabbit will be removed in Postal v3 so any Rabbit related issues will be best resolved by upgrading once that version is stable.
