### ISSUE TITLE
Error in documentation - Click & Open tracking

### ISSUE THREAD

**Issue by sGoico** [postalserver/postal#2124]
## Tracking configuration snippet in the docs is wrong

Configuration snippet for nginx in the docs to enable "Click & Open tracking" has an extra colon that makes config fail.

## To Reproduce

1. Go to https://docs.postalserver.io/features/click-and-open-tracking/
2. Search "X-Postal-Track-Host: 1" in the text
3. Use that config in nginx and it will fail

## Expected behaviour

I expected postal to redirect rewritten tracking links based on the received header from the reverse proxy.

## Additional information/context

I spent some hours reviewing the config and testing a lot of different things. I came across a sample config WITHOUT the colon and decided to test it. After the change, everything started working as expected.

**Comment by willpower232** [comment]
The sentence describes how headers are sent in raw HTTP requests so is correct however as you say, it needs to be adapted into the proxy server being used (nginx, caddy, apache, etc).

For example, the install repo contains [a caddyfile example of this](https://github.com/postalserver/install/blob/ce3ddfa66e18a7509ebec9c7aebf84fcd70675df/examples/Caddyfile#L12).

Postal shouldn't document how to add headers for each proxy server software as that would add a lot of extra effort for not a lot of benefit.

**Comment by sGoico** [comment]
Hey @willpower232 roger that. I assumed it was the actual config line.
I know about Caddy but didn't use it because I was going to use a pre-existent reverse proxy in our infrastructure.

Thank you.
