### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR after install

### ISSUE THREAD

**Issue by joshuacadman01** [postalserver/postal#2133]
I have followed the docs and installed Postal on a Ubuntu server, I have followed the docs and have had no errors when installing, however I am unable to view the UI when I type in my domain (post.techspire.uk), this points to the correct IP of the server and I have checked on a DNS propagation tool, firewall points port 80 & 443 to the server and I ran the caddy code, but no luck.

Has anyone experienced this before and would be able to offer some advice?

**Comment by Neykuratick** [comment]
did you fix it?

**Comment by willpower232** [comment]
Looks like you figured it out in the end, this error usually means the certificate was not set up quite right.
