### ISSUE TITLE
end of file reached problem with microsoft domains

### ISSUE THREAD

**Issue by javierllovet** [postalserver/postal#2192]
We have issues when we tried to send emails to outlook.com hotmail.com or other comian that hosted by office 365, we have the issue to send emails ans mark as Soft Fail.

The problem for each message is the same and the description is

end of file reached

For other domains we dont have the problem just for microsoft.

![image](https://user-images.githubusercontent.com/73400666/196995832-27074840-b539-43b4-b57a-0b9ef627de3f.png)

**Comment by willpower232** [comment]
> no SMTP servers were available

make sure that your server provider has allowed you to send email

**Comment by jishanalibd** [comment]
> > no SMTP servers were available
> 
> make sure that your server provider has allowed you to send email

How can I make sure? I had same issue. I can connect the address by telnet from the VPS but postal gives that error!
