### ISSUE TITLE
postal_worker_1     /docker-entrypoint.sh post ...   Exit 1 Error

### ISSUE THREAD

**Issue by mail2sathishkumar008** [postalserver/postal#2212]
### Discussed in https://github.com/postalserver/postal/discussions/2211

<div type='discussions-op-text'>

<sup>Originally posted by **mail2sathishkumar008** October 31, 2022</sup>
Hi,

Please help me to resolve the issue.

postal_cron_1       /docker-entrypoint.sh post ...   Up
postal_requeuer_1   /docker-entrypoint.sh post ...   Exit 1
postal_smtp_1       /docker-entrypoint.sh post ...   Up
postal_web_1        /docker-entrypoint.sh post ...   Up
postal_worker_1     /docker-entrypoint.sh post ...   Exit 1</div>

**Comment by uhlhosting** [comment]
Provide logs, and do not overpost it!

**Comment by willpower232** [comment]
not an issue with postal, discussing in #2211
