### ISSUE TITLE
Multiple Emails Sent to Same Address

### ISSUE THREAD

**Issue by jmdunsing** [postalserver/postal#2222]
## Describe the bug

While expanding volume to use multiple workers, I noticed the number of emails sent in the last hour skyrocketed past my daily queue. Upon investigating webhooks from postal, it appears at least a few hundred people were sent the same email, with a few unfortunate souls receiving up to 17 (!) copies over a couple minutes. From what I can guess, the multiple workers overloaded my sql database, and the workers were performing actions on the same emails simulataneously. Luckily I noticed it before it did this for days... 

## Expected behaviour

I have not looked into postal's code, but it may at least be a design improvement to ensure records are locked in sql before actions are taken on them. Realize that could have a sink in performance, but having that option in my mind is cheap insurance against upsetting the folks on my email list.

## Environment details 

 - OS: Ubuntu 20.04
 - Postal version 2.1.1

**Comment by willpower232** [comment]
> While expanding volume to use multiple workers

Can you elaborate on this? I don't think you need modify any storage, just need to use the scale argument?

**Comment by jmdunsing** [comment]
Yes, I expanded workers when starting postal using the following command: postal start --scale worker=8 for a total of 8 workers.

**Comment by willpower232** [comment]
17 copies shouldn't be possible unless there are multiple copies in your database to begin with?

**Comment by jmdunsing** [comment]
I just checked everywhere I could. I only have a record of each of these emails being sent to postal only once.

**Comment by jmdunsing** [comment]
Looks like I was wrong. Not a postal issue.
