### ISSUE TITLE
400 error on API requests

### ISSUE THREAD

**Issue by TuguldurJ** [postalserver/postal#2231]
I am using the latest version of postal with 50 workers. Sending maximum about 130 message/minute. 
I configured mysql server following guide: #697
But Every message out of 10 messages fails with 400 error when using API send request. 
I think its related to postal web server performance.
Is it possible to maximize the performance of the postal web server? And how? And why this error occurs frequently.

**Comment by willpower232** [comment]
You will need to look at the output of the 400 response to see what the problem is.

**Comment by TuguldurJ** [comment]
Thank you for support!
During these days, I tried to find the portal web log. Unfortunately, could not find it. 
In v2, previous version without docker, we can clearly see the logs of the Web API requests in the postal.
`postal logs -f worker` shows only worker's logs. not web log.  
How can I get more log files?

400 error means HTTP API is not responding and cannot process requests.

**Comment by willpower232** [comment]
You need to look at the output of the response in your code, I don't think the information would be captured in the logs.
