### ISSUE TITLE
Reverse Proxy Errors

### ISSUE THREAD

**Issue by AToska21** [postalserver/postal#2254]
Hello! I have been trying to setup a Postal instance on a fresh VmWare ESXi VM behind HAProxy on a PFSense router. But it seems postal thinks it uses HTTP when I connect from HTTPS. Yes, I did set the config option to HTTPS but it still did nothing. Attached is the logs of the instance.
```
cron_1      | [8] [2022-11-25T19:41:19.286] INFO -- : Starting clock for 4 events: [ every-1-minutes every-hour every-hour every-day ]
cron_1      | [8] [2022-11-25T19:41:19.290] INFO -- : Triggering 'every-1-minutes'
requeuer_1  | [9] [2022-11-25T19:41:19.253] INFO -- : Running message requeuer...
smtp_1      | [8] [2022-11-25T19:41:19.319] INFO -- : Listening on  :::25
web_1       | Puma starting in single mode...
web_1       | * Puma version: 5.6.2 (ruby 2.6.10-p210) ("Birdie's Version")
web_1       | *  Min threads: 5
web_1       | *  Max threads: 5
web_1       | *  Environment: production
web_1       | *          PID: 8
web_1       | * Listening on http://192.168.20.106:5000
web_1       | Use Ctrl-C to stop
web_1       | [8] [2022-11-25T19:41:30.218] INFO -- : Started GET "/" for 192.168.20.1 at 2022-11-25 19:41:30 +0000
web_1       | [8] [2022-11-25T19:41:30.219] INFO -- : Processing by OrganizationsController#index as HTML
web_1       | [8] [2022-11-25T19:41:30.224] INFO -- : Redirected to http://<domain>/login?return_to=%2F
web_1       | [8] [2022-11-25T19:41:30.224] INFO -- : Filter chain halted as :login_required rendered or redirected
web_1       | [8] [2022-11-25T19:41:30.224] INFO -- : Completed 302 Found in 5ms
web_1       | 192.168.20.1 - - [25/Nov/2022:19:41:30 +0000] "GET / HTTP/1.1" 302 - 0.0266
web_1       | [8] [2022-11-25T19:41:30.288] INFO -- : Started GET "/login?return_to=%2F" for 192.168.20.1 at 2022-11-25 19:41:30 +0000
web_1       | [8] [2022-11-25T19:41:30.293] INFO -- : Processing by SessionsController#new as HTML
web_1       | [8] [2022-11-25T19:41:30.293] INFO -- :   Parameters: {"return_to"=>"/"}
web_1       | [8] [2022-11-25T19:41:30.295] INFO -- :   Rendering sessions/new.html.haml within layouts/sub
web_1       | [8] [2022-11-25T19:41:30.303] INFO -- :   Rendered sessions/new.html.haml within layouts/sub (8.0ms)
web_1       | [8] [2022-11-25T19:41:30.307] INFO -- : Completed 200 OK in 14ms (Views: 12.9ms)
web_1       | 192.168.20.1 - - [25/Nov/2022:19:41:30 +0000] "GET /login?return_to=%2F HTTP/1.1" 200 - 0.0216
web_1       | [8] [2022-11-25T19:41:32.150] INFO -- : Started POST "/login" for 192.168.20.1 at 2022-11-25 19:41:32 +0000
web_1       | [8] [2022-11-25T19:41:32.151] INFO -- : Processing by SessionsController#create as HTML
web_1       | [8] [2022-11-25T19:41:32.151] INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"oVFL74UmCLR9tYe9PfCd2mDbfHWrVoctmNIkdWawoDByT5o3oTOTSU/4P/ZhjO2H1BxFEasTy4xhv3GECj1b5g==", "return_to"=>"/", "email_address"=>"<email>", "password"=>"[FILTERED]", "commit"=>"Login"}
web_1       | [8] [2022-11-25T19:41:32.152] WARN -- : HTTP Origin header (https://<domain>) didn't match request.base_url (http://<domain>)
web_1       | [8] [2022-11-25T19:41:32.152] INFO -- : Completed 422 Unprocessable Entity in 1ms
web_1       | [8] [2022-11-25T19:41:32.153] FATAL -- :
web_1       | [8] [2022-11-25T19:41:32.153] FATAL -- : ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
web_1       | [8] [2022-11-25T19:41:32.153] FATAL -- :
web_1       | [8] [2022-11-25T19:41:32.154] FATAL -- : lib/postal/tracking_middleware.rb:12:in `call'
web_1       | 192.168.20.1 - - [25/Nov/2022:19:41:32 +0000] "POST /422 HTTP/1.1" 422 1547 0.0110
worker_1    | [9] [2022-11-25T19:41:22.242] INFO -- : Worker running with 4 threads
worker_1    | [9] [2022-11-25T19:41:22.251] INFO -- : [DDWDAOKS0U] Started processing RequeueWebhooksJob job
worker_1    | [9] [2022-11-25T19:41:22.256] INFO -- : Joined main queue
worker_1    | [9] [2022-11-25T19:41:22.262] INFO -- : [LEQCGLVC2X] Started processing SendNotificationsJob job
worker_1    | [9] [2022-11-25T19:41:22.320] INFO -- : [DDWDAOKS0U] Finished processing RequeueWebhooksJob job in 0.068362494s
worker_1    | [9] [2022-11-25T19:41:22.369] INFO -- : [LEQCGLVC2X] Finished processing SendNotificationsJob job in 0.10646666s
```
I tried searching for the "request.url" but to no avail. Thanks in advance!

**Comment by willpower232** [comment]
If you're having proxy problems it is likely that you're missing a few headers at some point. Here are some common ones used in nginx as listed in this very repo (a long time ago) https://github.com/postalserver/postal/blob/41d9014d4750eec48f0b208681f20112ddf8e17f/resource/nginx.cfg#L33-L36

**Comment by AToska21** [comment]
> If you're having proxy problems it is likely that you're missing a few headers at some point. Here are some common ones used in nginx as listed in this very repo (a long time ago)
> 
> https://github.com/postalserver/postal/blob/41d9014d4750eec48f0b208681f20112ddf8e17f/resource/nginx.cfg#L33-L36

I'm not using NGINX, and it seems to be a postal problem, not a proxy problem.

**Comment by willpower232** [comment]
if you can confirm that you are definitely passing those headers to Postal then that will narrow down what the problem is.

The headers will be needed regardless of what proxy software is involved, it is just convenient this repo used to include an nginx example.

**Comment by dchase-sir** [comment]
Just to add a comment, I had this issue and it's because I logged in to the web interface prior to setting up nginx.. To fix, I logged out from the https:// and http:// sides, then logged back in to https:// and it worked fine.

**Comment by mmorales99** [comment]
Hello!
Having similar issue.
I have configured everything ok, then changed Caddy for IIS since i have more sites running under.
I have Docker Desktop under Windows 10.
To make postal work, i had to manually enable Host Networking, which is disabled by default under windows environments.

<img width="1045" height="465" alt="Image" src="https://github.com/user-attachments/assets/2ba2eddd-b656-40f1-8cf9-2452dc260d5b" />

Then configured my site as normally for reverse proxying with IIS.
Even added the headers:

<img width="691" height="845" alt="Image" src="https://github.com/user-attachments/assets/e068daf5-57ec-4745-96e8-f6a00a0b931d" />

Site has a valid SSL certificate; DNS is well configured.
Postal.yaml has correct web_hostname, web_protocol and smtp_hostname.
Ports are correctly open and configured at router and firewall. Machine ports clear and open for Postal to take them.
In attachment, i added the web.config with domain name removed cause privacy. See original filename is `web.config`, name changed for avoiding .config files restriction in github issues.

[mail_web.config--.xml](https://github.com/user-attachments/files/22120810/mail_web.config--.xml)
