### ISSUE TITLE
Add a private/public mode to Postal

### ISSUE THREAD

**Issue by belghitioth** [postalserver/postal#2288]
### Discussed in https://github.com/postalserver/postal/discussions/2286

<div type='discussions-op-text'>

<sup>Originally posted by **belghitioth** December 12, 2022</sup>
I am trying to use Postal for one of my client to manage our business needs but we don't want to display messages information as it is sensitive data.

I would like to add a private/public mode to Postal in order to not display sensitive content from emails such as attachments, plain text, plain html.

Using one new variable in the file `config/postal.defaults.yml`

`public_mode: false` to not display sensitive data from incoming and outgoing messages

**Public Mode: OFF**

<img width="1255" alt="Capture d’écran 2022-12-12 à 13 48 33" src="https://user-images.githubusercontent.com/17969052/207063661-97a0d612-3269-44ab-aec1-4f16392cbe0d.png">
<img width="1242" alt="Capture d’écran 2022-12-12 à 13 50 04" src="https://user-images.githubusercontent.com/17969052/207063665-4111f96c-4cb2-4d0d-b799-9bf24b4c4cde.png">

**Public Mode: On**
<img width="1249" alt="Capture d’écran 2022-12-12 à 15 00 37" src="https://user-images.githubusercontent.com/17969052/207064271-d3a40088-9376-4bf3-9f6a-e6fdb152f75b.png">

Here is the link of the PR: https://github.com/postalserver/postal/pull/2287

</div>

**Comment by willpower232** [comment]
Please don't open duplicate messages, having the PR and discussion open is more than enough.
