### ISSUE TITLE
checking postal status after complete installations shows this error

### ISSUE THREAD

**Issue by Bugspiderlee** [postalserver/postal#2333]
postal_worker_1     /docker-entrypoint.sh post ...   Exit 1    

root@mastermailing:~# postal status
      Name                     Command               State    Ports
-------------------------------------------------------------------
postal_cron_1       /docker-entrypoint.sh post ...   Up            
postal_requeuer_1   /docker-entrypoint.sh post ...   Up            
postal_smtp_1       /docker-entrypoint.sh post ...   Up            
postal_web_1        /docker-entrypoint.sh post ...   Up            
postal_worker_1     /docker-entrypoint.sh post ...   Exit 1        

How can this be fixed

## Environment details 

 - Type [e.g. desktop, mobile etc...]

## Additional information/context

Add any other context about the problem here. It is particularily useful to include log extracts (after removing private information).

**Comment by uhlhosting** [comment]
check `postal logs worker`

**Comment by Bugspiderlee** [comment]
root@mastermailing:~# postal logs worker
Attaching to postal_worker_1
worker_1    | [9] [2023-01-22T13:18:41.293] INFO -- : Worker running with 4 threads
worker_1    | /usr/local/bundle/gems/bunny-2.14.4/lib/bunny/session.rb:1275:in `raise': Connection-level error: NOT_ALLOWED - vhost postal not found (Bunny::NotAllowedError)
worker_1    | 	from /usr/local/bundle/gems/bunny-2.14.4/lib/bunny/session.rb:1275:in `open_connection'
worker_1    | 	from /usr/local/bundle/gems/bunny-2.14.4/lib/bunny/session.rb:320:in `start'
worker_1    | 	from /opt/postal/app/lib/postal/rabbit_mq.rb:26:in `create_connection'
worker_1    | 	from /opt/postal/app/lib/postal/rabbit_mq.rb:31:in `create_channel'
worker_1    | 	from /opt/postal/app/lib/postal/worker.rb:195:in `job_channel'
worker_1    | 	from /opt/postal/app/lib/postal/worker.rb:17:in `work'
worker_1    | 	from script/worker.rb:3:in `<main>'
worker_1    | [9] [2023-01-22T13:27:49.600] INFO -- : Worker running with 4 threads
worker_1    | /usr/local/bundle/gems/bunny-2.14.4/lib/bunny/session.rb:1275:in `raise': Connection-level error: NOT_ALLOWED - vhost postal not found (Bunny::NotAllowedError)
worker_1    | 	from /usr/local/bundle/gems/bunny-2.14.4/lib/bunny/session.rb:1275:in `open_connection'
worker_1    | 	from /usr/local/bundle/gems/bunny-2.14.4/lib/bunny/session.rb:320:in `start'
worker_1    | 	from /opt/postal/app/lib/postal/rabbit_mq.rb:26:in `create_connection'
worker_1    | 	from /opt/postal/app/lib/postal/rabbit_mq.rb:31:in `create_channel'
worker_1    | 	from /opt/postal/app/lib/postal/worker.rb:195:in `job_channel'
worker_1    | 	from /opt/postal/app/lib/postal/worker.rb:17:in `work'
worker_1    | 	from script/worker.rb:3:in `<main>'
worker_1    | [8] [2023-01-22T14:26:30.745] INFO -- : Worker running with 4 threads
worker_1    | /usr/local/bundle/gems/bunny-2.14.4/lib/bunny/session.rb:1275:in `raise': Connection-level error: NOT_ALLOWED - access to vhost 'postal' refused for user 'postal' (Bunny::NotAllowedError)
worker_1    | 	from /usr/local/bundle/gems/bunny-2.14.4/lib/bunny/session.rb:1275:in `open_connection'
worker_1    | 	from /usr/local/bundle/gems/bunny-2.14.4/lib/bunny/session.rb:320:in `start'
worker_1    | 	from /opt/postal/app/lib/postal/rabbit_mq.rb:26:in `create_connection'
worker_1    | 	from /opt/postal/app/lib/postal/rabbit_mq.rb:31:in `create_channel'
worker_1    | 	from /opt/postal/app/lib/postal/worker.rb:195:in `job_channel'
worker_1    | 	from /opt/postal/app/lib/postal/worker.rb:17:in `work'
worker_1    | 	from script/worker.rb:3:in `<main>'
worker_1    | [9] [2023-01-22T21:39:22.011] INFO -- : Worker running with 4 threads
worker_1    | /usr/local/bundle/gems/bunny-2.14.4/lib/bunny/session.rb:1275:in `raise': Connection-level error: NOT_ALLOWED - access to vhost 'postal' refused for user 'postal' (Bunny::NotAllowedError)
worker_1    | 	from /usr/local/bundle/gems/bunny-2.14.4/lib/bunny/session.rb:1275:in `open_connection'
worker_1    | 	from /usr/local/bundle/gems/bunny-2.14.4/lib/bunny/session.rb:320:in `start'
worker_1    | 	from /opt/postal/app/lib/postal/rabbit_mq.rb:26:in `create_connection'
worker_1    | 	from /opt/postal/app/lib/postal/rabbit_mq.rb:31:in `create_channel'
worker_1    | 	from /opt/postal/app/lib/postal/worker.rb:195:in `job_channel'
worker_1    | 	from /opt/postal/app/lib/postal/worker.rb:17:in `work'
worker_1    | 	from script/worker.rb:3:in `<main>'
root@mastermailing:~#
