### ISSUE TITLE
"latest" package released by accident (it seems) causing problems

### ISSUE THREAD

**Issue by LeoColman** [postalserver/postal#2397]
Hi!

https://github.com/postalserver/postal/pkgs/container/postal

![image](https://user-images.githubusercontent.com/1577251/228661991-2ce272cb-7363-4bbf-8b90-3315115742fa.png)

I had Watchtower on and out of the blue my Postal stopped working. I discovered it's due to this new version, that doesn't seem purposefully published as it doesn't follow the same pattern

**Comment by willpower232** [comment]
that is a bit unfortunate but I think that seems to be what is intended in the workflow file.

are you able to specify versions in your docker configuration to avoid this?

**Comment by LeoColman** [comment]
Yes, that's the quickest way to fix the problem.

Was this latest package published previously? I thought only numbered versions were published and latest just meant the latest numbered version

Mar 30, 2023 11:17:36 Will Power ***@***.***>:

**Comment by adamcooke** [comment]
This isn't an accident. The latest tag has always followed the main branch of the repository. For stability, you should deploy a specific version. The latest released version is still 2.1.2 but there will be another soon. 

If something is broken for you following, albeit accidentally, upgrading to latest, please let us know so we can fix it.

**Comment by LeoColman** [comment]
> The latest tag has always followed the main branch of the repository.

Woow! Kudos for you guys! I've always left (recklessly, I admit now) the auto-update on and the master branch never gave me a single issue!

What was broken was that ruby wasn't finding a method, `tls_hostname`. I guess that it started on this commit https://github.com/postalserver/postal/commit/159509a3ed29ae33cba522b255904992922dcfdf#diff-9bca3a0aa946cb1f1d97f18ed7f1a6f472814de75eb39dcc3913d8c8e714645fR52 

Although I have absolutely no Ruby knowledge and this was just what I found exploring. Should I create a new issue? Or perhaps wait for an official release and see if the bug persists there?

**Comment by catphish** [comment]
> What was broken was that ruby wasn't finding a method, `tls_hostname`. I guess that it started on this commit [159509a#diff-9bca3a0aa946cb1f1d97f18ed7f1a6f472814de75eb39dcc3913d8c8e714645fR52](https://github.com/postalserver/postal/commit/159509a3ed29ae33cba522b255904992922dcfdf#diff-9bca3a0aa946cb1f1d97f18ed7f1a6f472814de75eb39dcc3913d8c8e714645fR52)

Yes, this is my fault. The `tls_hostname` method doesn't exist in Ruby 2.7.7 (the specified version for Postal). For some reason I tested this code on a later version of Ruby that does have this functionality. This deserves its own issue.

**Comment by catphish** [comment]
Postal is due to be upgraded to Ruby 3.1.2 very soon, so most likely this bug will be fixed by the Ruby upgrade, rather than by being reverted. Sorry for releasing this in the wrong order!
