### ISSUE TITLE
HP MFP Scan to mail issue

### ISSUE THREAD

**Issue by dinodipardo** [postalserver/postal#2404]
Hi, I upgraded postal to the latest version to see if the issue with HP printers is solved as logged here: https://github.com/postalserver/postal/issues/2005#issuecomment-1504957023_

Unfortunately HP MFP's I have tested are unable to mail through postal.

I did test the scan to mail function form three different HP printers sending e-mails directly to the following mail systems:

Google
Microsoft
Plesk - hosted
Telenet
MailHug (which I used to gather the log files)
I tested with and without authentication, with and without TLS. All of these services are accepting just fine the mails send by the three different HP MFP's.

The only SMTP server not accepting e-mails from those three different HP printers is postal :-(. So I really think there is an issue in the SMTP server part of postal. I tested postal with and without TLS configured.

It would be great if this can be solved as this is the last bit that doesn't work for us.

I've attached the log files as they contain strange/invalid characters coming from the HP MFP's.
[FAILURE_postal_smtp_server.log](https://github.com/postalserver/postal/files/11209796/FAILURE_postal_smtp_server.log)
[SUCCESS_mailhug.log](https://github.com/postalserver/postal/files/11209798/SUCCESS_mailhug.log)

**Comment by willpower232** [comment]
duplicate
