### ISSUE TITLE
tracking link was denied

### ISSUE THREAD

**Issue by oussamaelwarraki** [postalserver/postal#2439]
Access to click.luzinmedia.com was denied
You don't have authorization to view this page.
HTTP ERROR 403

this is my Caddyfile : 

`mail.luzinmedia.com {
  reverse_proxy 127.0.0.1:5000
}

click.luzinmedia.com {
  tls it@xxxxxxxx
  reverse_proxy 127.0.0.1:5000 {
    header_up X-Postal-Track-Host "1"
  }
}
`

_Originally posted by @oussamaelwarraki in https://github.com/postalserver/postal/discussions/2438_

**Comment by willpower232** [comment]
duplicate #2415
