### ISSUE TITLE
Click and Open Tracking Not Working

### ISSUE THREAD

**Issue by vulnfind** [postalserver/postal#2449]
### Discussed in https://github.com/postalserver/postal/discussions/2446

<div type='discussions-op-text'>

<sup>Originally posted by **vulnfind** May  4, 2023</sup>
My postal server is on "mail.example1.com" and I have added another domain inside the postal server "example2.com". I have created a subdomain "click.example2.com" and pointed its CNAME record to "mail.example1.com" and added the header in the Caddyfile as follows

```

# Update this to match the hostname you wish to use for accessing the
# Postal web interface.
mail.example1.com {
  reverse_proxy 127.0.0.1:5000
}

# If you use open/click tracking you may need to add additional hosts
# to this file using the format below.
#
click.example2.com {
  reverse_proxy 127.0.0.1:5000 {
    header_up X-Postal-Track-Host "1"
  }
}

```

What else should I do??</div>

**Comment by willpower232** [comment]
not duplicate discussions into issues
