### ISSUE TITLE
403 forbidden + caddy ssl not working

### ISSUE THREAD

**Issue by slezercc** [postalserver/postal#2459]
I finished setting up postal and:
1: I'm getting a 403 forbidden error on my mail subdomain
2: even after doing the caddy thing, theres no ssl on my mail subdomain

**Comment by ankitjaggi** [comment]
@slezercc Were you able to resolve this? I'm facing a similar issue.

**Comment by slezercc** [comment]
> @slezercc Were you able to resolve this? I'm facing a similar issue.

Im not sure but if I can recall properly all I did was start from scratch and it worked. Try removing absolutely everything from docker and starting again from the docs.

**Comment by ankitjaggi** [comment]
Yeah, something similar worked for me as well.
