### ISSUE TITLE
Mysql2::Error: Data too long for column 'output' at row 1

### ISSUE THREAD

**Issue by slezercc** [postalserver/postal#2460]
![image](https://github.com/postalserver/postal/assets/37955902/c0b14fca-3314-483a-bda6-d84f67969e1b)
![image](https://github.com/postalserver/postal/assets/37955902/4865379f-1eff-49a1-9e62-c8728149f559)

**Comment by jpcapone** [comment]
Are you able to access the logs?  It would be helpful to see the postal-smtp-1 logs:
`docker ps -a`
`docker logs CONTAINERID -f`
https://geekflare.com/check-docker-logs/

I use portainer and you can use the management features to view the logs easily:
![image](https://github.com/postalserver/postal/assets/47680328/ec0fefbc-ca7d-478c-a293-de6850c575d9)

**Comment by willpower232** [comment]
Do you have webhooks enabled? It might be that you have somehow eluded the 512 limit applied here https://github.com/postalserver/postal/blob/5222263484f2a5889653859db6aeb7438f116357/lib/postal/message_db/delivery.rb#L51

**Comment by catphish** [comment]
This should be easy to fix, but I'd like to confirm the affected version, and ideally see the backtrace.
