### ISSUE TITLE
Distortion of characters when viewing the original message

### ISSUE THREAD

**Issue by alglyzin** [postalserver/postal#2462]
After updating to the latest version 2.1.4, the html version incorrectly displays text other than English characters.
The email arrives in the correct encoding, but is viewed as in the screenshot:

![2023-05-15_10-43-13](https://github.com/postalserver/postal/assets/11249756/263cc518-595b-4a0b-9a01-20f90b6ff55f)

**Comment by usr-h** [comment]
I am also interested in what causes it and how it can be fixed...

**Comment by Paz08** [comment]
Has anyone taken a look at this? I'm also experiencing the same issue and the clients are not happy about it...

**Comment by JustinBack** [comment]
Same issue, this happens for incoming E-Mails as well, resulting in the webhooks breaking the encoding and passing the invalid characters.

Seems this line is responsible for handling the encoding, though I don't have a fix

https://github.com/postalserver/postal/blob/2f62baa238fc1102706ee4acf079b7a876b05283/config/initializers/mail_extensions.rb#L89-L105

**Comment by stereu** [comment]
#2596

**Comment by Paz08** [comment]
any news on this release?
