### ISSUE TITLE
Random internal server error

### ISSUE THREAD

**Issue by ivangdavila** [postalserver/postal#2471]
I am facing a strange behavior since I upgraded to version 2.1.4.
I use the API to send HTML generated with mjml library, which worked with previous versions. 

Now I receive a 500 error, and the docker logs of the postal_web_1 container print:

Read: #<ArgumentError: wrong number of arguments (given 1, expected 0)>

This happens randomly, I think it is related to URLs inside the HTML content because it works if I remove all of them, it never works if I add 10-20 URLS, and with 5 URLs it works randomly. For example, the same API call works 50% of the time and otherwise throws the error. And fails less for API calls separated by less than a second.

**Comment by willpower232** [comment]
Does it fail randomly if you give it the exact same 5 links over and over? Does it work consistently if you turn off click tracking?

**Comment by ivangdavila** [comment]
I have tried changing links and it is not related. Using the same links or using other links does not change anything. If I do five calls separated by 1/2 second, usually the first one throws the error and the following work. And if then I wait for 2-3 seconds, the postal throws the error again. 

I have tried using https+notrack for all the links and the problem persist, with no change in the behavior.

**Comment by willpower232** [comment]
If you temporarily remove the tracking domain so that click tracking is disabled, does it start working normally again?

It would be good to see the rest of the stack trace, not just the one error line.

**Comment by ivangdavila** [comment]
The problem persists even if I remove the tracking domain from the environment, and do "postal stop && postal start"

Which would be the best way to get the full stack trace? I have tried with "postal log" and docker logs in different containers and I cannot get more info.

**Comment by ivangdavila** [comment]
I have done some extra tests and it seems that the error still happen even when I send a simple one-sentence email body, with no links, images or html. 

The error still happens randomly, like 1 out of 5 times, sending the same payload to the postal API.

**Comment by willpower232** [comment]
The request should be going to the web container so you need to keep an eye on `postal logs web`. If you don't see anything in there, it might be worth keeping an eye on the nginx or caddy logs to confirm the request is always going to the right place.
