### ISSUE TITLE
html_raw missing meta utf-8

### ISSUE THREAD

**Issue by usr-h** [postalserver/postal#2494]
## Describe the bug
Postal version 2.1.2 exist meta declaration and not bad őúéáűí characters..
url: /org/xxx/servers/xxx/messages/15/html_raw
v. 2.1.2:
![image](https://github.com/postalserver/postal/assets/17280005/4105dc31-787b-4265-9b4a-8d965044466f)

v.2.1.4:
![image](https://github.com/postalserver/postal/assets/17280005/7fc9c234-f3c1-4d39-8e6c-b1e17daaa0bd)

Result after postal upgrade:
![image](https://github.com/postalserver/postal/assets/17280005/f79c7d11-6051-4d25-ae15-3c836a371241)

**Comment by usr-h** [comment]
temporary solution?

**Comment by dronerdk** [comment]
Same issue here. Please make a fix

**Comment by dronerdk** [comment]
We need feedback on this issue here!

**Comment by pendurov** [comment]
Same issue after upgrading to 2.1.4 from 2.1.1

**Comment by mihailbishkek** [comment]
![изображение](https://github.com/postalserver/postal/assets/18412931/2de2f3eb-b1b4-4727-a876-6c634f666f10)
Same issue after upgrading to 2.1.4!!!!

**Comment by Toni202012569** [comment]
Yes, I understand that the encoding display is incorrect. How can I fix this error?

**Comment by adamcooke** [comment]
Can't reproduce. Please re-open a new issue with full reproduction steps if this persists.

![Image](https://share.adam.ac/24/Screen-Shot-2024-02-01-13-38-56.83-vkoYYu6JFw.png)

**Comment by andrsharov** [comment]
After the update the bug was fixed . Thanks!
