### ISSUE TITLE
MessageBounced Webhook not sent

### ISSUE THREAD

**Issue by vkperumal** [postalserver/postal#2500]
## Describe the bug
Even though the message is categorized as bounce, webhook is not getting triggered

SPF, DKIM and Return path have been configured

Postal Version: 2.1.4

## Expected behaviour
Webhook should be triggered

## Screenshots
<img width="1172" alt="image" src="https://github.com/postalserver/postal/assets/35548944/1979e4d1-a014-4f17-a8f0-9b4a7a9ad44c">

Bounce Webhook Configuration
<img width="732" alt="image" src="https://github.com/postalserver/postal/assets/35548944/cd3a5690-3ddd-4a10-8df6-dff1c2adcbae">

Webhook History
<img width="750" alt="image" src="https://github.com/postalserver/postal/assets/35548944/88677915-597d-46a9-b68c-c8cc3fd5c30d">

**Comment by willpower232** [comment]
The code still seems present so I'm not sure what the problem could be.

https://github.com/postalserver/postal/blob/2f62baa238fc1102706ee4acf079b7a876b05283/lib/postal/message_db/message.rb#L439-L442

https://github.com/postalserver/postal/blob/2f62baa238fc1102706ee4acf079b7a876b05283/app/jobs/unqueue_message_job.rb#L90-L98

If you're able to trigger a bounce yourself, you could try watching the logs for the workers and see if they log anything relevant but that might be challenging depending on how busy they are.

**Comment by vkperumal** [comment]
I was able to solve the problem by adding below to config/application.rb file seeing from one of the issue.

# Allow more types to be serialized
    config.active_record.yaml_column_permitted_classes = [Symbol, Hash, Array, ActiveSupport::HashWithIndifferentAccess]

Then I was able to get Bounce Webhooks.

**Comment by ReptoxX** [comment]
This issue is still persisting and #2477 indeed fixes that.
Is this ever going to get merged?

**Comment by chrisdeeming** [comment]
Apologies for this. I am also encountering this issue.

Is anyone able to write an idiots guide (for me, an idiot) on how to patch this directly? Assume I know barely anything about Docker and even less about Ruby.

Particularly @vkperumal as it sounds like you may have done this before :) 

Much appreciated.
