### ISSUE TITLE
postal test-app-smtp example@email.com fails on ERROR

### ISSUE THREAD

**Issue by arthurzenika** [postalserver/postal#2514]
## Describe the bug

```shell
root@postal:~# postal test-app-smtp test-kq4onl1je@srv1.mail-tester.com
Creating postal_runner_run ... done
usage: postal test-app-smtp [email address]
ERROR: 1
```

## To Reproduce

1. SSH into the server
2. run postal test-app-smtp with an email address 
3. see the error above

## Expected behaviour

For the test email to be sent. 

Workaround using console and copying the ruby code from script : 

```ruby
root@postal-prod:/opt/postal# postal console
Creating postal_runner_run ... done
Loading production environment (Rails 5.2.6.2)
irb(main):002:0> AppMailer.test_message('test-kq4onl1je@srv1.mail-tester.com').deliver
  Rendering app_mailer/test_message.text.erb
  Rendered app_mailer/test_message.text.erb (0.4ms)
AppMailer#test_message: processed outbound mail in 7.0ms
[snip]
```

## Environment details 

 - OS: debian + docker-compose
 - Browser n/a
 - Version 2.1.2
 - Type n/a

**Comment by willpower232** [comment]
Ah yes that is unfortunate, @adamcooke doesn't there need to be some form of arg passing through occurring here https://github.com/postalserver/install/blob/ce3ddfa66e18a7509ebec9c7aebf84fcd70675df/bin/postal#L155-L157

**Comment by adamcooke** [comment]
Fixed in https://github.com/postalserver/install/commit/ec72fd9e4601c0b992bb9a393376eec12bb33a5e
