### ISSUE TITLE
cron timezone issue

### ISSUE THREAD

**Issue by rbustos** [postalserver/postal#2518]
## Describe the bug

Postal tries to perform sql queries looking for a table that should exists in the future according our timezone.

Following illustrate a MySQL log where it run a query for 2023-06-29 when according our timezone is 2023-06-28:

`**2023-06-28** 20:01:28 MySQL_Session.cpp:4450:handler_minus1_LogErrorDuringQuery(): [WARNING] Error during query on (10,10.69.170.2,3306,5049658) , user "postal_user@127.0.0.1" , schema "information_schema" , 1146, Table 'postal-server-109.raw-**2023-06-29**' doesn't exist . digest_text = "INSERT INTO postal-server-?.raw-?-?-? (`data`) VALUES (?)"`

Our timezone is UTC-4 as shown in the OS:

```
$ timedatectl
               Local time: Wed 2023-06-28 20:56:59 -04
           Universal time: Thu 2023-06-29 00:56:59 UTC
                 RTC time: Thu 2023-06-29 00:56:59
                Time zone: America/Santiago (-04, -0400)
System clock synchronized: no
              NTP service: inactive
          RTC in local TZ: no
```

Our Organization into Postal has the right Timezone (UTC -4).

The issue here is when it happens whole Postal simple hangs and we have to restart it. There are no other logs showing an error or so.

## Environment details 

 - OS: Rocky:  Linux release 8.8 (Green Obsidian)
 - Version:  2.1.2

**Comment by willpower232** [comment]
> Our Organization into Postal has the right Timezone (UTC -4)

I'm not actually sure that the organization timezone does anything.

It would be interesting to know what time the container thinks it is, I'm not sure if docker affects that in any way.

I'm not sure what exactly is going wrong, whether the table isn't being created around here

https://github.com/postalserver/postal/blob/2f62baa238fc1102706ee4acf079b7a876b05283/lib/postal/message_db/provisioner.rb#L97

or whether the insert command is misreading the date around here

https://github.com/postalserver/postal/blob/2f62baa238fc1102706ee4acf079b7a876b05283/lib/postal/message_db/database.rb#L110

or here

https://github.com/postalserver/postal/blob/2f62baa238fc1102706ee4acf079b7a876b05283/lib/postal/message_db/message.rb#L266-L267

Presumably that last one doesn't need to be set but I could easily be misinterpreting the code :sweat_smile:

**Comment by adamcooke** [comment]
The presence of that in the error log is to be expected. Postal will is designed to catch that error and create the table if it doesn't exist. 

```ruby
        begin
          headers, body = data.split(/\r?\n\r?\n/, 2)
          headers_id = insert(table_name, data: headers)
          body_id = insert(table_name, data: body)
        rescue Mysql2::Error => e
          raise unless e.message =~ /doesn't exist/

          provisioner.create_raw_table(table_name)
          retry
        end
```

Without any other information, I can't say or determine why the installation hangs of if/how this is related.
