### ISSUE TITLE
`postal initialize` is failing with the error docker-compose comand not found

### ISSUE THREAD

**Issue by jenishngl** [postalserver/postal#2522]
## `postal initialize` is failing with the error docker-compose comand not found

I was able to verify docker compose installed already in the instance with `docker compose version` comand. I got the below as output
`Docker Compose version v2.18.1`

## To Reproduce

1. Follow the steps as per the documentation [here](https://docs.postalserver.io/install/prerequisites)
2. In the installation step, run `postal initialize`

## Expected behaviour

postal should initialize

## Screenshots

<img width="435" alt="image" src="https://github.com/postalserver/postal/assets/9320926/ca843dd0-8d92-45a8-9d23-d736bb983c3d">

## Environment details 

 - Raspbian OS 64bit Lite running on Raspberry Pi 4 8GB

**Comment by jenishngl** [comment]
`sudo apt-get install libffi-dev libssl-dev python3-dev python3 python3-pip qemu-user-static -y`
This fixed the issue, but with docker-compose no longer available in latest docker packages, i think the init scipt still needs to be corrected

**Comment by willpower232** [comment]
See also https://github.com/postalserver/install/pull/8

**Comment by EdenKahane** [comment]
> `sudo apt-get install libffi-dev libssl-dev python3-dev python3 python3-pip qemu-user-static -y` This fixed the issue, but with docker-compose no longer available in latest docker packages, i think the init scipt still needs to be corrected

This does not solve the issue for me.
Is there any other solution than manually modifying the /bin/postal ?

**Comment by KalynDavis** [comment]
As per [Docker's docs](https://docs.docker.com/compose/install/standalone/)

`curl -SL https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose` to install it

and then `sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose` to create a symlink.

**Comment by stevebrainng** [comment]
I had the same error put in my case the command 
`apt-get install docker-compose-plugin
`
downloaded and installed docker-compose, python and other dependencies.

**Comment by ibousfiha** [comment]
Having the same issue here, this solved the issue: https://docs.docker.com/compose/install/linux/#install-the-plugin-manually

**Comment by marvinhinz** [comment]
Having the same problem on a fresh debian 12:

```
root@postal1:~# apt-get install docker-compose-plugin
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
docker-compose-plugin ist schon die neueste Version (2.20.2-1~debian.12~bookworm).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
root@postal1:~# docker compose version
Docker Compose version v2.20.2
```

```
root@postal1:~# postal initialize
/usr/bin/postal: Zeile 20: docker-compose: Kommando nicht gefunden.
```
I used this alias to get it working:
https://gist.github.com/tatosjb/c477a5c09c4ad8fa67265032831ac94f

**Comment by mredodos** [comment]
i have try to follow all your step but now i have /usr/bin/postal: line 20: /usr/local/bin/docker-compose: Permission denied

how can i solve?

**Comment by mredodos** [comment]
all this stuff is correct? 

```
 ✔ smtp Skipped - Image is already being pulled by web                                                         0.0s 
 ✔ worker Skipped - Image is already being pulled by web                                                       0.0s 
 ✔ cron Skipped - Image is already being pulled by web                                                         0.0s 
 ✔ requeuer Skipped - Image is already being pulled by web                                                     0.0s 
 ✔ web 22 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                              23.7s 
   ✔ 3e440a704568 Pull complete                                                                                5.3s 
   ✔ 68a71c865a2c Pull complete                                                                                5.5s 
   ✔ 670730c27c2e Pull complete                                                                                5.9s 
   ✔ 5a7a2c95f0f8 Pull complete                                                                                8.5s 
   ✔ 6d627e120214 Pull complete                                                                               15.9s 
   ✔ adce7d0cf0c9 Pull complete                                                                               16.1s 
   ✔ f83e8ed56f1d Pull complete                                                                               17.1s 
   ✔ f6a7165b526d Pull complete                                                                               17.1s 
   ✔ bcf3ffa6af9b Pull complete                                                                               17.6s 
   ✔ 70f9cc79c982 Pull complete                                                                               19.5s 
   ✔ 98bb5f89ed82 Pull complete                                                                               19.5s 
   ✔ ce687268e98d Pull complete                                                                               19.5s 
   ✔ 2242e59acc18 Pull complete                                                                               19.6s 
   ✔ 4f4fb700ef54 Pull complete                                                                               19.7s 
   ✔ f02853c610fa Pull complete                                                                               19.8s 
   ✔ 891c238e34bd Pull complete                                                                               19.8s 
   ✔ 77bfcbc71894 Pull complete                                                                               22.6s 
   ✔ 6b910f0264ec Pull complete                                                                               22.6s 
   ✔ 4c03b238bfa6 Pull complete                                                                               22.7s 
   ✔ 2ecd74400830 Pull complete                                                                               22.8s 
   ✔ fe76eae325c0 Pull complete                                                                               23.0s 
   ✔ 2171c03db388 Pull complete                                                                               23.0s 
Initializing database
Database 'postal' already exists
```

**Comment by simarmannsingh** [comment]
As @marvinhinz  mentioned, this worked for me too.
Thanks mate.

[https://gist.github.com/tatosjb/c477a5c09c4ad8fa67265032831ac94f](https://gist.github.com/tatosjb/c477a5c09c4ad8fa67265032831ac94f)
