### ISSUE TITLE
No incoming emails.

### ISSUE THREAD

**Issue by webmastermario** [postalserver/postal#2532]
Hello,

i have registered and installed postalserver but no incoming emails are delivered to my email test AT mediafile . link 
I have added all records for the domain and they are green but still not working. Also added routes with the email and as attached.
<img width="1440" alt="Bildschirmfoto 2023-07-07 um 21 02 08" src="https://github.com/postalserver/postal/assets/121729061/1428453a-c680-49eb-a6c6-7b178852ceb6">
What am i doing w
<img width="1440" alt="Bildschirmfoto 2023-07-07 um 21 02 15" src="https://github.com/postalserver/postal/assets/121729061/5b4ec9a6-8ecf-442c-9317-b6db48983eb8">
What am i doing wrong? Thanks for helping

**Comment by adamcooke** [comment]
This is not a bug with the software. Try using Discussions.
