### ISSUE TITLE
Unable to add multiple host names

### ISSUE THREAD

**Issue by aryansharma-incentius** [postalserver/postal#2548]
I have completed the postalserver setup on my server. (**Postal version 2.1.4**) It is working fine. Web interface is also live and emails are being sent. Now, I want to setup open & click tracking. For that, I referred to the official documentation and setup the tracking domain.

My postal web interface is running on **postal.mydomain.com**. My **web** block under postal.yml is as follows.

```
web:
  host: postal.mydomain.com
  protocol: https
```
In Caddyfile, I have following. Basically, I have setup postal web interface and tracking domain both.

```
postal.mydomain.com {
  reverse_proxy 127.0.0.1:5000
}
click.mydomain.com {
  reverse_proxy 127.0.0.1:5000 {
    header_up X-Postal-Track-Host "1"
  }
}
```
Now, since my web interface **postal.mydomain.com** is defined as **host** under **web** block in **postal.yml** file, it is working fine. But my tracking domain **click.mydomain.com** says **access denied** **HTTP 403**.

Just to troubleshoot, I have changed **host** in **web** block to **click.mydomain.com**, it worked fine and displayed **hello.** in the browser. So the main issue I am facing is that both postal web interface and tracking domains are not working in parallel.

Upon checking the log, it shows `[ActionDispatch::HostAuthorization::DefaultResponseApp] Blocked host: click.mydomain.com`

Is there any provision, to allow both postal web interface and tracking host in single postal config? I need to get both running at the same time in order to enable tracking and be able to see open, clicks in postal web interface.

Any help would be greatly appreciated. Thank you in advance!

**Comment by willpower232** [comment]
duplicate #2415

**Comment by aryansharma-incentius** [comment]
@willpower232  I have already followed the steps mentioned in #2415 but am unable to solve the issue.
I am using 2.1.4 version of Postal in which I am not able to resolve the above issue.
