### ISSUE TITLE
SMTP authentication with trusted IP address (without username and password)

### ISSUE THREAD

**Issue by webhostinggeek** [postalserver/postal#258]
So, we have some application that only allow SMTP IP to be set and we cannot specify username and password there. In postfix, there is an option to add our trusted IP's in mynetworks in main.cf file but I am not getting this option in Postal.

Can we achieve this?

**Comment by adamcooke** [comment]
That certainly seems like a reasonable request :)

**Comment by webhostinggeek** [comment]
So can we expect something in near future? :)

**Comment by scottcase** [comment]
+1 for this. Configserver CSF firewall is like this,  you can not set username / password only smtp IP

**Comment by adamcooke** [comment]
This was added.

**Comment by rccess** [comment]
@adamcooke 
is it possible to use SMTP-IP with credentials (That means that credentials works only when email receive on postal request from particular IP)

Thanks

**Comment by adamcooke** [comment]
No
