### ISSUE TITLE
Timed Out

### ISSUE THREAD

**Issue by hugoperes** [postalserver/postal#2632]
Hey guys!
Without changing anything on my postal server, I started getting a timeout error. Is this happening to you too?
I have already restarted the server's network service and the postal service. However, the problem persists.

**Connection to smtp.company.com.br:25 Timed Out Log data: ++ Starting Swift_SmtpTransport !! Connection to smtp.company.com.br:25 Timed Out (code: 0)
++ Starting Swift_SmtpTransport !! Connection to smtp.company.com.br:25 Timed Out (code: 0)**

**Comment by hugoperes** [comment]
Guys, problem solved. It was a problem with my hosting and not with the Postal Server.

**Comment by hugoperes** [comment]
Guys, I thought the problem was the hosting, but I was wrong.

The problem persists. Sometimes the post office is accepting shipping requests quickly, but after a few hours it starts to show a timeout for new shipping requests.

I'm using version 2.14 and I haven't changed anything in the postal server configuration. He started having this behavior in the middle of nowhere. Note: There are plenty of server resources. It's not a performance issue.

**Comment by hugoperes** [comment]
Na verdade, parece que é um problema do mesmo Servidor Postal. Depois de algum tempo com o servidor no ar, ele começa a apresentar atraso de conexão até chegar ao timeout. Consequentemente, as aplicações externas deixam de entregar os e-mails para o Servidor Postal. Esse problema só é resolvido quando reiniciamos o Servidor Postal. Depois de deixar o processo automatizado, eu fiz o seguinte:

1) Create the check-timeout.sh file and add the command: sudo swaks --server smtp.usender.com.br --to contato@autotic.com.br | grep -q '250 OK' || echo reboot

2) I created a cron to run this file every X time interval.

This way, the postal server's connection status will be checked every X amount of time and if this attempt does not return the value '250 OK' it means that SMTP is not working correctly and restart the server.

Note: It is also important to add the following cron to ensure the postal server starts up after the server restarts:

@reboot sudo postal start

**Comment by adamcooke** [comment]
This isn't something we have observed and I can't reproduce this. Without additional information we can't do much about this at the moment.
