### ISSUE TITLE
Upgrade install to use "docker compose" instead of deprecated "docker-compose"

### ISSUE THREAD

**Issue by bluepuma77** [postalserver/postal#2637]
## Describe the bug

Install script uses deprecated "docker-compose". Can't create a new setup.

## To Reproduce

```
root@postal:~# curl -fsSL https://get.docker.com -o get-docker.sh
root@postal:~# sudo sh get-docker.sh

root@postal:~# apt install git curl jq
root@postal:~# git clone https://postalserver.io/start/install /opt/postal/install
root@postal:~# sudo ln -s /opt/postal/install/bin/postal /usr/bin/postal
root@postal:~# postal bootstrap postal.yourdomain.com
Latest version is: 2.1.4
root@postal:~# postal initialize
/usr/bin/postal: line 20: docker-compose: command not found
```
## Expected behaviour

Command runs successfully

## Screenshots

n/a

## Environment details 

 - OS: Debian 11 (bullseye)
 - Docker CE 24.0.6

## Additional information/context

From the [Docker blog](https://www.docker.com/blog/new-docker-compose-v2-and-v1-deprecation/):
> Compose V1 support will no longer be provided after June 2023

I tried an alias workaround, but that didn't succeed
```
root@postal:~# alias docker-compose='docker compose'
root@postal:~# postal initialize
/usr/bin/postal: line 20: docker-compose: command not found
```

**Comment by willpower232** [comment]
duplicate, see also #2320 and #2522

**Comment by bluepuma77** [comment]
For those coming by through Internet search: 

As mentioned in #2522 here is a workaround: [gist](https://gist.github.com/tatosjb/c477a5c09c4ad8fa67265032831ac94f)
