### ISSUE TITLE
Pen Test - Second Order SQL Injection

### ISSUE THREAD

**Issue by hackeys** [postalserver/postal#2649]
Findings:
The application communicates with its database by sending a textual SQL query. The application creates the query by simply concatenating strings including data obtained from the database. Since that data may have been previously obtained from user input,and is neither checked for data type validity nor subsequently sanitized, the data could contain SQL commands that would be interpreted as such by the database.
Risk:
An attacker could directly access all of the system's data. The attacker would be able to steal any sensitive information stored by the system (such as personal user details or credit cards), and possibly change or erase existing data
Recommendations:
1.	Validate all data, regardless of source. Validation should be based on a whitelist: accept only data fitting a specified structure, rather than reject bad patterns. Check for:
•	Data type
•	Size
•	Range
•	Format
•	Expected values
2.	Instead of concatenating strings:
•	Use secure database components such as stored procedures, parameterized queries, and object bindings (for commands and parameters).
•	An even better solution is to use an ORM library, such as EntityFramework, Hibernate, or iBatis.
3.	Restrict access to database objects and functionality, according to the Principle of Least Privilege.

**Comment by catphish** [comment]
Please can you provide specific examples, or even better, patches?

**Comment by catphish** [comment]
Closing as these reports are not sufficiently specific.
