### ISSUE TITLE
Pen Test - Parameter Tampering

### ISSUE THREAD

**Issue by hackeys** [postalserver/postal#2650]
Findings:
The application provides user information without filtering by user ID. For example, it may provide information solely by a submitted account ID. The application concatenates the user input directly into the SQL query string, without any additional filtering.
The application also does not perform any validation on the input, nor constrain it to a pre-computed list of acceptable values.
Risk:
A malicious user could access other users’ information. By requesting information directly, such as by an account number,
authorization may be bypassed and the attacker could steal confidential or restricted information (for example, a bank account
balance), using a direct object reference
Recommendations:
Generic Guidance:
•	Enforce authorization checks before providing any access to sensitive data, including the specific object reference.
•	Explicitly block access to any unauthorized data, especially to other users’ data.
•	If possible, avoid allowing the user to request arbitrary data by simply sending a record ID. For example, instead of having the user send an account ID, the application should look up the account ID for the current authenticated user session.
Specific Mitigation:
•	Do not concatenate user input directly into SQL queries.
•	Include a user-specific identifier as a filter in the WHERE clause of the SQL query.
•	Map the user input to an indirect reference, e.g. via a prepared list of allowable values.

**Comment by catphish** [comment]
Closing as these reports are not sufficiently specific.
