### ISSUE TITLE
Pen Test - Improper Format Validation

### ISSUE THREAD

**Issue by hackeys** [postalserver/postal#2652]
Description Summary
The product uses a regular expression that does not sufficiently restrict the set of allowed values.
Extended Description
This effectively causes the regexp to accept substrings that match the pattern, which
produces a partial comparison to the target. In some cases, this can lead to other
weaknesses. Common errors include:
•	not identifying the beginning and end of the target string
•	using wildcards instead of acceptable character ranges
•	others
Time of Introduction
•	Implementation
Applicable Platforms
Languages
•	Perl
•	PHP

**Comment by catphish** [comment]
Closing as these reports are not sufficiently specific.
