### ISSUE TITLE
Security risk reporting - Email not found

### ISSUE THREAD

**Issue by hackeys** [postalserver/postal#2653]
I couldn't adhere to the policy when it comes to reporting security risks due to email not going forward .

How to reproduce 

Send a test email to security@postalserver.io

Error Message :
Delivery has failed to these recipients or groups:
[security@postalserver.io](mailto:security@postalserver.io)
The email address you entered couldn't be found. Please check the recipient's email address and try to resend the message. If the problem continues, please contact your email admin.
The following organization rejected your message: postalserver.io.

**Comment by adamcooke** [comment]
This is resolved.
