### ISSUE TITLE
Gmail 550 error resulting in "Hard Fail"

### ISSUE THREAD

**Issue by ravimantri** [postalserver/postal#266]
Dear Team / @adamcooke,

Thanks for the amazing application, which is interactive and easy to install. I just wanted to let you know I've just noticed that on Gmail Soft Bounces as following are showing as Hard Bounces in Postal:

550-5.7.1 [145.239.80.210 12] Our system has detected that this message is 550-5.7.1 likely unsolicited mail. To reduce the amount of spam sent to Gmail, 550-5.7.1 this message has been blocked. Please visit 550-5.7.1 https://support.google.com/mail/?p=UnsolicitedMessageError 550 5.7.1 for more information. w28si1688632wra.157 - gsmtp

Looking for your help. Thanks

**Comment by catphish** [comment]
Postal considers 550 errors to be hard failures. The specific error above is a permanent rejection of the message and it should be reflected in Postal as a hard failure. Can you confirm if this is what you are seeing? Your issue is ambiguous (title vs body text).

**Comment by ravimantri** [comment]
@catphish, Thanks for your reply. If I use PMTA I see this the same error as Soft Fail because it's due to reputation issue which is temporary and can be solved. In email industry usually hard bounces are something which are unsolvable like Email Doesn't Exist, Domain, etc.

**Comment by catphish** [comment]
You can of course solve your reputation issue then send the emails again. In my opinion it doesn't seem like a good idea (for improving reputation) to continue to automatically regularly retry emails that are being actively rejected as spam.

This is another thing that comes down purely to opinion, so the only solution that would work for everyone is to make a configurable list of SMTP status codes and how to act on them. More than that, 550 is a generic non-standard error, so it would be necessary to configure not only the code but the human readable message that goes with it, or even to configure this on a per-provider basis.

I will mark this as an enhancement, but I can't promise a complete configurable solution for this immediately.

**Comment by ravimantri** [comment]
@catphish, Thanks for your reply. Now I completely get your point and understood that with SOFT BOUNCE status Postal will retry to send again & again, which is of no use & not recommended.

My concern was only that I was connecting Postal with an EMA (Email Marketing Application) and due to that if EMA receives that the particular recipient is Hard Bounce EMA will mark that recipient as Blacklist, so that any user won't be able to send email to that recipient again.

I can understand that there is already lot of work going on and I really appreciate for making such product open-source & public.

Thanks

**Comment by saporus** [comment]
> You can of course solve your reputation issue then send the emails again. In my opinion it doesn't seem like a good idea (for improving reputation) to continue to automatically regularly retry emails that are being actively rejected as spam.
> 
> This is another thing that comes down purely to opinion, so the only solution that would work for everyone is to make a configurable list of SMTP status codes and how to act on them. More than that, 550 is a generic non-standard error, so it would be necessary to configure not only the code but the human readable message that goes with it, or even to configure this on a per-provider basis.
> 
> I will mark this as an enhancement, but I can't promise a complete configurable solution for this immediately.

@catphish ,

I trust you are doing great today. Please when will this enhancement be available. It is seriously needed.

Looking forward to read back from you.

Thanks
