### ISSUE TITLE
X-Postal-Tag is not extracted from messages that are held

### ISSUE THREAD

**Issue by washcroft** [postalserver/postal#2684]
If a message is being held, either due to a hold on the credential or the receipient is on the supressions list, the X-Postal-Tag header is not extracted because UnqueueMessageJob is exited before the relevant block of code is ran.

The following needs moving further up:

https://github.com/postalserver/postal/blob/2f62baa238fc1102706ee4acf079b7a876b05283/app/jobs/unqueue_message_job.rb#L315-L319

**Comment by willpower232** [comment]
I presume you're searching for the tag in the UI and it isn't working because the held messages aren't tagged so you can't find them amongst other held messages?

**Comment by washcroft** [comment]
That'd be a problem too, but in my case we use webhooks to report on email delivered by campaign (each campaign tagged with a unique tag) and this issue was preventing that reporting from being accurate.

**Comment by willpower232** [comment]
Ah yes good point, if you want to make a PR of it then you could also create your own docker image to resolve your workflow.
