### ISSUE TITLE
Webhook requests are not being pruned

### ISSUE THREAD

**Issue by olegbliaher** [postalserver/postal#2696]
## Describe the bug

Postal has a cron job that prunes old, unexecuted webhook requests, and uses the following line:

`@database.select(:webhook_requests, where: { timestamp: { less_than: 10.days.ago.to_f } }, order: "timestamp", direction: "desc", limit: 1, fields: ["id"])`

However, `webhook_requests` does not have a `timestamp` column. It does, however, have a `created_at` column. The payload has a timestamp key.-

## Environment details 

 - Version 2.1.4
 
## Other info

The following would probably work instead:

```ruby
last = WebhookRequest.where(created_at: ..10.days.ago).order(created_at: :desc).limit(1).pluck(:id).first
```

**Comment by willpower232** [comment]
I think you'll find there are multiple tables of webhook_requests, one variety is in the individual message databases and the other is in the main database.

Unfortunately they have different schemas so you're wrong in that the individual message databases version seems to be getting cleaned up.

But you're right in that nothing seems to be clearing out the one in the main database, I can see some really old entries in ours but I'm not sure why they are there at all and there are some very large gaps in the IDs so something is intermittently cleaning them up.

**Comment by olegbliaher** [comment]
@willpower232 ahh of course!

I think I'll add then some cron job of my own.
