### ISSUE TITLE
Incorrect domain addition rp.postal.example.com

### ISSUE THREAD

**Issue by LuD1161** [postalserver/postal#2708]
## Describe the bug

When adding a new domain, the instructions give wrong DNS entries to put. Instead of `rp.postal.mydomain.tld` it shows `rp.postal.example.com`. Also when verifying this verifies it incorrectly. Please check the screenshot attached.

## To Reproduce

1. Go to 'domains'
2. Add a new domain
3. Do the 'DNS setup'
4. You'll see the incorrect instructions.

## Expected behaviour

It should point to `rp.postal.mydomain.tld`

## Screenshots

<img width="574" alt="image" src="https://github.com/postalserver/postal/assets/17861054/f99815df-0e75-4d62-8b45-2e431e5fc9d1">

## Environment details 

 - OS: Ubuntu 22.04 LTS
 - Version - `postal 2.1.4`

**Comment by willpower232** [comment]
I presume you realised you just needed to restart Postal once you finish setting up the config file :sweat_smile:
