### ISSUE TITLE
Update quickstart script to use docker compose v2

### ISSUE THREAD

**Issue by majudev** [postalserver/postal#2742]
## Describe the bug

Docker Compose v1 (`docker-compose`) has now been deprecated for a while, yet it is still used by `bin/postal` helper script from https://github.com/postalserver/install repo (referenced by official manual). Manual nowhere mentions you need to have v1 specifically, and if you do fresh installation of Docker you will get v2 installed (`docker compose`) instead of v1.

## Possible fix

Just replace line 20 in `bin/postal` in repo https://github.com/postalserver/install from:
```bash
    eval "docker-compose -p postal $@"
```
to
```bash
    eval "docker compose -p postal $@"
```

Whole function view:
```bash
run-docker-compose() {
    if [ ! -f "docker-compose.yml" ]; then
        echo 'No docker-compose file available. Generating using latest available version...'
        latest_version=`get-latest-postal-version`
        echo "Latest verison is $latest_version"
        set-postal-version $latest_version
    fi

    eval "docker-compose -p postal $@"
}
```
to:
```bash
run-docker-compose() {
    if [ ! -f "docker-compose.yml" ]; then
        echo 'No docker-compose file available. Generating using latest available version...'
        latest_version=`get-latest-postal-version`
        echo "Latest verison is $latest_version"
        set-postal-version $latest_version
    fi

    eval "docker compose -p postal $@"
}
```

**Comment by willpower232** [comment]
duplicate https://github.com/postalserver/install/pull/8
