### ISSUE TITLE
Issue for non-admin users to change their email address

### ISSUE THREAD

**Issue by olegbliaher** [postalserver/postal#2748]
## Describe the bug

When a non-admin user changes their email, the settings page gets "stuck". The email address modification works as it should, but the screen doesn't refresh.

Following error is being generated in the logs:

```
[10028] [2024-01-12T10:42:13.410] INFO -- : Completed 500 Internal Server Error in 248ms (ActiveRecord: 7.0ms | Allocations: 1888)
[10028] [2024-01-12T10:42:13.414] FATAL -- :
NoMethodError (undefined method `verify_path' for #<UserController:0x000000000162d8>):

app/controllers/user_controller.rb:72:in `update'
lib/postal/tracking_middleware.rb:12:in `call'
```

Indeed, `verify_path` doesn't seem to be defined anywhere in the code.

## To Reproduce

1. Login as non-admin
2. Go to My Settings
3. Enter your password, and replace the email address.

## Expected behaviour

An email verifying the new email address should be sent I guess? Or at least a refreshed screen.

## Environment details 

version 2.1.4

**Comment by adamcooke** [comment]
This will be resolved in Postal 3.0.0.
