### ISSUE TITLE
Can't access Credentials-Webinterface after upgrade

### ISSUE THREAD

**Issue by david-brombacher** [postalserver/postal#2763]
Hello,

i have upgraded postal from 1.x to 2.1.4 via new installation on new server and restore of sql dump. It works, but i cant access any credentials in the webinterface of any mailserver:

![Screenshot 2024-01-25 030211](https://github.com/postalserver/postal/assets/70525131/16528e81-0207-4111-a1e6-075a80ea4756)

It says "We're sorry, but something went wrong"

Reboot or restarting postal is not solving the issue. Can anyone help me out or point me in the right direction?

Thank you

**Comment by Pacerino** [comment]
Could you attach some Logs please?
Also did you followed https://docs.postalserver.io/install/upgrade-to-v2 ?

**Comment by david-brombacher** [comment]
I found some log entries, related to this issue by using this command:

`docker logs postal_web_1`

Log:
![image](https://github.com/postalserver/postal/assets/70525131/c32cd582-7975-4d69-88ef-d342ed3dc8b2)

This shows in the sql database "postal", table "credentials":
![image](https://github.com/postalserver/postal/assets/70525131/0a154abe-028b-416e-a9bd-1a212bf220b0)

This is the table description:
![image](https://github.com/postalserver/postal/assets/70525131/0824c516-fc75-405d-b217-e756cb23c35b)

I cant see any error in the database. I searched the web for "uuid" - does postal use uuidtools?

https://geekhmer.github.io/blog/2014/12/06/using-uuid-as-primary-key-in-ruby-on-rails-with-mysql-guide/

**Comment by Pacerino** [comment]
From your table description I'm missing the `uuid` field. Take a look into the schema from postal for v2.
https://github.com/postalserver/postal/blob/main/db/schema.rb#L60

Added with https://github.com/postalserver/postal/blob/main/db/migrate/20200717083943_add_uuid_to_credentials.rb

**Comment by david-brombacher** [comment]
Thank you very much for pointing that out.
 It is not mentioned in the documentation (Section "Installing on a new server with existing data"), that after restoring the databases, its necessary to perform a database migration.

I solved the issue by executing:

`docker exec -it postal_web_1 bash`
`bin/rails db:migrate`

**Comment by willpower232** [comment]
If you'd like to open a PR in the [docs repo](https://github.com/postalserver/docs) to add the missing text then that would be appreciated
