### ISSUE TITLE
strip_received_headers may be problematic

### ISSUE THREAD

**Issue by chrisdeeming** [postalserver/postal#2781]
I have recently been having my server IPs added to the Spamhaus CSS list. Usually not an issue, and usually removed fairly quickly.

Today the automatic delisting failed (probably because I had requested too many delistings) and in their ticket response to me:

> From Jan 27th they stopped having "Received" headers, making them indistinguishable from spamware.

Now, to me, this doesn't sound right. A `received` header does usually contain the IP address of the sender but surely its presence or absence doesn't inherently indicate spam behaviour.

If I was spamming, surely I could spoof an IP address in the received header.

It doesn't really add up. Especially as, when I was using postfix, I would modify the headers to exclude the IP address anyway.

All things considered, I'm not sure how problematic the current approach is, but I don't want IP addresses being leaked via outgoing emails. My only option currently is `strip_received_headers` but if the absence of the header is going to be a spam signal then that isn't a viable solution either.

What would be great and give us the maximum flexibility is if we could modify the default content of the header. I guess it could be defined in the YAML file:

```yaml
received_header_format: "from {{helo_name}} ({{hostname}} [{{ip_address}}]) by {{dns_name}} with SMTP; {{time_now}}"
```

When the header is being generated, it'd just render the string and replace those placeholders.

I would then simply update my config file with:

```yaml
received_header_format: "from {{helo_name}} ({{hostname}} by {{dns_name}} with SMTP; {{time_now}}"
```

I'm a developer but I don't know the first thing about Ruby otherwise I would take this on myself, but I would imagine that someone experienced would be able to knock this up in a very short amount of time.

Any thoughts here from Postal veterans or maintainers?

**Comment by adamcooke** [comment]
I'm not sure that I want to add the option to format the received header at the moment but I do think adding a 'privacy mode' option would be useful that would allow for IPs/hostnames to be excluded from the received header of the client that sends mail to Postal. Rather than being in the config file, this would be configurable per server through the web UI.

Would that suitable for your use?

**Comment by chrisdeeming** [comment]
Hi @adamcooke yes that would be perfect. I've patched the code myself today to remove the IP but if I didn't have to do that then that's even better

**Comment by amplitudesxd** [comment]
> I'm not sure that I want to add the option to format the received header at the moment but I do think adding a 'privacy mode' option would be useful that would allow for IPs/hostnames to be excluded from the received header of the client that sends mail to Postal. Rather than being in the config file, this would be configurable per server through the web UI.
> 
> Would that suitable for your use?
> 
> This would also allow us to remove the `strip_received_header` config option which was only partially implemented and shouldn't have been at the config file level. It should have been configuration that applied on a per-server basis.

This would be perfect for my use case as well, I hope this can be implemented.

**Comment by adamcooke** [comment]
Privacy mode has now been merged and will be in the next release.
