### ISSUE TITLE
strip_received_headers sends headers when using API

### ISSUE THREAD

**Issue by amplitudesxd** [postalserver/postal#2785]
## Describe the bug

When using the Postal HTTP API with strip_received_headers set to true, Postal doesn't strip the received headers from the email.

## Expected behaviour

I expect Postal to strip the headers.

## Additional information/context

I'd be happy to open a PR to fix this, the issue lies in the outgoing_message_prototype having different behaviour from the SMTP server client:
https://github.com/postalserver/postal/blob/main/lib/postal/smtp_server/client.rb#L381 (strips header)
https://github.com/postalserver/postal/blob/main/app/models/outgoing_message_prototype.rb#L178 (does not strip header)

**Comment by willpower232** [comment]
Have you seen #2781 ?

**Comment by amplitudesxd** [comment]
@willpower232 I believe it's different, that issue seems to be about customizing the value of the header - whereas this issue relates to the HTTP API not having the header stripped, when the config value to strip the received header is enabled.

**Comment by adamcooke** [comment]
It does appear that this feature was only partially implemented and did not include the API, just the SMTP server.

However, I am planning to remove it entirely in favour of a new 'privacy mode' which I have just described in #2781. Therefore, I'm not going to fix this.
