### ISSUE TITLE
Sometimes postal sent email to A record insted of MX

### ISSUE THREAD

**Issue by aledavidgueva** [postalserver/postal#2833]
## Describe the bug

Sometimes postal sent email to A record insted of MX. This behavior is random.

For example:

To: moranieva@sanvicenteescobar.edu.ar
Error Permanent SMTP delivery error when sending to sanvicenteescobar.edu.ar (44.198.246.147). The IP isn't the mail server, is the IP of domain.
![image](https://github.com/postalserver/postal/assets/88793488/21d3ef26-5945-41e2-9d40-baf1b08485d1)

The MX records are:
![image](https://github.com/postalserver/postal/assets/88793488/4e013a81-c367-4d0a-b426-4169164c2d6d)

Then, if i try redeliver manually, works
![image](https://github.com/postalserver/postal/assets/88793488/7aa1c7fd-1b61-474e-abbc-b804f234ba9a)

## Expected behaviour
If DNS query fail for MX records, mark as soft fail and retry later.

## Environment details 

 - OS: Debian
 - Postal version: 2.3.0

**Comment by adamcooke** [comment]
Thanks for the bug report. I can see how this might happen if looking up the MX records is slower than the configured DNS timeout. When it times out, we assume there are no MX records and move on to looking up based on the A record instead.

I will have a think about how this can be resolved.
