### ISSUE TITLE
Unable to receive incoming email after upgrade to V3

### ISSUE THREAD

**Issue by LotisHunters** [postalserver/postal#2845]
## Describe the bug
I'm able to send emails after the upgrade, but I haven't been able to receive any emails that I've sent to the server.
I checked all the logs and this is the only thing I found

worker_1  | Loading config from /config/postal.yml
worker_1  | WARNING: Using legacy config file format. Upgrade your postal.yml to use
worker_1  | version 2 of the Postal configuration or configure using environment
worker_1  | variables. See https://postalserver.io/config-v2 for details.

Going to https://postalserver.io/config-v2 results in a 404

I can provide any other details needed

**Comment by adamcooke** [comment]
I will need more information. The URL does need fixing but isn't the cause of your issues.

Check the logs for the SMTP server with "postal logs smtp"?

**Comment by LotisHunters** [comment]
This is everything from that

postal logs smtp
Attaching to postal_smtp_1
smtp_1    | Loading config from /config/postal.yml
smtp_1    | WARNING: Using legacy config file format. Upgrade your postal.yml to use
smtp_1    | version 2 of the Postal configuration or configure using environment
smtp_1    | variables. See https://postalserver.io/config-v2 for details.
smtp_1    | 2024-03-05 18:49:34 +0000 INFO   Listening on 127.0.0.1:25 component=smtp-server
smtp_1    | 2024-03-05 18:49:34 +0000 INFO   started health server on port 9091 component=health-server

**Comment by adamcooke** [comment]
There's nothing useful to go on there I'm afraid. Are you sure that your old installation has all stopped running?

**Comment by LotisHunters** [comment]
3/5/2024 1:17:14 PM Connection attempt #1 - Unable to connect after 15 seconds. [15.05 sec]

Ran an nmap scan of one of my IPs.
25/tcp  closed smtp
80/tcp  open   http
443/tcp open   https

Looks like port 25 isn't open or able to be connected to. I didn't make any changes to my firewall and my other Postal servers that I didn't upgrade can still receive just fine.

The old install looks stopped and gone.
![image](https://github.com/postalserver/postal/assets/47806082/a74e9507-f3d4-4bc8-8249-0f16bcd9a9f1)

Tried restarting the server and postal several times just in case. I'll keep digging. Let me know if you can think of anything else to try.

**Comment by LotisHunters** [comment]
Woke up instantly after adding that. Receiving works. Thanks!

**Comment by adamcooke** [comment]
I will be changing the default bind address to this for everyone using the legacy config files. This was an oversight on my part and will be resolved in 3.0.2.

**Comment by LotisHunters** [comment]
No worries at all. I was testing it out on a secondary server to make sure the upgrade to V3 works smoothly.

Thank you for all the work you've been putting into Postal. We rely on it a lot and it has been very exciting to see all the upgrades. Looking forward to seeing all the new developments coming with V3.
