### ISSUE TITLE
Documentation is missing how to upgrade docker containers from version 2.x.x to V3

### ISSUE THREAD

**Issue by LeoColman** [postalserver/postal#2846]
https://docs.postalserver.io/getting-started/upgrade-to-v3
https://docs.postalserver.io/getting-started/upgrading

No mentions are made to the docker image

https://docs.postalserver.io/other/containers is not migrated to the new version either

**Comment by adamcooke** [comment]
What references do you want to see on those pages about the image? 

I will update the containers page on the docs shortly though.

**Comment by adamcooke** [comment]
I have now updated the containers page of the docs to reflect what is needed for v3.
