### ISSUE TITLE
Unable to get incoming mails - Broken pipe smtp-server

### ISSUE THREAD

**Issue by RahulVerma989** [postalserver/postal#2862]
### Discussed in https://github.com/orgs/postalserver/discussions/2861

<div type='discussions-op-text'>

<sup>Originally posted by **RahulVerma989** March  9, 2024</sup>
Hi there,

I am able to receive emails using the **Simulate an incoming e-mail** option but not able to receive when sending through gmail.

After executing postal logs smtp I am getting these logs.

<img width="1288" alt="Screenshot 2024-03-09 at 3 17 50 PM" src="https://github.com/postalserver/postal/assets/48805821/687b5e1b-b4dd-4be4-92e4-5c6aa576aa5e">

My domain is also setup correctly.

<img width="1193" alt="Screenshot 2024-03-09 at 3 20 48 PM" src="https://github.com/postalserver/postal/assets/48805821/fbd29146-3bfc-4570-a2a8-8154778ab01e">

How should I solve this issue?
</div>

**Comment by adamcooke** [comment]
This sounds like an installation issue. Please continue in your discussion and add an issue following the issue template if you can actually identify an issue with Postal.
