### ISSUE TITLE
Webhook error / Mysql2::Error (Data too long for column 'body' at row 1)

### ISSUE THREAD

**Issue by sitnikov** [postalserver/postal#2863]
worker-1  | 2024-03-09 11:21:29 +0000 ERROR  Mysql2::Error (Data too long for column 'body' at row 1) component=worker thread=work1
worker-1  | 2024-03-09 11:21:29 +0000 ERROR  /usr/local/bundle/gems/mysql2-0.5.6/lib/mysql2/client.rb:151:in `_query' component=worker thread=work1
worker-1  | 2024-03-09 11:21:29 +0000 ERROR  /usr/local/bundle/gems/mysql2-0.5.6/lib/mysql2/client.rb:151:in `block in query' component=worker thread=work1
worker-1  | 2024-03-09 11:21:29 +0000 ERROR  /usr/local/bundle/gems/mysql2-0.5.6/lib/mysql2/client.rb:150:in `handle_interrupt' component=worker thread=work1
worker-1  | 2024-03-09 11:21:29 +0000 ERROR  /usr/local/bundle/gems/mysql2-0.5.6/lib/mysql2/client.rb:150:in `query' component=worker thread=work1
worker-1  | 2024-03-09 11:21:29 +0000 ERROR  /opt/postal/app/lib/postal/message_db/database.rb:326:in `query_on_connection' component=worker thread=work1
worker-1  | 2024-03-09 11:21:29 +0000 ERROR  /opt/postal/app/lib/postal/message_db/database.rb:234:in `block in insert' component=worker thread=work1
worker-1  | 2024-03-09 11:21:29 +0000 ERROR  /opt/postal/app/lib/postal/message_db/connection_pool.rb:20:in `use' component=worker thread=work1
worker-1  | 2024-03-09 11:21:29 +0000 ERROR  /opt/postal/app/lib/postal/message_db/database.rb:345:in `with_mysql' component=worker thread=work1
worker-1  | 2024-03-09 11:21:29 +0000 ERROR  /opt/postal/app/lib/postal/message_db/database.rb:233:in `insert' component=worker thread=work1
worker-1  | 2024-03-09 11:21:29 +0000 ERROR  /opt/postal/app/lib/postal/message_db/webhooks.rb:12:in `record' component=worker thread=work1
worker-1  | 2024-03-09 11:21:29 +0000 ERROR  /opt/postal/app/app/services/webhook_delivery_service.rb:54:in `record_attempt' component=worker thread=work1
worker-1  | 2024-03-09 11:21:29 +0000 ERROR  /opt/postal/app/app/services/webhook_delivery_service.rb:15:in `block in call' component=worker thread=work1
worker-1  | 2024-03-09 11:21:29 +0000 ERROR  /usr/local/bundle/gems/klogger-logger-1.4.0/lib/klogger/group_set.rb:18:in `call_without_id' component=worker thread=work1
worker-1  | 2024-03-09 11:21:29 +0000 ERROR  /usr/local/bundle/gems/klogger-logger-1.4.0/lib/klogger/logger.rb:72:in `tagged' component=worker thread=work1
worker-1  | 2024-03-09 11:21:29 +0000 ERROR  /opt/postal/app/app/services/webhook_delivery_service.rb:12:in `call' component=worker thread=work1
worker-1  | 2024-03-09 11:21:29 +0000 ERROR  /opt/postal/app/app/lib/worker/jobs/process_webhook_requests_job.rb:43:in `block in process_requests' component=worker thread=work1
worker-1  | 2024-03-09 11:21:29 +0000 ERROR  /usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/relation/delegation.rb:88:in `each' component=worker thread=work1
worker-1  | 2024-03-09 11:21:29 +0000 ERROR  /usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/relation/delegation.rb:88:in `each' component=worker thread=work1
worker-1  | 2024-03-09 11:21:29 +0000 ERROR  /opt/postal/app/app/lib/worker/jobs/process_webhook_requests_job.rb:40:in `process_requests' component=worker thread=work1
worker-1  | 2024-03-09 11:21:29 +0000 ERROR  /opt/postal/app/app/lib/worker/jobs/process_webhook_requests_job.rb:13:in `call' component=worker thread=work1
worker-1  | 2024-03-09 11:21:29 +0000 ERROR  /opt/postal/app/app/lib/worker/process.rb:143:in `block (4 levels) in work' component=worker thread=work1
worker-1  | 2024-03-09 11:21:29 +0000 ERROR  /usr/local/lib/ruby/3.2.0/benchmark.rb:311:in `realtime' component=worker thread=work1
worker-1  | 2024-03-09 11:21:29 +0000 ERROR  /opt/postal/app/app/lib/worker/process.rb:143:in `block (3 levels) in work' component=worker thread=work1
worker-1  | 2024-03-09 11:21:29 +0000 ERROR  /opt/postal/app/app/lib/worker/process.rb:264:in `capture_errors' component=worker thread=work1
worker-1  | 2024-03-09 11:21:29 +0000 ERROR  /opt/postal/app/app/lib/worker/process.rb:140:in `block (2 levels) in work' component=worker thread=work1
worker-1  | 2024-03-09 11:21:29 +0000 ERROR  /opt/postal/app/app/lib/worker/process.rb:139:in `each' component=worker thread=work1
worker-1  | 2024-03-09 11:21:29 +0000 ERROR  /opt/postal/app/app/lib/worker/process.rb:139:in `block in work' component=worker thread=work1
worker-1  | 2024-03-09 11:21:29 +0000 ERROR  /usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `with_connection' component=worker thread=work1
worker-1  | 2024-03-09 11:21:29 +0000 ERROR  /opt/postal/app/app/lib/worker/process.rb:138:in `work' component=worker thread=work1
worker-1  | 2024-03-09 11:21:29 +0000 ERROR  /opt/postal/app/app/lib/worker/process.rb:121:in `block (3 levels) in start_work_thread' component=worker thread=work1
worker-1  | 2024-03-09 11:21:29 +0000 ERROR  /opt/postal/app/app/lib/worker/process.rb:120:in `loop' component=worker thread=work1
worker-1  | 2024-03-09 11:21:29 +0000 ERROR  /opt/postal/app/app/lib/worker/process.rb:120:in `block (2 levels) in start_work_thread' component=worker thread=work1
worker-1  | 2024-03-09 11:21:29 +0000 ERROR  /usr/local/bundle/gems/klogger-logger-1.4.0/lib/klogger/group_set.rb:18:in `call_without_id' component=worker thread=work1
worker-1  | 2024-03-09 11:21:29 +0000 ERROR  /usr/local/bundle/gems/klogger-logger-1.4.0/lib/klogger/logger.rb:72:in `tagged' component=worker thread=work1
worker-1  | 2024-03-09 11:21:29 +0000 ERROR  /opt/postal/app/app/lib/worker/process.rb:118:in `block in start_work_thread' component=worker thread=work1

**Comment by adamcooke** [comment]
Please resubmit following the bug issue template including all the required information. This is one of the laziest bug reports I've seen.
