### ISSUE TITLE
Problems accessing specific routes

### ISSUE THREAD

**Issue by EvvySiur** [postalserver/postal#2868]
I upgraded to v3.1.1 a few days ago in my v2 stable environment ,this all works fine, the mail server is still running stably, but I've encountered a few minor problems, I'm not sure if it's due to the upgrade or some bugs, when accessing 'View message queue' and 'queue', a routing error occurs
https://x x x x/org/xxxx/servers/xxx/queue 
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.
I'm not sure what the problem is, I see some related errors in the docker logs!

exception_class=ActionView::Template::Error exception_message=No message found matching provided query {:id=>23430} exception_backtrace=/opt/postal/app/lib/postal/message_db/message.rb:12:in `find_one'\n/opt/postal/app/lib/postal/message_db/database.rb:47:in `message'\n/opt/postal/app/app/models/concerns/has_message.rb:10:in `message'\n/opt/postal/app/app/views/messages/_list.html.haml:4:in `block in _app_views_messages__list_html_haml___475291026477001434_58100'

**Comment by adamcooke** [comment]
This usually means that a message exists in your `queued_messages` table is locked but not being processed and has now had its actual message data removed.

See #2869 which will resolve this.
