### ISSUE TITLE
Postal web interface sends emails to the wrong SMTP port

### ISSUE THREAD

**Issue by goldmont** [postalserver/postal#2885]
## Describe the bug

Postal forces port 25 when sending emails from its web interface to itself but SMTP is running on port 2525. Is there a way to set a custom port for the web interface? Postal works perfectly when sending to port 2525 from other services.

I get the error:
`No SMTP servers were available for mail.example.com. Invalid argument - connect(2) for "<ip_address>" port 25, execution expired`

## Expected behaviour

Being able to send emails to port 2525 via Postal web interface.

## Screenshots

Outgoing messages:
![Screenshot from 2024-03-16 10-07-34](https://github.com/postalserver/postal/assets/6855692/8069e9c4-b61e-420a-b1c0-0d4f25299f29)

SMTP endpoints:
![Screenshot from 2024-03-16 10-02-19](https://github.com/postalserver/postal/assets/6855692/2992debb-db64-4f24-9078-f7e60decabbb)

Routes:
![Screenshot from 2024-03-16 10-03-48](https://github.com/postalserver/postal/assets/6855692/1ca1757b-5f76-4e62-9e23-ae999c4b9e2b)

## Environment details 

 - OS: Debian 12
 - Browser: Chrome
 - Version: Postal 3.2.2

**Comment by adamcooke** [comment]
When you say "Is there a way to set a custom port for the web interface?" what do you mean? What e-mails are you talking about?

**Comment by goldmont** [comment]
> When you say "Is there a way to set a custom port for the web interface?" what do you mean? What e-mails are you talking about?

I mean that Postal keeps sending emails to port 25 but my SMTP is running on port 2525. When I send an email via the `Send message` form (see the screenshot), Postal fails to deliver the message because it's trying to send it to port 25.

![Screenshot from 2024-03-16 10-29-33](https://github.com/postalserver/postal/assets/6855692/d140d17b-dfde-4178-8664-fbd4d2cf07d3)

**Comment by goldmont** [comment]
Of course `example.com` is not my real domain.

**Comment by adamcooke** [comment]
I see now. 

No, that's not possible. If you want to receive incoming email to your Postal install from other mail servers (and Postal itself) you will need to listen on port 25. 

Postal does not treat outgoing mail any differently whether it's going to itself or any other external al server.

**Comment by goldmont** [comment]
> I see now.
> 
> No, that's not possible. If you want to receive incoming email to your Postal install from other mail servers (and Postal itself) you will need to listen on port 25.
> 
> Postal does not treat outgoing mail any differently whether it's going to itself or any other external server.

So can you please explain my what is the purpose of letting the user to set a custom port while creating a new SMTP endpoint? There's something I don't understand or missing in the documentation.

**Comment by adamcooke** [comment]
SMTP endpoints are used to route incoming mail to other servers. For example, you can setup specific addresses to go to other servers.

**Comment by goldmont** [comment]
To anyone else having the same issue, you can open port 25 on your firewall and redirect all the traffic to another port on the same host. For example, I had to redirect all the traffic from port 25 to 2525.

Message sent successfully:
![Screenshot from 2024-03-16 10-55-55](https://github.com/postalserver/postal/assets/6855692/7b94a438-07a4-407d-bbfe-9db66c0bb40e)

**Comment by willpower232** [comment]
For future people coming here, I just wanted to add that there is a massive difference between using Postal to send emails via SMTP or API and using the incoming routing.

If you wanted to use the incoming routing, you would have to have a domain with its MX records pointing at Postal and then probably use something else to send the message to that domain (I'm not sure if Postal would be able to SMTP to itself).

Using Postal directly to send messages via SMTP or API will always use the standard port.
