### ISSUE TITLE
Greylog, support TCP

### ISSUE THREAD

**Issue by derfabianpeter** [postalserver/postal#289]
Hi,

reviewing the default postal.yml, I found config-options for greylog (I assume you mean grAylog? Would it be possible to add an option to submit via TCP instead of the default UDP? Makes it easier to target GELF-Inputs behind certain loadbalancers that aren't capable of loadbalancing UDP traffic.

Ref: https://github.com/graylog-labs/gelf-rb

`n = GELF::Notifier.new("127.0.0.1", 12201, "LAN", { :protocol => GELF::Protocol::TCP })`

**Comment by catphish** [comment]
We should be able to add this as a config option. Labelled as enhancement, should be an easy one. "grey" is the usual spelling of "gray" over here, so we often end up spelling graylog wrong :slightly_smiling_face:
