### ISSUE TITLE
postal status not showing the ports

### ISSUE THREAD

**Issue by 9x3l6** [postalserver/postal#2898]
## Describe the bug

When I run the command `postal status` the output doesn't show the ports that the services are listening on.

## To Reproduce

1. Run `postal start`
2. Run `postal status`
3. Notice output has Ports column but no ports listed in it

## Expected behaviour

I expected to see the ports listed in the Ports column of the output, but has to dig around for an hour or so the figure out that they are opened on the docker host

## Screenshots

<img width="818" alt="Screen Shot 2024-03-25 at 2 01 32 PM" src="https://github.com/postalserver/postal/assets/113054034/a136e690-3c19-4da2-a0c7-c204324c4830">

## Environment details 

 - OS: Ubuntu 22.04
 - Postal Version: 3.3.2

**Comment by adamcooke** [comment]
That output just shows the status from docker compose. The ports it listens on are as described by the config file.

**Comment by willpower232** [comment]
If you're running caddy and mysql as docker on the same host (i.e. directly in docker and not part of Postals docker-compose file), you may be interested in the more complete output of `docker ps` and then you can append `-a` which appends the extra information about ports and time created.
