### ISSUE TITLE
Docker Network

### ISSUE THREAD

**Issue by VermiumSifell** [postalserver/postal#2914]
I think docker networks should be used instead of "127.0.0.1". This makes it easier to use Traefik for example.

Basicly get rid of `network_mode: "host"`, and open ports using Docker

**Comment by adamcooke** [comment]
This is incompatible with IP pools. If you want to do this, you're welcome to configure your installation like that if you don't use IP pools but I don't plan on changing the default installation for this I'm afraid.

**Comment by VermiumSifell** [comment]
Okay cool, how can I change to use docker networks? :D

**Comment by willpower232** [comment]
You said it yourself

> Basicly get rid of `network_mode: "host"`, and open ports using Docker

You would have to take responsibility for managing the docker-compose.yml file yourself, I'm not sure if subsequent updates would revert your changes.

**Comment by adamcooke** [comment]
You might be able to use a `docker-compose.override.yaml` to change them and avoid issues some potential issues on upgrades. I haven't tried though so you'd need to experiment.
