### ISSUE TITLE
Upgrade 2.3.2 : Powered by Postal unspecified.

### ISSUE THREAD

**Issue by Killianzrca** [postalserver/postal#2919]
Hello,
After updating from version 2.1.4 to 2.3.2.
Reporting the version number on the HMI does not work.
Message displayed:
_Powered by Postal unspecified._
Is this a known issue?
Do you know how to correct the problem?

This is only a visual bug and the operation of the application is not altered.

**Comment by willpower232** [comment]
Weird, can you share a screenshot?

**Comment by Killianzrca** [comment]
![screen_postal](https://github.com/postalserver/postal/assets/165994828/62d8b802-ec7d-41b7-9bd7-be6b6523d37a)

**Comment by sandrovenezuela** [comment]
This really happens!

I solved it by manually changing the "diff/opt/postal/app/VERSION" file inside the "/var/lib/docker/overlay2" directory.

It is necessary to restart Postal.

**Comment by willpower232** [comment]
Whilst that information is useful, it isn't really the fix as either your docker image was made by someone who used a different process or it is a problem with the real image

**Comment by sandrovenezuela** [comment]
Perfect!

I believe that version 2.1.4 actually has some issues related to upgrading to new versions.

In my tests, to upgrade from version 2.1.4 to version 2.3.2, I had to run the command "postal upgrade 2.3.2" twice.

The first time updates the files and the second time, the new Docker image has been downloaded.

Postal is working correctly for now.

**Comment by adamcooke** [comment]
Upgrade to the latest Postal and this won't be an issue. This was an issue during the build process that does not otherwise affect the image. It won't be fixed now as the 2.x is no longer supported.
