### ISSUE TITLE
Ip rotation not working

### ISSUE THREAD

**Issue by anantsparrow** [postalserver/postal#2937]
Hey there, I have assigned an ip pool to one organization, but it seems to be still sending mail from the default server ip.

**Comment by Artucuno** [comment]
> Hey there, I have assigned an ip pool to one organization, but it seems to be still sending mail from the default server ip.

Heya, did you end up fixing this? I'm having the same problem.

Thanks,
Artu

**Comment by maratgaliev** [comment]
I dont even understand how I can bind multiple IP addresses to my VM on GCP or any other cloud (multiple network interfaces, forwarding, load balancer???), how did you fixed that? @Artucuno @anantsparrow

**Comment by anantsparrow** [comment]
> I dont even understand how I can bind multiple IP addresses to my VM on GCP or any other cloud (multiple network interfaces, forwarding, load balancer???), how did you fixed that? @Artucuno @anantsparrow

attach the additional ips on your server, that's it

**Comment by anantsparrow** [comment]
> > Hey there, I have assigned an ip pool to one organization, but it seems to be still sending mail from the default server ip.
> 
> Heya, did you end up fixing this? I'm having the same problem.
> 
> Thanks, Artu

recreate the organization etc

**Comment by maratgaliev** [comment]
@anantsparrow thanks for your answer, but it still not clear, I have pool of my IPs on GCP, like 50 ips. I want to use all of them, how I can attach them to my VM? Is that on network interface level? Like if I want two IPs I should have 2 network interfaces etc

**Comment by anantsparrow** [comment]
> @anantsparrow thanks for your answer, but it still not clear, I have pool of my IPs on GCP, like 50 ips. I want to use all of them, how I can attach them to my VM? Is that on network interface level? Like if I want two IPs I should have 2 network interfaces etc

Hey there, i have personally never used GCP, i have my own virtualizor , and i run a hosting company, so i manage all these from virtualizor only. talking about the gcp, https://cloud.google.com/migrate/compute-engine/docs/4.9/how-to/networking/using-multiple-ip-addresses this might help you, it seems very simple

**Comment by maratgaliev** [comment]
Thank you for the link! But this is for internal addresses, my understanding is - I need external IPs for the IP pool?

**Comment by anantsparrow** [comment]
> Thank you for the link! But this is for internal addresses, my understanding is - I need external IPs for the IP pool?

okay so you meant by BGP session?
