### ISSUE TITLE
After upgrade to V3 no mails are sent

### ISSUE THREAD

**Issue by uhlhosting** [postalserver/postal#2941]
## Describe the bug

TypeError: no implicit conversion of Array into String

## To Reproduce

Follow official upgrade path from latest 2 to 3.

## Expected behaviour

A working postal v3.

## Screenshots

<img width="1461" alt="image" src="https://github.com/postalserver/postal/assets/6324047/2f33398f-1756-4e29-a11a-726021a57112">

## Environment details 

 - OS: ubuntu
 - Browser safari, chrome
 - Version latest
 - Type desktop

## Additional information/context

Add any other context about the problem here. It is particularily useful to include log extracts (after removing private information).

**Comment by willpower232** [comment]
Are you able to find the full stack trace from within the logs? Probably somewhere in the `postal logs worker` output.

**Comment by uhlhosting** [comment]
@willpower232 Will have to redo that. Since i was forced to restore a backup.

**Comment by adamcooke** [comment]
Can you confirm the exact version you’re running?

**Comment by uhlhosting** [comment]
@adamcooke 

```
CONTAINER ID   IMAGE                               COMMAND                  CREATED       STATUS        PORTS                                                                      NAMES
a34297612656   ghcr.io/postalserver/postal:2.2.2   "/docker-entrypoint.…"   5 weeks ago   Up 28 hours                                                                              postal-smtp-1
6ec9940805e8   ghcr.io/postalserver/postal:2.2.2   "/docker-entrypoint.…"   5 weeks ago   Up 28 hours                                                                              postal-worker-1
a4b242436d9c   ghcr.io/postalserver/postal:2.2.2   "/docker-entrypoint.…"   5 weeks ago   Up 28 hours                                                                              postal-cron-1
e699c9930eac   ghcr.io/postalserver/postal:2.2.2   "/docker-entrypoint.…"   5 weeks ago   Up 28 hours                                                                              postal-web-1
2ec30e60fbfc   ghcr.io/postalserver/postal:2.2.2   "/docker-entrypoint.…"   5 weeks ago   Up 28 hours                                                                              postal-requeuer-1
ac18cbbb80ab   rabbitmq:3.8                        "docker-entrypoint.s…"   2 years ago   Up 28 hours   4369/tcp, 5671/tcp, 15691-15692/tcp, 25672/tcp, 127.0.0.1:5672->5672/tcp   postal-rabbitmq
dd8d1f2d5478   mariadb                             "docker-entrypoint.s…"   2 years ago   Up 28 hours   127.0.0.1:3306->3306/tcp                                                   postal-mariadb
e3b3c5365e01   439af64db489                        "caddy run --config …"   2 years ago   Up 28 hours  
```

this is aftter the restore, before was latest 2.2.x release before the major v3.

**Comment by Reftek85** [comment]
I have the same issue, 
I can send emails using the SMTP connector with an API key, but when I try to reply to an email that try to use a route and an address endpoint
TypeError: no implicit conversion of Array into String
![image](https://github.com/postalserver/postal/assets/63370623/54000749-a70a-42ae-b439-87129b5b0527)

**Comment by Reftek85** [comment]
So, its related to ClamAV,
I turned off rspamd and retried, still not working.
i turned off clamav and retried and it was now working!
I enabled rspamd and it still is working.
turned back on clamav in postal.yml, and I now get this error again.

so its a good news overall, other than I wont be able to scan viruses.

**Comment by uhlhosting** [comment]
@willpower232 any news on this matter? Other what community discussed?

**Comment by willpower232** [comment]
I was waiting for @adamcooke to continue now he has your answer about which version, I just removed the stale tag to keep it open until he is able to reply

**Comment by uhlhosting** [comment]
Tried upgrading again. Got same: TypeError: no implicit conversion of Array into String

**Comment by uhlhosting** [comment]
@adamcooke hi, any updates on this matter?

**Comment by grrinch** [comment]
Hi All, maybe not applicable, but I had the same issue just now after updating v2 to v3 (latest) and the same issues started coming up.

I debugged the logs and this drew my attention:
```
...
worker_1  | 2024-08-19 22:15:05 +0000 ERROR  Error talking to spamd: Errno::ECONNREFUSED (Connection refused - connect(2) for "127.0.0.1" port 783) component=worker thread=work0 original_queued_message=22521 queued_message=22521
worker_1  | 2024-08-19 22:15:05 +0000 INFO   internal error: TypeError: no implicit conversion of Array into String component=worker thread=work0 original_queued_message=22521 queued_message=22521
...
```

Seemed unlikely, but still weird that the one error before this was issue where Postal could not connect to SpamAssassin.

So I checked SpamAssassin service status and indeed, it was inactive:

![image](https://github.com/user-attachments/assets/f749a8a0-3147-459d-8cb8-e7651aaa1050)

As soon as I started it and re-tried delivering the failed emails... Boom, all worked fine.

Just leaving here in case it could help anyone.

**Comment by uhlhosting** [comment]
@grrinch did you hit the same errors as me above in postal UI?

**Comment by grrinch** [comment]
The exact same, also on Ubuntu.

**Comment by uhlhosting** [comment]
@grrinch Thanks, will retry the upgrade. Have done this already twice always failed same way. And decided to wait for a fix. Yet that did not arrived yet. So will check your solution when at pc.
