### ISSUE TITLE
Local SMTP Endpoint Route Not Working

### ISSUE THREAD

**Issue by jmondragon** [postalserver/postal#2947]
## Describe the bug

I've got Postal up and running and almost everything is working.  Inbound routing works for Address Endpoints, but doesn't seem to work for SMTP endpoints.  I am using Postal for outbound email successfully, and the goal was to replace inbound email intended for a self-hosted GitLab's incoming email service.  Previously, I simply NAT'd TCP/25 directly to the internal GitLab instance, but would like to place Postal between them so that I can have more flexibility with all inbound email to the domain.

## To Reproduce

1. Add SMTP Endpoint with internal IP address.
2. Add a route that uses the SMTP Endpoint
3. Send an email to this new route.
4. Incoming Messages error indicates "No SMTP servers were available for <domain>.  No hosts to try."

## Expected behaviour

I expected the email to be delivered to Postal first and then forwarded to the GitLab instance (where I'm also running Postfix).

## Screenshots

N/A

## Environment details 

 - OS: Ubuntu
 - Browser: Chrome
 - Version: Postal 3.3.3
 - Type: Web UI

## Additional information/context

SMTP directly into GitLab works.  Telnet to GitLab SMTP (TCP/25) from the Postal host works.

**Comment by jmondragon** [comment]
Thank you for your reply.  I apologize, I just realized I didn't explain that GitLab is on a separate VM, so I didn't need to change the SMTP port there.  Postal is running on it's own server and the SMTP Endpoint just has the IP of the GitLab server (and the default port 25).

**Comment by willpower232** [comment]
Did you have a look at the SMTP logs in Postal?

> Add SMTP Endpoint with internal IP address

I just spotted this, I bet that is the problem. I think it has to be a hostname in the box rather than an IP address.

**Comment by jmondragon** [comment]
Perfect!  This was, in fact, the issue.  I had to add an entry to my `/etc/hosts` so that it resolved correctly internally, but once I did that, it worked with the hostname rather than IP.

**Comment by willpower232** [comment]
Glad you figured it out :pray:
