### ISSUE TITLE
ContainerConfig error at postal upgrade

### ISSUE THREAD

**Issue by modir** [postalserver/postal#2957]
## Describe the bug

I have a server which had postal 2.2.2 running for a long time. I did now first a `apt-get update` and `apt-get upgrade` to update Ubuntu. Afterwards I did the update of postal as described in the official documentation. The whole upgrade went fine up to the last part where the new containers should get started. I got the same ContainerConfig error as the person is this [forum post](https://askubuntu.com/questions/1508129/docker-compose-giving-containerconfig-errors-after-update-today). According to the main answer in this forum post the problem is that `docker-compose` is outdated and we should use `docker compose` instead. When I ran the command inside `/opt/postal/install` like mentioned then indeed the containers came up without any problems.

I guess that apt-get upgrade left `docker-compose` and a buggy version and inside the `postal` tool the calls are still made to `docker-compose` instead of `docker compose`.

## Environment details 

 - OS: Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-105-generic x86_64)
 - Postal version: 3.3.3
 - Docker version: 26.1.1

**Comment by willpower232** [comment]
The latest version of the install repo uses whichever command is available, `docker-compose` or `docker compose` https://github.com/postalserver/install/blob/main/bin/postal

I don't think this is a current Postal issue.

**Comment by modir** [comment]
Sadly your if statement is going the wrong way. If both versions are possible then it takes `docker-compose` instead of `docker compose`. Which is a typical situation when you do update on a Linux system and you still have the old script around even though the new `docker compose` is around and should be used.

If you don't want to solve it in the code then at least it would be great to have a note in the documentation about this.
