### ISSUE TITLE
Deleting an address endpoint causes not to be able to load routes anymore

### ISSUE THREAD

**Issue by niels-przybilla** [postalserver/postal#2967]
## Describe the bug

I deleted an address endpoint. After deleting the address endpoint i cannot access the route tab anymore.
It is only in this specific mailserver. All other route setting of other servers are working,

## To Reproduce

1. Go to "Routing"
2. Click on Address endpoints
3. delete one ( i had only one)

## Screenshots

![Monosnap We're sorry, but something went wrong (500) 2024-05-13 08-19-57](https://github.com/postalserver/postal/assets/99684821/74fd484d-f5d2-4f26-834f-47fab4f104ee)

## Environment details 

 - OS: Ubuntu 20
 - Version 3.3.2

**Comment by willpower232** [comment]
You will need to rummage through `postal logs web` in order to find the exception message and full stack trace so someone can help you further.

**Comment by mohamed-mourabit** [comment]
same here:

![image](https://github.com/user-attachments/assets/f6a49c8c-bcdd-440c-bd2f-2173b4b2c8af)

stacktrace:

ERROR  GET /org/dso/servers/dev-solus/routes (500) event=request transaction=6781af57e59fa2b6ab0c controller=RoutesController action=index format=html method=GET path=/org/dso/servers/dev-solus/routes request_id=937b3635-78ea-4ad6-83b9-e50555ef75e6 ip_address=172.24.0.13 status=500 db_runtime=6.428897857666016 exception_class=ActionView::Template::Error exception_message=undefined method `description' for nil:NilClass exception_backtrace=/opt/postal/app/app/views/routes/index.html.haml:43:in `block (2 levels) in _app_views_routes_index_html_haml__1911547863970772885_58660'\n/usr/local/bundle/gems/actionview-7.0.8.1/lib/action_view/helpers/capture_helper.rb:45:in `block in capture'\n/usr/local/bundle/gems/actionview-7.0.8.1/lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'\n/usr/local/bundle/gems/actionview-7.0.8.1/lib/action_view/helpers/capture_helper.rb:45:in `capture'
105.72.255.108 - - [24/Aug/2024:23:13:06 +0000] "GET /500 HTTP/1.1" 500 1477 0.0350

**Comment by mohamed-mourabit** [comment]
same here:

![image](https://github.com/user-attachments/assets/6271c73d-d625-49bb-a3a3-bf9bfcb00694)

stacktrace:

ERROR  GET /org/dso/servers/dev-solus/routes (500) event=request transaction=6781af57e59fa2b6ab0c controller=RoutesController action=index format=html method=GET path=/org/dso/servers/dev-solus/routes request_id=937b3635-78ea-4ad6-83b9-e50555ef75e6 ip_address=172.24.0.13 status=500 db_runtime=6.428897857666016 exception_class=ActionView::Template::Error exception_message=undefined method `description' for nil:NilClass exception_backtrace=/opt/postal/app/app/views/routes/index.html.haml:43:in `block (2 levels) in _app_views_routes_index_html_haml__1911547863970772885_58660'\n/usr/local/bundle/gems/actionview-7.0.8.1/lib/action_view/helpers/capture_helper.rb:45:in `block in capture'\n/usr/local/bundle/gems/actionview-7.0.8.1/lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'\n/usr/local/bundle/gems/actionview-7.0.8.1/lib/action_view/helpers/capture_helper.rb:45:in `capture'
105.72.255.108 - - [24/Aug/2024:23:13:06 +0000] "GET /500 HTTP/1.1" 500 1477 0.0350

**Comment by willpower232** [comment]
Logs provided by someone else in #3101
