### ISSUE TITLE
No complaint Feedback Loop handling like SendGrid, Mailgun, Postmark, AWS...

### ISSUE THREAD

**Issue by benstaf** [postalserver/postal#3084]
Hi, Postal doesn't have a way to deal with complaints and spam reports, like it has for bounces.

Documentation doesn't say anything about complaints:
https://docs.postalserver.io/developer/webhooks

In the email industry, spam complaints are a clear metric to determine abuse and poor sending practices. It’s important to take these reports seriously to ensure the best delivery. 

Lacking this feature is a serious bug.

Compare with SendGrid:

https://sendgrid.com/en-us/blog/in-praise-of-spam-complaints

Mailgun:

https://help.mailgun.com/hc/en-us/articles/203661564-Events-Logs-Message-Event-Types

Postmark:

https://postmarkapp.com/support/article/815-what-are-bounces-and-spam-complaints

Amazon:
https://aws.amazon.com/blogs/messaging-and-targeting/amazon-ses-set-up-notifications-for-bounces-and-complaints/

Sparkpost:
https://bird.com/guides/what-is-an-email-feedback-loop-(fbl)

Typical good complaint rate is 0.08%, so when sending 10 M emails, it's 8000 complaints to address, this can't be done manually

**Comment by willpower232** [comment]
please don't duplicate discussions into issues

**Comment by benstaf** [comment]
Discussion is here: https://github.com/orgs/postalserver/discussions/3083#discussion-7024832

It's an issue more than a discussion
