### ISSUE TITLE
Automatic Retention not working? Manual Trigger?

### ISSUE THREAD

**Issue by shakalandy** [postalserver/postal#3119]
## Describe the bug

It appears that the Retention is not working over here.
We have 26GB Space used, but the Retention set to 14 days and space usage now limited to 2GB, see screenshots, also from MySQL raw-tables.

Can it be triggered by a CLI command or job to be run "manually"?
Can we do the retention manually to reclaim space, e.g. by deleting tables?

## Expected behaviour

Retention is reducing MySQL Usage to the configured value (as slightly above)

## Screenshots

![image](https://github.com/user-attachments/assets/c0064c8d-5ce2-42fb-8342-1db1160716af)
![image](https://github.com/user-attachments/assets/7246a2d6-4e10-443d-a771-3cce60c56f88)

## Environment details 

 - OS: Ubuntu
 - Postal Version 3.3.4
 - Type [e.g. desktop, mobile etc...]

## Additional information/context

Where are the logs of the "retention job"? is it in the "worker container" or somewhere else?

Thanks very much.

**Comment by willpower232** [comment]
Are you definitely running Postal 3.3.4? That was released specifically to fix this problem.

I believe the logs would be mixed in with the web if there were any so you would need to `postal logs web` to confirm either way.

**Comment by shakalandy** [comment]
@willpower232 yes, at least, the image is there and postal identifies itself as 3.3.4:

![image](https://github.com/user-attachments/assets/1b94da2b-f639-4a5e-b39e-f9d6c63e38a1)

![image](https://github.com/user-attachments/assets/df1096cf-abaa-42a6-98c7-04c905223e91)

In fact, I updated it 2 hours before to make sure, that If have the recent version in place.
Is the cleanup happening only once per day?

**Comment by willpower232** [comment]
Yeah I think its overnight sometime, check back tomorrow I guess :sweat_smile:

**Comment by shakalandy** [comment]
Thanks @willpower232 - it worked and was automatically cleaned up through the night at 05:00 o'clock.

not sure, if that could be configured somewhere, maybe it helps.

Closing and thanks again @willpower232

**Comment by willpower232** [comment]
Good to know its all still working!
