### ISSUE TITLE
nginx default

### ISSUE THREAD

**Issue by gthb1** [postalserver/postal#312]
Suggesting to use something else than 'default' for doc root, since:
https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/#using-the-default-document-root

**Comment by willpower232** [comment]
This is a good idea but hopefully you wouldn't be running anything more than postal on the actual server.

**Comment by catphish** [comment]
Where is the default document root used?

**Comment by willpower232** [comment]
The wiki instructs to use the "default" file which I presume is the issue...

https://github.com/atech/postal/wiki/Installation

**Comment by gthb1** [comment]
@willpower232 
Am trying to get phpmyadmin onto it, and after destroying apache/php/nginx and fixing it all, now only have to fix the nginx config ;)
My next test vps will go with centos/cwp to see how it works when there is postfix mx underneath from the outset, maybe that makes the routing of incoming easier.

@catphish 
# the ln »@default« is in /etc/nginx/sites-enabled/
# the file »default« is in /etc/nginx/sites-available/
`server {
    listen [::]:443 ssl;
    listen 0.0.0.0:443 ssl;
    root /opt/postal/app/public;
    server_name`

PS: postal is awesome!

**Comment by catphish** [comment]
The documentation seems to be saying not to use the default document root, which we don't.

With that said, it makes sense to also not use the default site configuration file, and instead disable the default site, create a new site, and enable that.

**Comment by gthb1** [comment]
Yes, the documentation mentions default file and doc root, and as such it is best to avoid a ticking sys update snafu ;)
Thx for wise action!

**Comment by catphish** [comment]
I haven't taken any action yet. I will mark this as an enhancement though, shouldn't be too hard to change for new installs.

**Comment by pedalpoweredsoftware** [comment]
**@willpower232**
When you say:
> "This is a good idea but hopefully you wouldn't be running anything more than postal on the actual server."
Do you mean on the web server (software) or on the entire computer?

**Comment by willpower232** [comment]
The [installation](https://github.com/atech/postal/wiki/Installation) page on the wiki literally says
> It is highly recommended/required that you install Postal on a clean server. This guide assumes that the server does not have any other services running on it.

Postal can use a lot of CPU and memory so its better to not have it competing for resources alongside a business-critical website for example.
