### ISSUE TITLE
Postal Security Hardening

### ISSUE THREAD

**Issue by igerzog** [postalserver/postal#335]
Is it possible to improve smtp server security as it is made with fast server for example? It is very necessary to solve these important issues:
```
1. Cipher preference. The server does not prefer cipher suites.
2. DH parameter (1024) is too small.
3. The server supports a client-initiated secure renegotiation that may be unsafe.
```
Besides is it possible to use ECC instead of RSA?

**Comment by catphish** [comment]
It should be quite easy to make these enhancements :+1:

**Comment by igerzog** [comment]
Wonderful! Waiting with patience :)
