### ISSUE TITLE
Spam Not Checked

### ISSUE THREAD

**Issue by ilearnbydoing** [postalserver/postal#402]
the outgoing email is not getting checked for spam though I followed the steps to configure it.

it says spam not checked check screenshot

![image](https://user-images.githubusercontent.com/4979654/32701905-d82d9f8c-c803-11e7-9dc5-28d08b7f2f3b.png)

**Comment by willpower232** [comment]
Outgoing spam checking is disabled by default, you need to change the advanced settings to set an "outgoing spam threshold"

![image](https://user-images.githubusercontent.com/1619102/32720958-e57ffdf2-c85c-11e7-8ba8-75e366e748bf.png)

**Comment by ilearnbydoing** [comment]
Please check if it is normal.
![image](https://user-images.githubusercontent.com/4979654/32722150-f5d8b950-c88e-11e7-86d1-350121aa74c3.png)

**Comment by willpower232** [comment]
Do you get the "error when scanning for spam" on all new messages now?

**Comment by ilearnbydoing** [comment]
all the messages in fact I have other mail server activated and this is coming in all.

**Comment by ilearnbydoing** [comment]
does it means not spam? as it shows in spam status

![image](https://user-images.githubusercontent.com/4979654/32724381-10dd6f90-c897-11e7-8dae-0afe3db2c891.png)

**Comment by willpower232** [comment]
The "error" implies that spamassassin has not been set up or is not running.

I get this
![image](https://user-images.githubusercontent.com/1619102/32724599-d6b4f630-c869-11e7-88e5-ed2237bc8578.png)

Presumably as the spam scan wasn't able to return a negative answer, Postal records it as not spam. There is probably some work to do there but you should investigate your spamassassin and make sure it is running.

**Comment by dmilbert** [comment]
Check the postal log "message_inspection.log" (/opt/postal/log/message_inspection.log) if you see the following error:
`Error talking to spamd: Errno::ECONNREFUSED (Connection refused - connect(2) for "127.0.0.1" port 783`

or something similar then a possible solution that worked for me is to add:
`-d 127.0.0.1`

to the spamassasin EnvironmentFile/config file in the options section.

**Comment by willpower232** [comment]
@dmilbert are you saying that spamassassin wasn't running as a daemon for you? are you using an OS that isn't Ubuntu 16.04?
