### ISSUE TITLE
ClamAV Thread Header always "no"

### ISSUE THREAD

**Issue by ripkens** [postalserver/postal#406]
To have the X-Postal-Threat header set to be true if ClamAV finds a Threat, one Line has to be changed in **/app/jobs/unqueue_message_job.rb Line 132**

Old: `"X-Postal-Threat: #{queued_message.message.threat == 1 ? 'yes' : 'no'}"`
New: `"X-Postal-Threat: #{queued_message.message.threat ? 'yes' : 'no'}"`

**The Problem is, that the mail inspection returns "true" or "false" not 1 or 0**

Additionaly, an extra header should be added:

`"X-Virus-Status: #{queued_message.message.threat_details}"`

**Comment by ripkens** [comment]
Additionally, a global setting should be introduced how to handle Virus checks (Mark, HardFail, Scores etc.).

**Comment by willpower232** [comment]
Soudns good, are you able to make a pull request for this?

**Comment by ripkens** [comment]
Done ...

**Comment by willpower232** [comment]
Lovely, hopefully atech will get round to some merges soon...

**Comment by willpower232** [comment]
@ripkens your commit never left your fork, can you make a pull request to this repository?

**Comment by ripkens** [comment]
The pull request is here:https://github.com/atech/postal/pull/408

**Comment by willpower232** [comment]
Ah my mistake sorry

**Comment by tankerkiller125** [comment]
I added the code from this request into my own deployment for testing, running http://www.emailsecuritycheck.net on my server for receiving postal never detected any of the test files as a Virus even though it should have?

**Comment by adamcooke** [comment]
Duplicate of #206
