### ISSUE TITLE
Can I set a (prefered) delivery time/date for an email?

### ISSUE THREAD

**Issue by ghost** [postalserver/postal#423]
Is it possible to set the intended time/date in which an email delivery would be first attempted?

**Comment by willpower232** [comment]
This is not a feature of Postal, messages are sent immediately or after a short delay.

**Comment by Mr-Binary** [comment]
Thank you @willpower232, since marketers are concerned with these details, do you think it might be a good feature for postal?

**Comment by willpower232** [comment]
Its not a bad feature but its not a feature for Postal (see https://github.com/atech/postal/wiki/FAQs#can-you-add-mailing-list-feature)

It would be better to create your own software solution and send the messages via Postal via your own scheduling system.

**Comment by Mr-Binary** [comment]
I understand adding email management capabilities is out of this project scope, however, I think that wiki article does not apply to what I am describing.

I am talking about improving the queue with a simple (desired) time tag, that would improve the effectiveness of marketing messages.

I do however understand managing this at the sending app has some advantages too.

**Comment by willpower232** [comment]
Postal is primarily focused on developers who need their software to send messages rather than being a marketing email solution so its unlikely to get much traction.

**Comment by Mr-Binary** [comment]
Don´t underestimate marketers, they send most of the legal emails around the world, did you take a survey to see how many of these developers you mention currently work for marketing teams and companies? You might get surprised. I don´t know which is the aim of postal (btw, is there a roadmap somewhere?) but if you want it to be widely used, it would not hurt to accomodate those needs. In the project description you state postal is similar to some of these commercial email relay services, well some of these started supporting this already...

**Comment by Mr-Binary** [comment]
BTW, open and click tracking is a feature that´s totally out of the scope of any traditional email server and it´s been implemented into postal, it´s not needed for technical maintenance of the email server, it´s purely a marketing reporting feature.

**Comment by catphish** [comment]
I'll leave this open as a feature request. Feel free to implement it.

**Comment by Mr-Binary** [comment]
Thank you catphish, 
I have to implement this either on Postal or directly into my app.
Any pointers on where to start?
