### ISSUE TITLE
Incorrect setting description in Tracking Domain Setting form

### ISSUE THREAD

**Issue by willpower232** [postalserver/postal#441]
These two lines of text make no sense for the `SSL ENABLED` dropdown.

https://github.com/atech/postal/blob/2f0155747c5c058afb83856ce5c3c8d5f8cad341/app/views/track_domains/_form.html.haml#L20-L21

Could someone write something more accurate? I'm not sure what it should be precisely.

**Comment by adamcooke** [comment]
Already fixed.
