### ISSUE TITLE
The sending email help page still shows port 2525 as an option

### ISSUE THREAD

**Issue by willpower232** [postalserver/postal#473]
Port 2525 isn't a thing anymore (without customisation) but still confusingly shown on the help page

https://github.com/atech/postal/blob/21039f07e8aa66d671b203188e69553398b485e4/app/views/help/outgoing.html.haml#L33

**Comment by neidiom** [comment]
If port 2525 is not a thing anymore what shall we use in /opt/postal/config/postal.yml as it is configured to 2525 by default?

**Comment by adamcooke** [comment]
Fixed in 4404b3e
