### ISSUE TITLE
Send attachments Content-ID in webhooks

### ISSUE THREAD

**Issue by FloGou** [postalserver/postal#486]
Hi,

Perhaps I'm missing something, but it seems from the doc [here](https://github.com/atech/postal/wiki/HTTP-Payloads) that I can't receive content-id with attachments on my webhooks.
This poses a problem since without them I can't correctly render the origin html email.
Is this on purpose ? is there another way I can retrieve that piece of information ?

**Comment by dsnopek** [comment]
The webhooks send very little information in their payload. Generally, you need to call back to Postal via the API to get more information about the message.

**Comment by willpower232** [comment]
Webhooks refer to message events such as message opened or link clicked when an email has been sent by Postal.

The article you have linked to refers to passing an email received by Postal to your application via Routing.

I don't know for certain but if you choose to receive the email "Delivered as the raw message" you probably get the information you need (i.e. Content-ID) in there?

**Comment by FloGou** [comment]
Yes sorry, I was referring to the routing feature. 
Getting the raw message was what I ended up doing, but it is a bit frustrating since the Content-ID was the only info I missed to correctly render the mail without having to do the parsing myself.

**Comment by willpower232** [comment]
If you are able to implement missing feature, do make a pull request.

Unfortunately, we don't receive emails through Postal so don't really have any need to have it at this time.
