### ISSUE TITLE
Support for installing on CentOS/RHEL

### ISSUE THREAD

**Issue by pedalpoweredsoftware** [postalserver/postal#539]
Currently it is not recommended to install on CentOS. I would assume the only supported workaround would be to install in an Ubuntu VM. Is that the case?

**Comment by willpower232** [comment]
Its not officially supported on Centos/RHEL but there are a number of people who have mentioned they run it on Centos in various issues so if you can change the install commands to be relevant (i.e. use yum) then theres nothing stopping you from using it if you're more comfortable that way.

**Comment by pedalpoweredsoftware** [comment]
Thanks! That gave me the reassurance to install it on CentOS. BTW, by searching the issues, I only found someone running it on CentOS in this issue:
https://github.com/atech/postal/issues/338
And one person saying they wanted to attempt to install it on CentOS.
And no RHEL or Red Hat.
