### ISSUE TITLE
Tracking in base64 encoding

### ISSUE THREAD

**Issue by laci84** [postalserver/postal#548]
Tracking is working in plain text emails, but not in base64 encoding. How can I configure it?

**Comment by willpower232** [comment]
Can you download a testing message from Postals UI and attach it here?

**Comment by laci84** [comment]
The problem is the @ in url:

http://test.com/part1/part2/part3@part4/part5/ is not okay

http://test.com/part1/part2/part3/part5/ is okay

**Comment by willpower232** [comment]
Ah probably related to https://github.com/atech/postal/pull/296 and https://github.com/atech/postal/issues/115 although that doesn't include `@`.

I presume you can replicate the issue without the base64 encoding?

**Comment by laci84** [comment]
Yes, its not related to base64 encoding but special char '@'

**Comment by willpower232** [comment]
Yes thank you.

Is that "not okay" link exactly the kind of link you are using? Are there any subtle varieties of it you might use as well? We will need some accurate links to test with.

**Comment by laci84** [comment]
Yes, "http://test.com/part1/part2/part3@part4/part5/" was tested, and not replaced.

**Comment by willpower232** [comment]
Thanks, I'm not sure when I'd get a chance to test so you could try incorporating the changes from the pull request into your Postal and adding `@` to the regex which is already being modified there or wait to see if it can get updated/merged.
