### ISSUE TITLE
Using SSL Certificates on each mail server 

### ISSUE THREAD

**Issue by alnalda** [postalserver/postal#600]
Hello all, 
i was trying to use SSL certificates on my Postal installation and i see we need to set it up on the configuration file as said here: [https://github.com/atech/postal/blob/master/config/postal.defaults.yml#L71-L81](https://github.com/atech/postal/blob/master/config/postal.defaults.yml#L71-L81)

I asumme that this option only allows to use a certificate for the whole installation and **i was wondering whether there was a way to add a certificate for a single mail server**, i.e. having multiple certificates and using them in the desired mail servers.

Thank you in advance.

**Comment by willpower232** [comment]
All mail servers running from your Postal should use the same domain name which is probably the same address you use to log in to it.

Postal is not set up as a white-label solution that allows each mail server to have a separate domain name that accesses it.

**Comment by alnalda** [comment]
Thanks for the info, well i would use the same installation of Postal with multiple services i manage and all of them have its own domain. i wanted to use its own certificates on each mail server or organisation.

Having said that, i understand your point and probably this is not the tool for my purpose. Correct me if i'm wrong please. 

Thanks

**Comment by willpower232** [comment]
If you want to send messages via SMTP and Postal, there can only be one domain.

If you were only intending to use the API, you might be able to get nginx to use different URLs and certificates but this hasn't been tested and isn't what Postal is designed for currently.

**Comment by alnalda** [comment]
hmm forgive me for insisting but i think i didn't explain myself. 

My goal is signing the mails i send via Postal. As i have multiple servers (each one with its own domain), i would need to sign mailings from each mail server (each domain) with the corresponding signature. 

Regards.

**Comment by willpower232** [comment]
Postal provides SPF and DKIM for emails but no ability to sign or encrypt messages. The certificates are used for connection purposes only.
