### ISSUE TITLE
Different DKIM keys (from database & from /config/signing.key)

### ISSUE THREAD

**Issue by oasis1234** [postalserver/postal#616]
Hi, everybody. Here another guy with the 'strange' goal of protecting my platform from potential attacks. Having a webhook is an open door to receive Message Status Events, Send Limit Events and DNS Error Events that could be forged if the message is not verified. Thanks to my new hero David Snopek (another guy who managed to solve his problems without help), I was able to implement a signature verification function.
Snopek noticed that the DKIM key used for the webhook signing ('X-Postal-Signature' header) comes from 'postal default-dkim-record' and not from the DKIM TXT DNS record. https://github.com/atech/postal/issues/432#issuecomment-353143578 His confusion was understandable: besides the fact that the webhook signing is completely undocumented, there's also an underlying problem, explained here.

The DKIM pub key from `postal default-dkim-record` comes from /opt/postal/config/signing.key and it's used for the webhook signing (X-Postal-Signature).
The key in the DKIM Record (DNS Setup page) comes from the database and it's the actual key used for email signing.

You can check this info by getting the pub key.
`openssl rsa -in /opt/postal/config/signing.key -pubout -out public.key`
This is the same as the key from `postal default-dkim-record`.

I was really confused. I found the post 'How to know Default DKIM Private Key?' https://github.com/atech/postal/issues/202 Wrong info. My question was: How can Postal generate different DKIM public keys for different domains from the same signing.key?
Then, after some research, I found that... the keys are stored in a database! The official docs doesn't explain this method. You can check the real keys with these commands:
```
$ mysql -u root -p
> use postal;
> SELECT dkim_private_key FROM domains WHERE name = "example.com";
```
This issue has several implications. First, the one regarding the webhook signing. Second, the confusing documentation.
https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration
DKIM record. (Section not labeled). "_When the installation is initialised a key will be generated automatically._"
Are you talking about the 'signing.key' or the database record?
"_You can see the appropriate value for this record by running 'postal default-dkim-record' on the host._"
**Wrong!** You need to add the value from the 'DNS Setup' page, which is generated for each different domain and is stored in the database.
If you add the default DKIM record to your DNS table, the verification will fail, as it expects the value from the database.

**Comment by tiltec** [comment]
I'll revive this issue because I was also confused by this but I think I could resolve it. It definitely helps to have better documentation.

First, we need to keep apart the _Postal instance_ (e.g. postal.example.com) and an _email sending domain_ (e.g. mails.yourdomain.com)

These things are about the Postal instance:
- https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration
- `postal default-dkim-record`
- `signing.key`

Whereas the DKIM record on the DNS Setup page is about the _email sending domain_. This is stored in the database because one Postal instance can have many email sending domains, hence also many DKIM records.
