### ISSUE TITLE
Add Caddyfile example

### ISSUE THREAD

**Issue by tankerkiller125** [postalserver/postal#622]
I recently migrated to [caddy](https://caddyserver.com) for my web server, I'm not sure where its best to put example files so I figured I'd share here and if someone wants to point me in the right direction for a pull request I'll do that:

First, add the postal user to your caddy user group then set the following as your Caddyfile config OR add it:

```
postal.yourdomain.tld {
        root /opt/postal/app/public

        proxy / localhost:5000 {
                header_upstream Host {host}
                header_upstream X-Real-IP {remote}
                header_upstream X-Forwarded-For {remote}
                header_upstream X-Forwarded-Proto {scheme}
        }

        header /assets {
                Cache-Control "max-age=3600"
        }
}
```

Caddy does not require the try_file argument or anything special, this will work perfectly everytime. The header_upstream config options could be completely replaced by a shorthand `transparent` but I left them here in case something special is needed in the future. No caddy plugins are required for this to work.

**Comment by willpower232** [comment]
There is a file at https://github.com/atech/postal/blob/master/resource/nginx.cfg so you could fork and pull request a new file along the lines of `resource/caddy.cfg`.

I doubt it would get official support but it would be handy for other caddy users.
