### ISSUE TITLE
Name and format of Opened event

### ISSUE THREAD

**Issue by kirk-quinbar** [postalserver/postal#629]
Unless i am missing something in the documentation, there doesnt seem to be an example and format of the opened event that can be sent to the webhook in postal. I wanted to know the name and json layout.

this is the documentation where i expected it to be:
https://github.com/atech/postal/wiki/Webhook-Events-&-Payloads

**Comment by willpower232** [comment]
Good spot!

The name you will receive is `MessageLoaded` and the JSON should be identical to the`MessageLinkClicked` payload but without the `url` and `token` so something like this:

```json
{
  "ip_address":"185.22.208.2",
  "user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36",
  "message":{
    "id":12345,
    "token":"abcdef123",
    "direction":"outgoing",
    "message_id":"5817a64332f44_4ec93ff59e79d154565eb@app34.mail",
    "to":"test@example.com",
    "from":"sales@awesomeapp.com",
    "subject":"Welcome to AwesomeApp",
    "timestamp":1477945177.12994,
    "spam_status":"NotSpam",
    "tag":"welcome"
  }
}
```

**Comment by willpower232** [comment]
One for @adamcooke
