### ISSUE TITLE
Default DKIM identifier should be used instead of hardcoded 'postal'

### ISSUE THREAD

**Issue by ppadron** [postalserver/postal#642]
Hi there,

When assembling the DKIM header for a message, Postal checks if the domain has DKIM records properly configured, and if not it will use the server defaults. However, the `dkim_identifier` is hardcoded instead of using the dns.dkim_identifier setting in postal.yml:

https://github.com/atech/postal/blob/ed7889a40e1d777f1d80821043562ab18b04766e/lib/postal/dkim_header.rb#L12

It seems that this line should be:

```ruby
@dkim_identifier = Postal.config.dns.dkim_identifier
```

Is this correct? I can provide a patch, I just want to be sure this is the expected behavior.

**Comment by willpower232** [comment]
Judging by https://github.com/atech/postal/blob/ed7889a40e1d777f1d80821043562ab18b04766e/lib/postal/dkim_header.rb#L10, I'd say you are correct.

Presumably the default value is rarely changed in the config but your patch would be useful for completeness.

**Comment by catphish** [comment]
You're absolutely correct. Resolved by 87e9b3e3460c727d94f73d19368be0495799468c
