### ISSUE TITLE
prime256v1 (NIST P-256)

### ISSUE THREAD

**Issue by denji** [postalserver/postal#652]
https://github.com/atech/postal/blob/a7e3e9d/lib/postal/fast_server/client.rb#L156

If you have generated a ECDSA certificate with a curve other than prime256v1 (NIST P-256), you need to change the TLS configuration because of a change in OpenSSL >= 1.1.0. For example, if you use secp384r1 elliptic curve with your ECDSA certificate, change the value :

    OpenSSL::PKey::EC.new("secp384r1")

Additional informations about this issue :
* https://github.com/openssl/openssl/issues/2033
* https://bugzilla.redhat.com/show_bug.cgi?id=1473971

**Comment by willpower232** [comment]
Thanks for the that. It also looks like that callback is deprecated under newer Ruby/OpenSSL https://docs.ruby-lang.org/en/2.5.0/OpenSSL/SSL/SSLContext.html#attribute-i-tmp_ecdh_callback

Worth a reply from Atech about how best to update those few lines of code.
