### ISSUE TITLE
Postal can change ip if it's listed ??

### ISSUE THREAD

**Issue by ghost** [postalserver/postal#654]
Hi,
As we Postal can check ip is listed or not.
And my query is when postal send mails it change the ip if it is listed.
Now Postal is doing -
Postal > check ip > listed > Hard fails
Postal can do this ? -
Postal > check ip > listed > change ip > send

**Comment by willpower232** [comment]
I don't believe Postal checks if the IP is listed, it sends the message and gets a response that it is impossible to be delivered.

From a technical point of view, I would have assumed that each email server uses a different message or terminology to imply that the IP address is on a blacklist so it could be difficult to create this functionality.
