### ISSUE TITLE
Support for Ruby 2.5 ?

### ISSUE THREAD

**Issue by neidiom** [postalserver/postal#684]
Any plans to support Ruby 2.5 as `Ruby 2.3 is now under the state of the security maintenance phase, until the end of the March of 2019. `?

**Comment by willpower232** [comment]
Hopefully there are no issues with 2.5, according to https://github.com/atech/postal/issues/549#issuecomment-416014055 there is just one gem change needed to fix a different bug.

Can @catphish or @adamcooke confirm the plans?

**Comment by denji** [comment]
@neidiom Docker/Postal Ruby 2.6 https://github.com/CatDeployed/docker-postal/pull/8

**Comment by willpower232** [comment]
Thanks @denji, good to know about the docker too

**Comment by willpower232** [comment]
Thanks @denji, good to know about the docker too

**Comment by denji** [comment]
@willpower232 https://medium.com/@k0kubun/ruby-2-6-jit-progress-and-future-84e0a830ecbf
