### ISSUE TITLE
Copyedit issue

### ISSUE THREAD

**Issue by yasoob** [postalserver/postal#686]
<img width="456" alt="screen shot 2018-10-19 at 10 19 44 am" src="https://user-images.githubusercontent.com/3696393/47224162-d78aa200-d388-11e8-9684-b5c1db090b60.png">

Shouldn't it be "sent" instead of "send"?

**Comment by willpower232** [comment]
Ah yes on the Postal web page. Unfortunately that page isn't currently open source as far as I can see so this is something for @catphish and @adamcooke

**Comment by adamcooke** [comment]
This website no longer exists.
