### ISSUE TITLE
Email already taken and Change user permissions

### ISSUE THREAD

**Issue by criskolkman** [postalserver/postal#689]
Hello,

Once you've added a user with his/her email and you delete the account, you can re-add the user with the same email address but when a user clicks on the link send to his/her email and tries to set the password, you get the error that the email address is already in use.

Also, once you've added a user and the user created his/her account, you cannot change the users permissions.
E.g. from non-admin to admin, the **Save User** button keeps spinning and the following error is being shown in rails.log:

`
[web.1:9188] [2018-10-30T09:40:05.560] INFO -- : Started PATCH "/org/**org**/users/2ae2d19e-e5b3-4f1a-b837-207a81d42018" for 192.168.*.15 at 2018-10-30 09:40:05 +0100
[web.1:9188] [2018-10-30T09:40:05.561] INFO -- : Processing by UsersController#update as JSON
[web.1:9188] [2018-10-30T09:40:05.561] INFO -- :   Parameters: {"utf8"=>"✓", "invite"=>"", "organization_user"=>{"admin"=>"true"}, "commit"=>"Save User", "org_permalink"=>"**org**", "id"=>"2ae2d19e-e5b3-4f1a-b837-207a81d42018"}
[web.1:9188] [2018-10-30T09:40:05.574] INFO -- : Completed 404 Not Found in 13ms (ActiveRecord: 3.7ms)
[web.1:9188] [2018-10-30T09:40:05.575] FATAL -- :
[web.1:9188] [2018-10-30T09:40:05.575] FATAL -- : ActiveRecord::RecordNotFound (Couldn't find UserInvite):
[web.1:9188] [2018-10-30T09:40:05.575] FATAL -- :
[web.1:9188] [2018-10-30T09:40:05.575] FATAL -- : app/controllers/users_controller.rb:5:in `block in <class:UsersController>'
`

Also it would be nice to have same features like **SendGrid** or **SendInBlue**:
- Users have their own environment
- Sending limit per hour based on their personal reputation (eg they can send less emails per hour when they get many bounces or spam reports)
- Would also be nice to allow non-added domains to send mails through the system

**Comment by hameno** [comment]
I'm seeing the same error just now:
```
15:52:58 web.1 | => [web.1:142] [2019-11-26T15:52:58.633] INFO -- : Started PATCH "/org/orga/users/70834171-acd5-491c-90d3-74529dd27be7" for<ip> at 2019-11-26 15:52:58 +0000
15:52:58 web.1 | => [web.1:142] [2019-11-26T15:52:58.634] INFO -- : Processing by UsersController#update as JSON
15:52:58 web.1 | => [web.1:142] [2019-11-26T15:52:58.635] INFO -- : Parameters: {"utf8"=>"✓", "invite"=>"", "organization_user"=>{"admin"=>"true"}, "commit"=>"Save User", "org_permalink"=>"orga", "id"=>"70834171-acd5-491c-90d3-74529dd27be7"}
15:52:58 web.1 | => [web.1:142] [2019-11-26T15:52:58.690] INFO -- : Completed 404 Not Found in 56ms (ActiveRecord: 41.7ms)
15:52:58 web.1 | => [web.1:142] [2019-11-26T15:52:58.692] FATAL -- :
15:52:58 web.1 | => [web.1:142] [2019-11-26T15:52:58.692] FATAL -- : ActiveRecord::RecordNotFound (Couldn't find UserInvite):
15:52:58 web.1 | => [web.1:142] [2019-11-26T15:52:58.693] FATAL -- :
15:52:58 web.1 | => [web.1:142] [2019-11-26T15:52:58.693] FATAL -- : app/controllers/users_controller.rb:5:in `block in <class:UsersController>'
15:52:58 web.1 | => <ip>, 10.240.0.169 - - [26/Nov/2019:15:52:58 +0000] "PATCH /404 HTTP/1.0" 404 34 0.0620
```
