### ISSUE TITLE
Open tracking works, but click tracking doesn't?

### ISSUE THREAD

**Issue by shinebayar-g** [postalserver/postal#720]
I've revised my postal installation and now it's complete. I've tried to know what it looks like when I enable click & open tracking. So I followed instructions and setup domain, fast server, let's encrypt etc. All good, except only open tracking is working. When I click on links in email, click tracking is not working. My email's urls were rewritten with `click.mydomain.com` which looks like working as intended. Everything looks like OK, but click tracking is still not working.
![image](https://user-images.githubusercontent.com/3091558/51076429-397e4d80-16d3-11e9-9197-7987e3488819.png)
When I open email, it adds **opened** label on email. So I assume if click tracking works, it would add '**clicked**' or something like that ?

Edit: I'm sending html email.

**Comment by willpower232** [comment]
I thought there was a tag but apparently I am mistaken.

You can see that a link was clicked in the Activity tab inside the message or by webhook as mentioned above.

**Comment by shinebayar-g** [comment]
Thank you, I see that they clicked things on activity tab.
