### ISSUE TITLE
Spamassassin scoring

### ISSUE THREAD

**Issue by influenist** [postalserver/postal#737]
Hi, 

Where to set the scoring of Spamassassin, your current config gives a 0 score for RBL :/ 

Also other configuration parameters would be helpful as it isnt implemented into Postal. Like blocking domains. E.q. QQ.com floods etc. The current postal design allows floods to happen and that aint pretty.

Regards,

**Comment by willpower232** [comment]
As per https://github.com/atech/postal/issues/574, theres probably a fair bit around this topic that could be included but I'm not sure whos working on Postal much any more. Most of the functionality is focussed on outbound emails rather than inbound.

**Comment by influenist** [comment]
Hi Will,

Thanks for the reply. Just working on configuration of Spamassassin to take over this part. Will update you as soon as I got a working solution.

**Comment by influenist** [comment]
local.cf  being totally ignored, same as /opt/.spamassassin/user_prefs.cf

Scanning is done in ./app/lib/postal/message_inspection.rb, yet I do not see any score / spam configs being loaded. Anyone have an idea?

**Comment by influenist** [comment]
Fixed this.

Ass per spamc documentation you can specify the user. Updated : /app/lib/postal/message_inspection.rb

```
        tcp_socket = TCPSocket.new(Postal.config.spamd.host, Postal.config.spamd.port)
        tcp_socket.write("REPORT SPAMC/1.2\r\n")
        tcp_socket.write("User: postal\r\n")
        tcp_socket.write("Content-length: #{@message.bytesize}\r\n")
        tcp_socket.write("\r\n")
        tcp_socket.write(@message)
        tcp_socket.close_write
        data = tcp_socket.read
```
Also the user config isn't /opt/postal/.spamassassin/user_prefs.cf but /opt/postal/.spamassassin/user_prefs

Loaded the present for scoring and blacklisting there solved this issue. Now you can blacklist inbound domains and setup custom scoring.

**Comment by willpower232** [comment]
awesome, would you be able to make a pull request for this?

**Comment by AndersonOuverney** [comment]
> To note: rspamd much better then spamassasin in general, better migrate to it.

Did you manage to integrate rspamd with the postal?
