### ISSUE TITLE
SMTP server is not really asynchronous (and so connections timeout when there are simultaneous connection attempts)

### ISSUE THREAD

**Issue by dsnopek** [postalserver/postal#744]
I've been investigating some issues with using the SMTP server to send emails (rather than the API). It was working great for some time, but recently, connections have been timing out. It appears that once a certain number of simultaneous connections try to connect, the connection time will get really long.

The server isn't under particularly high load (0.01). It just appears that the SMTP server is blocking really long if multiple connections are made at the same time.

I've looked at a number of previous issues with this same symptom, and many of those had MySQL connection issues. I'm not seeing any issues with connecting to MySQL in my case.

So, I started digging into the code.

The SMTP server is implemented using an asynchronous event loop:

https://github.com/atech/postal/blob/master/lib/postal/smtp_server/server.rb

However, the "client" code (the class that handles the individual connections) appears to be making multiple blocking calls to the database:

https://github.com/atech/postal/blob/master/lib/postal/smtp_server/client.rb

Checking user authentication and actually saving the message appear to be done through ActiveRecord, which uses blocking IO. :-( I think this is the source of the problem.

It should be possible to implement the SMTP server completely asynchronously, either by switching to something like AsyncRecord or just having the SMTP server communicate with the API (and using async HTTP communication) rather than working with the database directly. Or, switching the SMTP server to use a threading or forking model to handle the connections, so that it's no longer asynchronous, just like the API which is not asynchronous.

However, as it stands now, with an asynchronous server that uses synchronous IO, you're going to inevitably run into issues where it can't handle all the connections, even if the server has the resources...

**Comment by rbustos** [comment]
Totally agree with your research.

**Comment by willpower232** [comment]
Thanks for your efforts @dsnopek, I also imagine there would be a similar problem with the server receiving incoming emails from the general internet?

I don't really know Rails that well but FWIW I would say that the threading/forking approach is probably the least disruptive to the overall system.

Would you be able to make a pull request to address the problem with whatever you feel is the best solution?

**Comment by dsnopek** [comment]
> I also imagine there would be a similar problem with the server receiving incoming emails from the general internet?

Yes, anything coming in on the SMTP server could be affected.

> I don't really know Rails that well but FWIW I would say that the threading/forking approach is probably the least disruptive to the overall system.

I agree. Switching to threading/forking means the code in [the client class](https://github.com/atech/postal/blob/master/lib/postal/smtp_server/client.rb) can probably stay pretty much the same, and keep using ActiveRecord. Making the SMTP server be actually asynchronous would require much deeper changes.

> Would you be able to make a pull request to address the problem with whatever you feel is the best solution?

Unfortunately, while I can sort of read Ruby, I'm not a Ruby developer. That said, over the past couple days I've been looking for a Ruby developer who can create PR and I'm hopeful I can find someone who can hack on it soon!

**Comment by dsnopek** [comment]
Ooo, this is interesting! It looks like the SMTP server used to be threaded, but was converted to an event loop in this commit:

https://github.com/atech/postal/commit/b90632b525dab624b07f7b072c50a9c8773e3a6e

So, here's the smtp_server/server.rb file before those changes:

https://github.com/atech/postal/blob/0f10481da0a276d2be5cb8ec5b7b181268f865c6/lib/postal/smtp_server/server.rb

Of course, the code has changed a bunch after the conversion to an event loop, and those changes would need to be maintained, but perhaps that old implementation could be helpful as a reference?

**Comment by dsnopek** [comment]
Or, actually, no... The old code wasn't pure threaded: it looks like it did an event loop (via epoll) under Linux, and threaded under other platforms. It also looks like it didn't use a thread pool, but created a new thread for every connection, which isn't super efficient. But that code might still be a little useful, I don't know. :-)

**Comment by andrew2net** [comment]
@dsnopek Hello, I installed Postal locally, tried to run RSpec tests, and got errors. Can you help?
```
postal@2f72d2a35a15:~/app$ rspec

An error occurred in a `before(:suite)` hook.
Failure/Error: DatabaseCleaner.clean

DatabaseCleaner::Safeguard::Error::ProductionEnv:
  ENV['RAILS_ENV'] is set to production. Please refer to https://github.com/DatabaseCleaner/database_cleaner#safeguards
...
```

**Comment by dsnopek** [comment]
@andrew2net I haven't personally tried to run the RSpect tests but if you follow the link in the error message, it suggests some environment variables that you can set to disable those safeguards:

```
export DATABASE_CLEANER_ALLOW_PRODUCTION=true
export DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true
```

Perhaps that will help?

I don't really know, but I suppose that may have a negative impact on the database you setup for Postal, so you might have to recreate it after or something?

**Comment by andrew2net** [comment]
@dsnopek The problem is `ENV['RAILS_ENV'] is set to production`.  I tried to set the variable to test and development. It has no effect. If we set `DATABASE_CLEANER_ALLOW_PRODUCTION=true` then it cleans production DB which I use to run Postal server.
Looks like there is a non-standard way to run tests, but I didn't find it in the documentation.

**Comment by dsnopek** [comment]
@andrew2net Unfortunately, that's beyond my limited Ruby knowledge, which is why I need your help with this. :-) Perhaps it would make sense to make a new issue asking about that and maybe someone else in the Postal community will be able to answer?

**Comment by dsnopek** [comment]
Here's a work-in-progress PR https://github.com/atech/postal/pull/751 from andrew2net

**Comment by catphish** [comment]
Per my comments on the PR, I believe the only blocking IO should be on local database requests. I realise this is not ideal, but it should not cause a noticeable problem unless there is a serious database performance problem.

I have found this approach to be considerably better than a threaded approach, however I can certainly understand how the database blocking the whole SMTP process could cause a problem.

There are really 4 options on the table here:

1) Make the database queries async. This is really very difficult.
2) Make the database faster. This works for us!
3) Build a second SMTP server that uses threads only. This is how Postal used to work, and may be a perfectly good option if someone wants to re-implement it.
4) Run multiple SMTP servers. This doesn't 100% solve the problem, but will reduce the impact of an individual slow query and allow more simultaneous queries with zero code changes.

**Comment by dsnopek** [comment]
@catphish One implementation of option nr 3 is PR #751 :-)
