### ISSUE TITLE
404 link in text

### ISSUE THREAD

**Issue by jon-evm** [postalserver/postal#747]
There is a link that goes to a 404 in the text "For full information about how to use our HTTP API, please ***see the documentation.***" (https://gopostal.io/~/http-sending)

Located in Organization > Mail Server > Credentials > Read more about sending outgoing e-mails > Sending over HTTP using our API

**Comment by willpower232** [comment]
This link was fixed a long time ago in https://github.com/atech/postal/commit/21039f07e8aa66d671b203188e69553398b485e4

Please make sure you are using an up to date version of Postal.

**Comment by jon-evm** [comment]
Used this 3 days ago - https://github.com/atech/postal/wiki/Quick-Install

curl https://raw.githubusercontent.com/atech/postal/master/script/install/ubuntu1604.sh | sh

**Comment by willpower232** [comment]
Ah it looks like the builds are quite behind still.

@adamcooke  @catphish any chance of a fresh build?

**Comment by jon-evm** [comment]
Can I use this to upgrade? https://github.com/atech/postal/wiki/Upgrading

**Comment by willpower232** [comment]
Unfortunately you are currently using a package and not a copy of the repo so the commands simply won't change what you have as you're running on the "latest" copy.

You could try replacing your copy of Postal with something like `sudo -i -u postal git clone https://github.com/atech/postal /opt/postal/app` but that might introduce other issues.

**Comment by jon-evm** [comment]
So the quickinstall instructions should be replaced if people want to be able to upgrade.

**Comment by jon-evm** [comment]
Do I need to start all over with a fresh server and follow this or is there a way to use the quickinstall and not be screwed? https://github.com/atech/postal/wiki/Installation

**Comment by willpower232** [comment]
Unfortunately, the instructions don't actually make a lot of sense since that doesn't look to clone a repo and refers to a non-existent devel branch.

Ultimately you are probably fine as you are and upgrading to the bleeding edge of the repo could create a few more problems than it solves unless you are or know a ruby developer who could resolve them.

**Comment by adamcooke** [comment]
If you use the "quick install" script, Postal will be installed from a package and shouldn't touch the repository at all. You can upgrade by following the auto upgrade or the upgrade from package instructions.

> Unfortunately, the instructions don't actually make a lot of sense since that doesn't look to clone a repo and refers to a non-existent devel branch.

Can you point me to these so I can fix them? I had a quick look but couldn't see them.

**Comment by willpower232** [comment]
Theres a whole section about cloning the repo https://github.com/atech/postal/wiki/Installation#cloning-the-repository but it doesn't actually get cloned.

The CLI instructions are fine but the text before and after it doesn't make sense.

**Comment by adamcooke** [comment]
These docs have now been replaced.
