### ISSUE TITLE
Outstanding bugs

### ISSUE THREAD

**Issue by catphish** [postalserver/postal#755]
Because of the large number of open tickets here, would @willpower232 be able to bring my attention to any specific outstanding bugs that require immediate attention?

I am hoping to do a shiny new release this week consisting largely of upstream security patches. outstanding bugs and simple improvements such as config enhancements.

**Comment by willpower232** [comment]
Hello! Glad to see you again.

I would initially draw your attention to my PRs (primarily https://github.com/atech/postal/pull/376) as well as the others in that tab.

Also https://github.com/atech/postal/issues/674 appears to be quite a show stopper but you may have detected and resolved this internally already. As per https://github.com/atech/postal/issues/674#issuecomment-430667774, we're using a version pretty behind the times so any progress here would be especially good.

I don't know if https://github.com/atech/postal/issues/536 is still a problem but might be worth including in some install/update script.

We've also had some issues with https://github.com/atech/postal/issues/521 but I am not sure if there a better resolution than my hack.

The only other note I have is https://github.com/atech/postal/issues/338#issuecomment-349948413 but there may be a more appropriate environment fix.

These are the big ones I have noted down in my list of how to reliably install and use Postal but I'll update again if I find others.

P.S. it would be good to have the ability/permission/authorisation to label issues here to apply a level of triage. I'm not sure how that can be done with githubs permission model but am open to helping out however possible. I believe you already have my email address so we can take this discussion offline if you would like to continue it.

**Comment by saporus** [comment]
@catphish, thanks for this because I have been really waiting for this. I love Postal and I hope it gets improves time to time.

If possible please help us add `Messages that postal detect as being bounces for a message that have already been sent to be delivered to sender return path route`

Most of us here really needs this feature, we have application that manage our return bounces already. We just need Postal to return the bounce code, reason e.t.c to our return path and our app would do the rest.

Please try and help us improve this app even if it means to donate, we will.
@willpower232 has been helping here always.

Best Regards,
Saporus.

**Comment by ilyacherevkov** [comment]
I think another issue is Ruby 2.5 compatibility, and also newer versions of some gems (like Haml) break things

**Comment by influenist** [comment]
Dont forget my solution on Spamassasin: https://github.com/atech/postal/issues/737#issuecomment-460251429

**Comment by willpower232** [comment]
@ilyacherevkov Ah yes Ruby 2.5 is probably a big one with the imminent EOL of 2.3 (https://github.com/atech/postal/issues/549 and https://github.com/atech/postal/issues/684)

@influenist would you be able to make a PR for the changes?

**Comment by saporus** [comment]
@willpower232 is @catphish really working on this update?

I think it is 14 days now, please try and do as you have written in this opened thread of yours.

We love Postal and we really needs more features added.

God bless.

**Comment by willpower232** [comment]
Its not for me to comment on really but I know he will get to it when he can.

**Comment by catphish** [comment]
Yes, I will be doing a release soon. Most likely this will be in a couple of stages:
1) Release current master, as it likely already contains well tested fixes.
2) Merge outstanding requests and release as beta
3) Hopefully after some testing, release the beta as final

**Comment by willpower232** [comment]
@catphish regarding current master, I think #674 is a real problem so probably best not to release that without being fixed (unless you meant a current master that wasn't on github)

**Comment by catphish** [comment]
Thanks, will be sure to address this first. Because of the time that's passed, I'm very keen to ensure that master is stable with upgraded libraries before embrarking on additional changes.

**Comment by catphish** [comment]
1ef7dbd67ee3476517ed98297050872f02deec3b has now been released as the stable package, and we are running it ourselves. This will likely solve outstanding compatibility issues due to numerous library upgrades. Once further testing is completed, and feedback has been received, I will start merging new pull requests.

**Comment by saporus** [comment]
Thanks and God bless for this.

More grease to your elbow.

**Comment by cmmata** [comment]
Great! Thank you! :clap:

**Comment by saporus** [comment]
Hello,

I trust you are doing great.

May I ask if this stable release will be compatible with Ubuntu 18.04 version?

Thanks

**Comment by willpower232** [comment]
That is a great question, Ubuntu 18.04 comes with Ruby 2.5 which may or may not be an issue as mentioned above.

It would be good to get confirmation of whether this will be okay, regardless of whether there is an install script or not.

**Comment by catphish** [comment]
It seems quite a lot of questions are about running this against new environments, MySQL 8, Ubuntu 18.04. We'll try to get some testing done shortly,

**Comment by saschaarthur** [comment]
any updates here? Also trieing to run it on mysql 8 and its just segfaulting..
