### ISSUE TITLE
Ubuntu 18.04 support

### ISSUE THREAD

**Issue by tchwpkgorg** [postalserver/postal#777]
There is an installation script for Ubuntu 16.04:

https://github.com/atech/postal/blob/master/script/install/ubuntu1604.sh

Does it work with Ubuntu 18.04?

**Comment by willpower232** [comment]
Hopefully yes but there is a very different version of Ruby in 18.04's packages.

This is being investigated as part of https://github.com/atech/postal/issues/755#issuecomment-476608056

**Comment by nenominal** [comment]
We are running postal on Ubuntu 18.04, but it was installed on 16.04 and we've updated the OS to 18.04, no issues so far (running it for months already)

**Comment by willpower232** [comment]
good to know!

**Comment by jaydrogers** [comment]
For what it's worth, just letting everyone know that I have Postal working on a **fresh install** of Ubuntu 18.04. I was able to automate a new/customized Postal server to be provisioned in about 3 minutes using Ansible. This includes:
* Postal
* MariaDB 10.3
* RabbitMQ
* nginx
* Certbot (Let's Encrypt)

There may need to be some changes to how the services are managed (I started a discussion here: https://github.com/atech/postal/issues/798), but hopefully there will be an official Docker support sometime in the future instead 😀

**Comment by pjv** [comment]
@jaydrogers can you make your ansible playbooks available?

**Comment by jaydrogers** [comment]
I just spent some time yesterday updating them to get them to work with MariaDB 10.4.

Let me see if I can get them into an "open source" style repository. There are a lot of moving parts, but it has been working really nicely so far.

Running a little swamped with other work right now, but I will try to get this done soon!

**Comment by willpower232** [comment]
@jaydrogers have you been able to get click tracking working in your environment? seems there might be a problem with HTTPS click tracking.

**Comment by jaydrogers** [comment]
Hi @willpower232 and @pjv,

I was able to get everything organized into a repository for reference. It's not in my "most optimal" method of delivery, but good enough to where you could use it or at least use bits and pieces from it.

View my Postal ansible repository here: https://github.com/521dimensions/ansible-postal

I am able to get HTTPS click tracking to work in my environment with my setup above.

**Comment by pjv** [comment]
Thanks very much for that @jaydrogers. Since I'm having trouble with the IP address of the DO droplet I'm using for my current postal instance, i will give your playbooks a spin and set up a vultr instance.

@willpower232 is there a simple method to migrate the data for my current postal instance on DO to a new one? Anything beyond simply exporting the mysql db and importing it on the other system? Or would i be better off just re-configuring the 4 servers I've created so far via the web interface on the new system?

**Comment by jaydrogers** [comment]
> @willpower232 is there a simple method to migrate the data for my current postal instance on DO to a new one? Anything beyond simply exporting the mysql db and importing it on the other system? Or would i be better off just re-configuring the 4 servers I've created so far via the web interface on the new system?

If it isnt too much work, I would re-create the servers using a standardized method. If you use my playbook, just export the databases and copy over the `/opt/postal/` directory. I make sure I keep all of the keys and everything else in that folder.

You can add multiple servers using my Ansible example under the `hosts` and `host_vars/` of the repo. Everything will be standardized that way for you too.

**Comment by pjv** [comment]
@jaydrogers I'm looking at your playbook now. Really nice work. A lot of the stuff in "common" overlaps with my own playbooks for ubuntu server setup. I'll run yours stock and then add my tweaks afterwards.

It looks like you are not using IPV6 at all, correct?

**Comment by jaydrogers** [comment]
Thanks! Correct, I have not tested this with IPv6.

**Comment by willpower232** [comment]
@pjv in theory, almost everything you want to save is in mysql databases so if you back them all up and restore them on another server, it should be pretty straightforward

**Comment by aaronstuder** [comment]
Any updates? :)

**Comment by PabloCastellano** [comment]
Ubuntu 20.04 LTS is now out, so maybe it's worth it focusing on this version now.

**Comment by willpower232** [comment]
Postal has recently been updated to support newer Ruby versions so it should work for the most part. I think there are a few little issues with the newer OpenSSL version however so your mileage may vary.

**Comment by dragoangel** [comment]
I think that for one node setup easiest way is support docker-compose which will provide ability to host Postal on any OS that work with docker correctly. Installation and upgrades with docker can be done by simple Git pull and docker-compose up -d script provided in same git repo.

**Comment by andrekutianski** [comment]
[install script](https://github.com/postalhq/postal/tree/master/script/install) for Ubuntu 18 and 16 are falling, the current repos and keys for Ruby and rabbitmq are outdated

**Comment by adamcooke** [comment]
These installation methods are no longer supported.
