### ISSUE TITLE
Installation guide wrong settings for nginx

### ISSUE THREAD

**Issue by erixtekila** [postalserver/postal#778]
Hi,

The installation guide is wrong @ https://github.com/atech/postal/wiki/Installation#configuring-nginx

```sh
sudo cp /opt/postal/app/resource/nginx.cfg /etc/nginx/sites-available/default

# You can create a self signed SSL certificate if you need to (otherwise put your own
# key & cert in /etc/nginx/ssl/postal.crt and postal.key)
sudo mkdir /etc/nginx/ssl/
sudo openssl req -x509 -newkey rsa:4096 -keyout /etc/nginx/ssl/postal.key -out /etc/nginx/ssl/postal.crt -days 365 -nodes
```

The default postal nginx settings uses this path `/etc/nginx/ssl/postal.cert` instead of `/etc/nginx/ssl/postal.crt`

**Comment by erixtekila** [comment]
The install script has a fix for this issue 
https://github.com/atech/postal/blob/master/script/install/ubuntu1604.sh

**Comment by willpower232** [comment]
Good spot, the certificate extension was standardised to `.cert` in the code back in https://github.com/atech/postal/issues/98 and https://github.com/atech/postal/pull/350 but the wiki got missed out so the code should be fine but hopefully someone will be able to update the wiki.

**Comment by erixtekila** [comment]
Great!

**Comment by adamcooke** [comment]
We no longer suggest using nginx.
