### ISSUE TITLE
More APIs

### ISSUE THREAD

**Issue by cruikshj** [postalserver/postal#82]
Great stuff.

Any plans for more APIs?  Looks like there is just a simple message and send API.  APIs for managing the various entities in the system would be awesome.

**Comment by adamcooke** [comment]
Yes. More API would be useful done these things. I don't have any immediate plans to add them myself but I'll keep this ticket open.

**Comment by masoodrahim** [comment]
@adamcooke Is it possible to add domains directly by injecting data into the database backend for Postal?  The reason I ask is that we really need the ability to add domains to the system but it doesn't look like there is an API capability for that.  Are there non-database elements that have to be created/modified for each newly added domain?

**Comment by willpower232** [comment]
All the information will be in the database

**Comment by gamalan** [comment]
I am interested at this. If somebody make PR for this case, will it be considered to be merged?

**Comment by adamcooke** [comment]
New API on the way soon.

**Comment by victorybiz** [comment]
@adamcooke @willpower232  Thanks for this amazing product. Is there any ETA for the New API with support for Domain API and User API? One of my apps depends on Postal and it is quite a tedious task adding and managing domains manually for hundreds of users.
