### ISSUE TITLE
DNS checks should use fully qualified names

### ISSUE THREAD

**Issue by hameno** [postalserver/postal#922]
I noticed that the code at https://github.com/postalhq/postal/blob/bb27d8c8a1703250a080caa0a182452aa4896783/app/models/domain/dns_checks.rb#L43 just uses the entered domain name without appending an "." (to make it fully qualified)
This means in certain configurations, e.g. ndots:5 in resolv.conf, will cause DNS checks to fail.

**Comment by willpower232** [comment]
Thanks @hameno are you experiencing this error currently?

**Comment by hameno** [comment]
Yes, I managed to reduce the ndots configuration in my kubernetes environment for the pod and it now works, but I believe this should be fixed

**Comment by willpower232** [comment]
Ah cool, I'll leave it open as a bug so it'll get sorted one way or the other

**Comment by adamcooke** [comment]
I imagine I'll never get an answer to this but presumably you have `use_local_ns_for_domains` enabled?

**Comment by hameno** [comment]
I'm not sure, what does this setting do exactly? don't remember setting it explicity (and not fully involved in that project anymore)

**Comment by adamcooke** [comment]
Postal will usually try to query directly with your nameservers for these DNS checks which really shouldn't be affected by the `ndots`. If not, it'll use your local resolvers. 


I can just add a trailing `.` to the end of the queries though for extra safety.

**Comment by adamcooke** [comment]
Please can you upgrade to the latest version of Postal and confirm whether this issue still exists? If so, please open a new issue for triage. Be sure to include any relevant log data as well as details about your environment as prompted by the new issue template.
